export interface SettingsSubcategoryHelpSection {
  heading: string;
  body: string;
}

export interface SettingsSubcategoryDoc {
  id: string;
  title: string;
  docsHref: `/docs/${string}`;
  summary: string;
  controls: string;
  recommended: string;
  risks: string;
  relatedDocs: string[];
  titleAliases?: readonly string[];
}

const settingsDocsPath = (anchor: string): `/docs/settings-${string}` => (
  `/docs/settings-${anchor}` as const
);

export const SETTINGS_SUBCATEGORY_DOCS = {
  "project-context": {
    id: "project-context",
    title: "Project Context",
    docsHref: settingsDocsPath("project-context"),
    summary: "Names and identifies the active project without changing the stored project id or execution history.",
    controls: "Project name is editable; project id, source type, and base directory explain how Code UX addresses and enters the workspace.",
    recommended: "Use a clear project name and keep the base directory aligned with the repository root workers should use.",
    risks: "Renaming is cosmetic, but an unexpected base directory usually means the project was created from the wrong path.",
    relatedDocs: ["Configuration and Storage", "Dashboard Guide"],
  },
  automation: {
    id: "automation",
    title: "Automation",
    docsHref: settingsDocsPath("automation"),
    summary: "Controls how much Code UX may continue without pausing for operator decisions.",
    controls: "Automation level sets the broad approval posture; auto-approve plans and auto-resume paused runs handle routine continuation points.",
    recommended: "Use Semi-auto for normal work, Full only for trusted projects, and Always ask for sensitive repositories.",
    risks: "More automation can move faster but may continue through a bad plan or stale context before you intervene.",
    relatedDocs: ["Operations Runbook", "Security Hardening"],
  },
  "docker-runtime": {
    id: "docker-runtime",
    title: "Docker Runtime",
    docsHref: settingsDocsPath("docker-runtime"),
    summary: "Defines the default container environment used by Docker-backed provider CLIs.",
    controls: "Image, setup script, memory limit, setup image caching, and Playwright browser preinstall shape each worker container.",
    recommended: "Keep the default image unless your repo needs a custom toolchain; enable Playwright browser preload for browser-heavy QA.",
    risks: "Broken setup scripts or overly tight memory limits can fail every provider invocation in the scope.",
    relatedDocs: ["Configuration and Storage", "Security Hardening"],
  },
  "system-runtime": {
    id: "system-runtime",
    title: "System Runtime",
    docsHref: settingsDocsPath("system-runtime"),
    summary: "Configures dashboard port and runtime logging behavior for the local Code UX process.",
    controls: "Dashboard port controls the HTTP listener; console and debug-file levels control log verbosity.",
    recommended: "Keep port 4444 and info/error logging for daily use; raise verbosity only while debugging.",
    risks: "Changing the port requires reconnecting clients, and debug logging may write large local files.",
    relatedDocs: ["Operations Runbook", "Logging and Correlation IDs"],
  },
  "restart-behavior": {
    id: "restart-behavior",
    title: "Restart Behavior",
    docsHref: settingsDocsPath("restart-behavior"),
    summary: "Chooses how active sprints and interrupted provider invocations are reconciled after the app restarts.",
    controls: "Sprint policy continues, pauses, or cancels active sprints; invocation policy continues, cancels, or restarts interrupted work.",
    recommended: "Continue sprints and continue invocations for local development; pause when you want manual review after downtime.",
    risks: "Restarting interrupted work can duplicate provider effort if the previous CLI run was still externally active.",
    relatedDocs: ["Operations Runbook", "Atomic Sprint Loop"],
  },
  "database-settings": {
    id: "database-settings",
    title: "Database Settings",
    docsHref: settingsDocsPath("database-settings"),
    summary: "Manages local SQLite retention and maintenance for runtime activity data.",
    controls: "Pruning removes old completed activity, retention sets the age window, and vacuum compacts storage on startup.",
    recommended: "Keep pruning and vacuum enabled unless you are preserving local forensic history.",
    risks: "Short retention can remove useful troubleshooting detail; disabling pruning can grow the local DB quickly.",
    relatedDocs: ["Configuration and Storage", "Operations Runbook"],
  },
  onboarding: {
    id: "onboarding",
    title: "Onboarding",
    docsHref: settingsDocsPath("onboarding"),
    summary: "Reopens the guided setup flow without changing saved settings by itself.",
    controls: "The action button launches onboarding so you can revisit provider, project, and setup prompts.",
    recommended: "Use it when setting up a new machine or after adding provider credentials.",
    risks: "Saving new onboarding choices can overwrite the current system defaults.",
    relatedDocs: ["Dashboard Onboarding", "Quickstart"],
  },
  "display-settings": {
    id: "display-settings",
    title: "Display Settings",
    docsHref: settingsDocsPath("display-settings"),
    summary: "Controls the dashboard shell layout, theme, motion preference, and desktop zoom when available.",
    controls: "Navigation mode switches dock/sidebar, theme sets color mode, reduced motion limits animation, and zoom scales Electron windows.",
    recommended: "Use System theme and Auto reduced motion unless you need a fixed accessibility preference.",
    risks: "High zoom or dense sidebars can reduce visible workspace on small screens.",
    relatedDocs: ["Dashboard Accessibility Patterns", "Mobile Responsiveness"],
  },
  background: {
    id: "background",
    title: "Background",
    docsHref: settingsDocsPath("background"),
    summary: "Customizes the dashboard background image, animation mode, static color, and pattern overlay.",
    controls: "Image upload, animated/static mode, animation style, color picker, and overlay pattern shape the visual layer behind panels.",
    recommended: "Prefer lightweight images and readable contrast; use static mode if motion is distracting.",
    risks: "Large images and busy patterns can hurt performance or reduce text contrast.",
    relatedDocs: ["Dashboard Design System", "Mobile Responsiveness"],
  },
  "default-routing-anchors": {
    id: "default-routing-anchors",
    title: "Default Routing Anchors",
    docsHref: settingsDocsPath("default-routing-anchors"),
    summary: "Sets the global and worker provider instances used when invocation routes inherit defaults.",
    controls: "Global and worker defaults choose named provider instances and base models; concurrency and timeout cap worker dispatch.",
    recommended: "Pick stable, authenticated instances for both anchors before fine-tuning route overrides.",
    risks: "Unconfigured anchors leave inherited routes without a usable provider.",
    relatedDocs: ["Provider Routing", "Configuration and Storage"],
  },
  "base-provider-configuration": {
    id: "base-provider-configuration",
    title: "Base Provider Configuration",
    docsHref: settingsDocsPath("base-provider-configuration"),
    summary: "Defines each named provider instance's default eligibility, model, thinking depth, weight, and concurrency.",
    controls: "Provider cards set default route participation, model, thinking mode, weighted routing weight, and max concurrent tasks.",
    recommended: "Keep only healthy instances eligible and use weights to express preference rather than hard pinning every route.",
    risks: "Incompatible model choices or high concurrency can cause repeated provider failures or quota pressure.",
    relatedDocs: ["Provider Routing", "Qwen Code Integration", "OpenCode Integration"],
  },
  "route-mapping": {
    id: "route-mapping",
    title: "Route Mapping",
    docsHref: settingsDocsPath("route-mapping"),
    summary: "Routes each invocation type to inherited, manual, weighted, or agent-selected provider pools.",
    controls: "Each route chooses a profile, strategy, primary instance, allowed weighted pool, and per-provider overrides.",
    recommended: "Use inherited defaults first, then override high-risk routes such as planning, QA, CI repair, and remediation.",
    risks: "Weighted pools with unavailable providers can spread failures across multiple task types.",
    relatedDocs: ["Provider Routing", "Atomic Sprint Loop"],
  },
  "model-pricing": {
    id: "model-pricing",
    title: "Model Pricing",
    docsHref: settingsDocsPath("model-pricing"),
    summary: "Stores token pricing metadata used for model cost estimates in dashboard views.",
    controls: "Pricing rows define per-model input and output token costs where the dashboard can estimate usage.",
    recommended: "Keep prices current for providers you actively route to and leave unknown models unset.",
    risks: "Outdated prices affect estimates only; they do not change provider billing.",
    relatedDocs: ["Provider Routing", "Dashboard Guide"],
  },
  "git-flow": {
    id: "git-flow",
    title: "Git Flow",
    docsHref: settingsDocsPath("git-flow"),
    summary: "Controls branch naming, PR creation, issue closure, and cleanup for sprint work.",
    controls: "Git mode, default branch, prefixes, sprint key, branch template, PR toggles, linked issue closure, and branch deletion define the workflow.",
    recommended: "Use Remote mode for PR/CI automation and Local mode for repositories where Code UX must not touch remotes.",
    risks: "Wrong default branches or aggressive cleanup can disrupt expected repository flow.",
    relatedDocs: ["Operations Runbook", "Instruction Template System"],
  },
  "merge-gates-autofix": {
    id: "merge-gates-autofix",
    title: "Merge Gates & Autofix",
    titleAliases: ["Merge Gates & Autofix (Unavailable in Local Mode)"],
    docsHref: settingsDocsPath("merge-gates-autofix"),
    summary: "Configures review, conflict, CI, and auto-merge gates for feature and main-branch merges.",
    controls: "Comment resolution, conflict repair, CI repair, feature PR auto-merge, and main PR auto-merge shape merge readiness.",
    recommended: "Require green checks and resolved comments for shared branches; use immediate auto-merge only in low-risk repositories.",
    risks: "Relaxed merge gates can land incomplete work; Local mode disables remote PR gates by design.",
    relatedDocs: ["Operations Runbook", "Security Hardening"],
  },
  "quality-assurance": {
    id: "quality-assurance",
    title: "Quality Assurance",
    docsHref: settingsDocsPath("quality-assurance"),
    summary: "Controls completion-time QA review, QA routing, and trigger-specific agent assignment.",
    controls: "QA toggles, route choices, and trigger selectors decide when and how final reviews run.",
    recommended: "Keep QA enabled for multi-task sprints and route it to a provider with strong review behavior.",
    risks: "Disabling QA removes an important last check before merge automation continues.",
    relatedDocs: ["Quality Assurance Agent", "Provider Routing"],
  },
  guardrails: {
    id: "guardrails",
    title: "Guardrails",
    docsHref: settingsDocsPath("guardrails"),
    summary: "Caps repeated agent jobs so runaway planning, coding, CI, merge, clarification, or remediation loops stop predictably.",
    controls: "Per-job caps and on-limit actions determine whether Code UX blocks, waits, warns, or continues.",
    recommended: "Keep guardrails enabled and use block-and-escalate for expensive or destructive job types.",
    risks: "Very high caps can burn provider quota; very low caps can stop recoverable work too early.",
    relatedDocs: ["Quality Guardrails", "Operations Runbook"],
  },
  "rate-limit": {
    id: "rate-limit",
    title: "Rate Limit",
    docsHref: settingsDocsPath("rate-limit"),
    summary: "Controls retries after provider quota or rate-limit responses.",
    controls: "Quota reset waits, fixed retry delays, retry counts, and no-timer quota retry caps define retry behavior.",
    recommended: "Retry on concrete quota reset timers and keep fixed retries modest.",
    risks: "Aggressive retries can keep failing tasks occupied and delay operator escalation.",
    relatedDocs: ["Operations Runbook", "Provider Routing"],
  },
  "watch-loop": {
    id: "watch-loop",
    title: "Watch Loop",
    docsHref: settingsDocsPath("watch-loop"),
    summary: "Controls whether live sprint orchestration keeps polling and how frequently it emits work.",
    controls: "The watch-loop toggle, evaluation interval, and output interval drive recurring orchestration checks.",
    recommended: "Keep the loop enabled with moderate intervals for active sprints.",
    risks: "Very short intervals can add noise; disabling the loop means progress depends on manual or external triggers.",
    relatedDocs: ["Atomic Sprint Loop", "Operations Runbook"],
  },
  "workspace-hygiene": {
    id: "workspace-hygiene",
    title: "Workspace Hygiene",
    docsHref: settingsDocsPath("workspace-hygiene"),
    summary: "Controls cleanup of temporary worktree state after provider CLI runs.",
    controls: "Success and failure cleanup toggles decide whether Code UX removes temporary execution workspace state.",
    recommended: "Clean successful worktrees and keep failed worktrees only when you are actively debugging.",
    risks: "Keeping failed worktrees can consume disk; removing them can erase useful repro artifacts.",
    relatedDocs: ["Operations Runbook", "Security Hardening"],
  },
  "workspace-visibility": {
    id: "workspace-visibility",
    title: "Workspace Visibility",
    docsHref: settingsDocsPath("workspace-visibility"),
    summary: "Controls automatic preview lifecycle and whether browser workspace entry points appear in the dashboard.",
    controls: "Preview enablement, in-app browser visibility, auto-start, rebuild triggers, and auto-stop define the preview lifecycle.",
    recommended: "Enable previews for UI projects and stop terminal previews automatically to conserve local resources.",
    risks: "Automatic rebuilds can be noisy for slow projects or heavy Docker images.",
    relatedDocs: ["Browser Preview", "Sprint Preview Browser"],
  },
  "runtime-limits": {
    id: "runtime-limits",
    title: "Runtime Limits",
    docsHref: settingsDocsPath("runtime-limits"),
    summary: "Sets preview container concurrency, host port range, app port, and startup script path.",
    controls: "Container cap, host port start/end, internal app port, and startup override path decide how previews launch.",
    recommended: "Keep preview ports on localhost-only ranges and set the app port to the project dev server port.",
    risks: "Port collisions or wrong startup scripts prevent previews from becoming reachable.",
    relatedDocs: ["Browser Preview", "Security Hardening"],
  },
  techstacks: {
    id: "techstacks",
    title: "Techstacks",
    titleAliases: ["Techstacks Catalog", "Project Techstack"],
    docsHref: settingsDocsPath("techstacks"),
    summary: "Manages the system techstack catalog and per-project techstack/application-kind assignment.",
    controls: "System scope owns stack entries, default-stack selection, and technology items; project scope chooses a stack, clears to Unassigned, and selects web or desktop app kind.",
    recommended: "Keep imported projects unassigned until setup or an operator identifies the stack; use the built-in Code UX stack only for Code UX-style Preact dashboards.",
    risks: "Deleting custom stacks clears references to them, while the built-in Code UX Stack is protected and restored by settings normalization.",
    relatedDocs: ["Configuration and Storage", "Settings Reference"],
  },
  guidance: {
    id: "guidance",
    title: "Guidance",
    titleAliases: ["Tech Stack", "Styleguide", "Custom styleguides", "Custom tech stack guidance"],
    docsHref: settingsDocsPath("guidance"),
    summary: "Manages selected tech-stack and styleguide guidance plus custom instruction entries for the active settings scope.",
    controls: "Each section has a selector with None support, custom entry add/edit/delete controls, and styleguide visibility controls for hiding built-in defaults from the UI.",
    recommended: "Use None until a scope needs explicit design guidance; keep custom ids stable once projects or sprints reference them.",
    risks: "Built-in guidance is protected. Deleting a selected custom entry clears that selection back to None for the edited scope.",
    relatedDocs: ["Configuration and Storage", "Settings Reference"],
  },
  "project-markdown-mirror": {
    id: "project-markdown-mirror",
    title: "Project Markdown Mirror",
    docsHref: settingsDocsPath("project-markdown-mirror"),
    summary: "Controls whether dashboard-authored agent presets are mirrored into project-local markdown files.",
    controls: "The mirror toggle writes companion files under `.code-ux/agents` for selected project agents.",
    recommended: "Enable it when agent instructions should be reviewable with project changes.",
    risks: "Mirrored files can make agent edits visible in repository diffs if `.code-ux/agents` is tracked.",
    relatedDocs: ["Agent Sync And Planning Agent", "Agent Routing"],
  },
  "agent-routing": {
    id: "agent-routing",
    title: "Agent Routing",
    docsHref: settingsDocsPath("agent-routing"),
    summary: "Assigns built-in or project agent presets to planning, coding, CI, merge, dashboard, and clarification work.",
    controls: "Coding can be manual or orchestrator-selected; each route can use a project preset or built-in fallback.",
    recommended: "Use built-ins first, then assign specialists where project-specific instructions materially improve outcomes.",
    risks: "Missing or overly narrow project agents can reduce task quality or block routing choices.",
    relatedDocs: ["Agent Routing", "Agent Knowledge Base"],
  },
  "memory-system": {
    id: "memory-system",
    title: "Memory System",
    docsHref: settingsDocsPath("memory-system"),
    summary: "Controls capture, promotion, and remediation of sprint and project memory.",
    controls: "Enablement, sprint capture, agent capture, auto-promotion, and remediation mode decide what knowledge is stored and curated.",
    recommended: "Enable memory with deterministic remediation unless you need AI-assisted cleanup.",
    risks: "Disabling memory reduces long-term learning; AI remediation consumes routed provider capacity.",
    relatedDocs: ["Memory Architecture and Search", "Memory Claims and Evidence"],
  },
  "long-term-remediation-schedule": {
    id: "long-term-remediation-schedule",
    title: "Long-Term Remediation Schedule",
    docsHref: settingsDocsPath("long-term-remediation-schedule"),
    summary: "Schedules recurring project memory cleanup and claim maintenance.",
    controls: "Cadence, remediation mode, and local run time create or pause a project-specific scheduler entry.",
    recommended: "Use weekly deterministic cleanup for active projects with steady sprint volume.",
    risks: "AI cleanup schedules can surprise provider budgets if routed to expensive models.",
    relatedDocs: ["Scheduler", "Memory Architecture and Search"],
  },
  limits: {
    id: "limits",
    title: "Limits",
    docsHref: settingsDocsPath("limits"),
    summary: "Caps memory promotion thresholds, retained memories, graph density, and remediation promotions.",
    controls: "Thresholds and maximum counts bound sprint/project memory volume and neural-map edge density.",
    recommended: "Keep defaults until memory search becomes noisy or storage grows too quickly.",
    risks: "Low limits can evict useful knowledge; high graph density can make maps harder to inspect.",
    relatedDocs: ["Memory Architecture and Search", "Memory Claims and Evidence"],
  },
  "embedding-provider": {
    id: "embedding-provider",
    title: "Embedding Provider",
    docsHref: settingsDocsPath("embedding-provider"),
    summary: "Chooses in-app embeddings or an external OpenAI-compatible embeddings API.",
    controls: "Backend, external URL, model id, and API key control semantic memory embedding.",
    recommended: "Use in-app models for local-first operation; use external APIs only when you need a managed embedding model.",
    risks: "External APIs send memory text to the configured endpoint and require careful key handling.",
    relatedDocs: ["Memory Architecture and Search", "Security Hardening"],
  },
  "worker-learnings-instruction": {
    id: "worker-learnings-instruction",
    title: "Worker Learnings Instruction",
    docsHref: settingsDocsPath("worker-learnings-instruction"),
    summary: "Defines the prompt appended to worker tasks so useful lessons are captured for memory processing.",
    controls: "The text area controls exactly what workers are asked to observe and write into the temporary learnings file.",
    recommended: "Keep instructions specific to reusable engineering lessons and avoid asking workers to record secrets.",
    risks: "Overbroad instructions can capture noisy or sensitive details.",
    relatedDocs: ["Memory Architecture and Search", "Instruction Template System"],
  },
  integrations: {
    id: "integrations",
    title: "Integrations",
    docsHref: settingsDocsPath("integrations"),
    summary: "Lists provider, git-host, issue-tracker, and read-only importer integrations and exposes manage/add actions.",
    controls: "Cards show connection state, auth hints, active/configured importer status, and management entry points; host hints can import detected local settings.",
    recommended: "Configure provider and importer credentials at system scope and use project overrides only for repository-specific git hosts or importer defaults.",
    risks: "Imported hints can reveal local auth paths; broad importer tokens can expose external workspaces to search.",
    relatedDocs: ["Configuration and Storage", "Security Hardening"],
  },
  "jules-automation": {
    id: "jules-automation",
    title: "Jules Automation",
    docsHref: settingsDocsPath("jules-automation"),
    summary: "Configures Jules clarification automation and CI autofix handoff behavior.",
    controls: "Clarification auto-answer, answer mode/template, Jules CI autofix, and retry cap decide when hosted Jules automation runs.",
    recommended: "Use template answers for routine clarifications and keep retry caps low.",
    risks: "Automatic clarification replies can answer with stale assumptions if the template is too broad.",
    relatedDocs: ["Operations Runbook", "Provider Routing"],
  },
  "git-host-configuration": {
    id: "git-host-configuration",
    title: "Git Host Configuration",
    titleAliases: ["GitHub Configuration", "GitLab Configuration"],
    docsHref: settingsDocsPath("git-host-configuration"),
    summary: "Stores GitHub or GitLab tokens and Docker git-auth behavior for repository automation.",
    controls: "Tokens, GitHub auth mounting, auth paths, local git config copy, and container git identity control remote repository access.",
    recommended: "Prefer least-privilege tokens and use local auth copy only on trusted machines.",
    risks: "Tokens and copied auth directories can grant repository write access inside provider containers.",
    relatedDocs: ["Security Hardening", "Operations Runbook"],
  },
  "jira-configuration": {
    id: "jira-configuration",
    title: "Jira Configuration",
    docsHref: settingsDocsPath("jira-configuration"),
    summary: "Connects Jira issue search, import transitions, and completion transitions.",
    controls: "Site URL, account email, API token, project key, transition names, and move/close toggles drive Jira automation.",
    recommended: "Use a dedicated API token and test transition names against the target Jira workflow.",
    risks: "Wrong transition names prevent issue movement; broad tokens expose more Jira scope than needed.",
    relatedDocs: ["Sprint Imports", "Security Hardening"],
  },
  "importer-configuration": {
    id: "importer-configuration",
    title: "Importer Configuration",
    titleAliases: ["Notion Configuration", "Asana Configuration", "Linear Configuration", "Miro Configuration", "Lucid Configuration", "Figma / FigJam Configuration", "Mural Configuration"],
    docsHref: settingsDocsPath("importer-configuration"),
    summary: "Configures read-only external work imports for project management, whiteboard, diagram, and design providers.",
    controls: "Enablement, API token, optional secret, base URL, default IDs, and search limit decide when each importer is active.",
    recommended: "Store shared credentials at system scope, then add project overrides only when one project needs different defaults.",
    risks: "Broad tokens can expose external workspaces to import searches; use read-only or least-privilege credentials where providers support them.",
    relatedDocs: ["Sprint Imports", "Security Hardening"],
  },
  "provider-integration": {
    id: "provider-integration",
    title: "Provider Integration",
    titleAliases: ["Jules Integration", "Gemini Integration", "Codex Integration", "Claude Code Integration", "Qwen Code Integration", "OpenCode Integration", "Antigravity Integration"],
    docsHref: settingsDocsPath("provider-integration"),
    summary: "Explains that provider credentials are system-owned while project scopes still control routing and auth-copy behavior.",
    controls: "The notices clarify where provider instances live and which settings remain project-scoped.",
    recommended: "Switch to system scope to add credentials, then route them from AI Models.",
    risks: "Expecting project scope to create credentials can leave routes without provider instances.",
    relatedDocs: ["Provider Routing", "Configuration and Storage"],
  },
  "provider-credentials": {
    id: "provider-credentials",
    title: "Provider Credentials",
    titleAliases: ["Jules Credentials", "Gemini Credentials", "Codex Credentials", "Claude Code Credentials", "Qwen Code Credentials", "OpenCode Credentials", "Antigravity Credentials"],
    docsHref: settingsDocsPath("provider-credentials"),
    summary: "Manages named provider instances, authentication mode, local auth copy, dashboard login, provider config files, and base model defaults.",
    controls: "Each instance owns API key/auth path/login/config-file mode plus routing-visible identity and availability.",
    recommended: "Use named instances per account or quota pool; use Provider Config File only when a CLI needs a specific config copied.",
    risks: "Local auth copy and config-file mounts expose host credentials to Docker-backed provider runs.",
    relatedDocs: ["Provider Routing", "Qwen Code Integration", "OpenCode Integration", "Security Hardening"],
  },
  "mcp-servers": {
    id: "mcp-servers",
    title: "MCP Servers",
    docsHref: settingsDocsPath("mcp-servers"),
    summary: "Lists built-in and custom MCP servers injected into provider CLI runtimes.",
    controls: "The list configures built-in tool access, custom server enablement, transport, provider restrictions, and server creation.",
    recommended: "Keep built-in tools enabled and restrict custom servers to the CLIs that need them.",
    risks: "Broad custom MCP access can expose external tools to more providers than intended.",
    relatedDocs: ["MCP Tools and Contracts", "MCP Runtime and Dispatch"],
  },
  "built-in-mcp": {
    id: "built-in-mcp",
    title: "Built-in MCP (Code UX)",
    docsHref: settingsDocsPath("built-in-mcp"),
    summary: "Controls which built-in Code UX MCP tool categories are available to containerized CLIs.",
    controls: "Tool-category and individual-tool toggles decide what providers may call on their next run.",
    recommended: "Disable only categories you know a provider should not access.",
    risks: "Disabling required tools can make provider workflows fail; enabling broad tools increases capability exposure.",
    relatedDocs: ["MCP Tools and Contracts", "Security Hardening"],
  },
  "mcp-tool-category": {
    id: "mcp-tool-category",
    title: "MCP Tool Category",
    docsHref: settingsDocsPath("mcp-tool-category"),
    summary: "Enables or disables one built-in MCP tool category and its individual tools.",
    controls: "The category toggle sets all tools in the group; each row can override a specific tool.",
    recommended: "Keep category-level changes coarse and document why any tool is disabled.",
    risks: "Fine-grained disablement can be hard to diagnose when a provider expects a missing tool.",
    relatedDocs: ["MCP Tools and Contracts", "MCP Runtime and Dispatch"],
  },
  "custom-mcp-server": {
    id: "custom-mcp-server",
    title: "Custom MCP Server",
    titleAliases: ["MCP server"],
    docsHref: settingsDocsPath("custom-mcp-server"),
    summary: "Configures one custom MCP server injected into compatible provider CLIs.",
    controls: "Display name, server key, transport, URL or command, args/env/headers, description, CLI restrictions, and preview define the server.",
    recommended: "Prefer HTTP/SSE for managed remote servers and restrict sensitive servers to specific CLIs.",
    risks: "Invalid JSON, unavailable commands, or leaked auth headers can break provider startup or expose secrets.",
    relatedDocs: ["External MCP Worker Client", "Security Hardening"],
  },
  "danger-zone": {
    id: "danger-zone",
    title: "Danger Zone",
    docsHref: settingsDocsPath("danger-zone"),
    summary: "Groups irreversible project deletion and project override reset actions.",
    controls: "Project reset clears saved overrides; project delete removes the project and associated local runtime data.",
    recommended: "Reset overrides before deleting a project when you only need to return to inherited defaults.",
    risks: "Delete actions are irreversible after confirmation.",
    relatedDocs: ["Operations Runbook", "Configuration and Storage"],
  },
  "project-memory": {
    id: "project-memory",
    title: "Project Memory",
    docsHref: settingsDocsPath("project-memory"),
    summary: "Clears selected memory tiers for the active project only.",
    controls: "Short-term, long-term, and all-memory actions remove progressively broader memory records.",
    recommended: "Clear short-term first when fixing noisy sprint memory; use all-memory only for a full project memory reset.",
    risks: "Clearing long-term or all memory removes claims, evidence, and vectors permanently.",
    relatedDocs: ["Memory Claims and Evidence", "Memory Architecture and Search"],
  },
  "system-memory": {
    id: "system-memory",
    title: "System Memory",
    docsHref: settingsDocsPath("system-memory"),
    summary: "Clears memory tiers across every project in the local database.",
    controls: "Short-term, long-term, and all-memory actions apply globally.",
    recommended: "Use only during local maintenance or after confirming no project needs the retained knowledge.",
    risks: "System memory clears are broad and irreversible.",
    relatedDocs: ["Memory Claims and Evidence", "Operations Runbook"],
  },
  "system-database": {
    id: "system-database",
    title: "System Database",
    docsHref: settingsDocsPath("system-database"),
    summary: "Wipes the local Code UX database so the app returns to a clean state on reload.",
    controls: "The hard reset action removes projects, sprints, tasks, histories, and system state.",
    recommended: "Use only for local reset or unrecoverable database corruption after exporting anything needed.",
    risks: "This deletes all local runtime state and cannot be undone from the dashboard.",
    relatedDocs: ["Configuration and Storage", "Operations Runbook"],
  },
} as const satisfies Record<string, SettingsSubcategoryDoc>;

export type SettingsSubcategoryId = keyof typeof SETTINGS_SUBCATEGORY_DOCS;

const normalizeTitle = (title: string): string => (
  title
    .replace(/\s+\([^)]*\)$/u, "")
    .trim()
    .toLowerCase()
);

const TITLE_TO_ID = new Map<string, SettingsSubcategoryId>(
  Object.entries(SETTINGS_SUBCATEGORY_DOCS).flatMap(([id, doc]) => {
    const entry = doc as SettingsSubcategoryDoc;
    return [entry.title, ...(entry.titleAliases ?? [])].map((title) => [normalizeTitle(title), id as SettingsSubcategoryId]);
  }),
);

export const getSettingsSubcategoryDoc = (
  idOrTitle: SettingsSubcategoryId | string | undefined,
): SettingsSubcategoryDoc | undefined => {
  if (!idOrTitle) {
    return undefined;
  }
  if (idOrTitle in SETTINGS_SUBCATEGORY_DOCS) {
    return SETTINGS_SUBCATEGORY_DOCS[idOrTitle as SettingsSubcategoryId];
  }
  const resolvedId = TITLE_TO_ID.get(normalizeTitle(idOrTitle));
  return resolvedId ? SETTINGS_SUBCATEGORY_DOCS[resolvedId] : undefined;
};

export const toHelpSections = (doc: SettingsSubcategoryDoc): SettingsSubcategoryHelpSection[] => [
  { heading: "Controls", body: doc.controls },
  { heading: "Recommended default", body: doc.recommended },
  { heading: "Risks and gotchas", body: doc.risks },
];
