import type { DashboardLocale } from "../i18n/locales.js";
import { getDocumentDashboardLocale, getSettingsShellMessage } from "../i18n/messages/settings-shell.js";

export interface SettingsSubcategoryHelpSection {
  heading: string;
  body: string;
}

export interface SettingsSubcategoryDoc {
  id: string;
  title: string;
  docsHref: `/docs/${string}`;
  summary: string;
  controls: string;
  recommended: string;
  risks: string;
  relatedDocs: string[];
  titleAliases?: readonly string[];
}

const settingsDocsPath = (anchor: string): `/docs/settings-${string}` => (
  `/docs/settings-${anchor}` as const
);

export const SETTINGS_SUBCATEGORY_DOCS = {
  "project-context": {
    id: "project-context",
    title: "Project Context",
    docsHref: settingsDocsPath("project-context"),
    summary: "Names and identifies the active project without changing the stored project id or execution history.",
    controls: "Project name is editable; project id, source type, and base directory explain how Code UX addresses and enters the workspace.",
    recommended: "Use a clear project name and keep the base directory aligned with the repository root workers should use.",
    risks: "Renaming is cosmetic, but an unexpected base directory usually means the project was created from the wrong path.",
    relatedDocs: ["Configuration and Storage", "Dashboard Guide"],
  },
  automation: {
    id: "automation",
    title: "Automation",
    docsHref: settingsDocsPath("automation"),
    summary: "Controls how much Code UX may continue without pausing for operator decisions.",
    controls: "Automation level sets the broad approval posture; auto-approve plans and auto-resume paused runs handle routine continuation points.",
    recommended: "Use Semi-auto for normal work, Full only for trusted projects, and Always ask for sensitive repositories.",
    risks: "More automation can move faster but may continue through a bad plan or stale context before you intervene.",
    relatedDocs: ["Operations Runbook", "Security Hardening"],
  },
  "docker-runtime": {
    id: "docker-runtime",
    title: "Docker Runtime",
    docsHref: settingsDocsPath("docker-runtime"),
    summary: "Defines the default container environment used by Docker-backed provider CLIs.",
    controls: "Image, setup script, memory limit, setup image caching, and Playwright browser preinstall shape each worker container.",
    recommended: "Keep the default image unless your repo needs a custom toolchain; enable Playwright browser preload for browser-heavy QA.",
    risks: "Broken setup scripts or overly tight memory limits can fail every provider invocation in the scope.",
    relatedDocs: ["Configuration and Storage", "Security Hardening"],
  },
  "system-runtime": {
    id: "system-runtime",
    title: "System Runtime",
    docsHref: settingsDocsPath("system-runtime"),
    summary: "Configures dashboard port and runtime logging behavior for the local Code UX process.",
    controls: "Dashboard port controls the HTTP listener; console and debug-file levels control log verbosity.",
    recommended: "Keep port 4444 and info/error logging for daily use; raise verbosity only while debugging.",
    risks: "Changing the port requires reconnecting clients, and debug logging may write large local files.",
    relatedDocs: ["Operations Runbook", "Logging and Correlation IDs"],
  },
  "restart-behavior": {
    id: "restart-behavior",
    title: "Restart Behavior",
    docsHref: settingsDocsPath("restart-behavior"),
    summary: "Chooses how active sprints and interrupted provider invocations are reconciled after the app restarts.",
    controls: "Sprint policy continues, pauses, or cancels active sprints; invocation policy continues, cancels, or restarts interrupted work.",
    recommended: "Continue sprints and continue invocations for local development; pause when you want manual review after downtime.",
    risks: "Restarting interrupted work can duplicate provider effort if the previous CLI run was still externally active.",
    relatedDocs: ["Operations Runbook", "Atomic Sprint Loop"],
  },
  "database-settings": {
    id: "database-settings",
    title: "Database Settings",
    docsHref: settingsDocsPath("database-settings"),
    summary: "Manages local SQLite retention and maintenance for runtime activity data.",
    controls: "Pruning removes old completed activity, retention sets the age window, and vacuum compacts storage on startup.",
    recommended: "Keep pruning and vacuum enabled unless you are preserving local forensic history.",
    risks: "Short retention can remove useful troubleshooting detail; disabling pruning can grow the local DB quickly.",
    relatedDocs: ["Configuration and Storage", "Operations Runbook"],
  },
  onboarding: {
    id: "onboarding",
    title: "Onboarding",
    docsHref: settingsDocsPath("onboarding"),
    summary: "Reopens the guided setup flow without changing saved settings by itself.",
    controls: "The action button launches onboarding so you can revisit provider, project, and setup prompts.",
    recommended: "Use it when setting up a new machine or after adding provider credentials.",
    risks: "Saving new onboarding choices can overwrite the current system defaults.",
    relatedDocs: ["Dashboard Onboarding", "Quickstart"],
  },
  "display-settings": {
    id: "display-settings",
    title: "Display Settings",
    docsHref: settingsDocsPath("display-settings"),
    summary: "Controls the dashboard shell layout, theme, accent color, motion preference, and desktop zoom when available.",
    controls: "Navigation mode switches dock/sidebar, theme sets color mode, reduced motion limits animation, and zoom scales Electron windows.",
    recommended: "Use System theme and Auto reduced motion unless you need a fixed accessibility preference.",
    risks: "High zoom or dense sidebars can reduce visible workspace on small screens.",
    relatedDocs: ["Dashboard Accessibility Patterns", "Mobile Responsiveness"],
  },
  background: {
    id: "background",
    title: "Background",
    docsHref: settingsDocsPath("background"),
    summary: "Customizes the dashboard background image, animation mode, static color, and pattern overlay.",
    controls: "Image upload, animated/static mode, animation style, color picker, and overlay pattern shape the visual layer behind panels.",
    recommended: "Prefer lightweight images and readable contrast; use static mode if motion is distracting.",
    risks: "Large images and busy patterns can hurt performance or reduce text contrast.",
    relatedDocs: ["Dashboard Design System", "Mobile Responsiveness"],
  },
  "default-routing-anchors": {
    id: "default-routing-anchors",
    title: "Default Routing Anchors",
    docsHref: settingsDocsPath("default-routing-anchors"),
    summary: "Sets the global and worker provider instances used when invocation routes inherit defaults.",
    controls: "Global and worker defaults choose named provider instances and base models; concurrency and timeout cap worker dispatch.",
    recommended: "Pick stable, authenticated instances for both anchors before fine-tuning route overrides.",
    risks: "Unconfigured anchors leave inherited routes without a usable provider.",
    relatedDocs: ["Provider Routing", "Configuration and Storage"],
  },
  "base-provider-configuration": {
    id: "base-provider-configuration",
    title: "Base Provider Configuration",
    docsHref: settingsDocsPath("base-provider-configuration"),
    summary: "Defines each named provider instance's default eligibility, model, thinking depth, weight, and concurrency.",
    controls: "Provider cards set default route participation, model, thinking mode, weighted routing weight, and max concurrent tasks.",
    recommended: "Keep only healthy instances eligible and use weights to express preference rather than hard pinning every route.",
    risks: "Incompatible model choices or high concurrency can cause repeated provider failures or quota pressure.",
    relatedDocs: ["Provider Routing", "Qwen Code Integration", "OpenCode Integration"],
  },
  "route-mapping": {
    id: "route-mapping",
    title: "Route Mapping",
    docsHref: settingsDocsPath("route-mapping"),
    summary: "Routes each invocation type to inherited, manual, weighted, or agent-selected provider pools.",
    controls: "Each route chooses a profile, strategy, primary instance, allowed weighted pool, and per-provider overrides.",
    recommended: "Use inherited defaults first, then override high-risk routes such as planning, QA, CI repair, and remediation.",
    risks: "Weighted pools with unavailable providers can spread failures across multiple task types.",
    relatedDocs: ["Provider Routing", "Atomic Sprint Loop"],
  },
  "model-pricing": {
    id: "model-pricing",
    title: "Model Pricing",
    docsHref: settingsDocsPath("model-pricing"),
    summary: "Stores token pricing metadata used for model cost estimates in dashboard views.",
    controls: "Pricing rows define per-model input and output token costs where the dashboard can estimate usage.",
    recommended: "Keep prices current for providers you actively route to and leave unknown models unset.",
    risks: "Outdated prices affect estimates only; they do not change provider billing.",
    relatedDocs: ["Provider Routing", "Dashboard Guide"],
  },
  "git-flow": {
    id: "git-flow",
    title: "Git Flow",
    docsHref: settingsDocsPath("git-flow"),
    summary: "Controls branch naming, PR creation, issue closure, and cleanup for sprint work.",
    controls: "Git mode, default branch, prefixes, sprint key, branch template, PR toggles, linked issue closure, and branch deletion define the workflow.",
    recommended: "Use Remote mode for PR/CI automation and Local mode for repositories where Code UX must not touch remotes.",
    risks: "Wrong default branches or aggressive cleanup can disrupt expected repository flow.",
    relatedDocs: ["Operations Runbook", "Instruction Template System"],
  },
  "merge-gates-autofix": {
    id: "merge-gates-autofix",
    title: "Merge Gates & Autofix",
    titleAliases: ["Merge Gates & Autofix (Unavailable in Local Mode)"],
    docsHref: settingsDocsPath("merge-gates-autofix"),
    summary: "Configures review, conflict, CI, and auto-merge gates for feature and main-branch merges.",
    controls: "Comment resolution, conflict repair, CI repair, feature PR auto-merge, and main PR auto-merge shape merge readiness.",
    recommended: "Require green checks and resolved comments for shared branches; use immediate auto-merge only in low-risk repositories.",
    risks: "Relaxed merge gates can land incomplete work; Local mode disables remote PR gates by design.",
    relatedDocs: ["Operations Runbook", "Security Hardening"],
  },
  "quality-assurance": {
    id: "quality-assurance",
    title: "Quality Assurance",
    docsHref: settingsDocsPath("quality-assurance"),
    summary: "Controls completion-time QA review, QA routing, and trigger-specific agent assignment.",
    controls: "QA toggles, route choices, and trigger selectors decide when and how final reviews run.",
    recommended: "Keep QA enabled for multi-task sprints and route it to a provider with strong review behavior.",
    risks: "Disabling QA removes an important last check before merge automation continues.",
    relatedDocs: ["Quality Assurance Agent", "Provider Routing"],
  },
  guardrails: {
    id: "guardrails",
    title: "Guardrails",
    docsHref: settingsDocsPath("guardrails"),
    summary: "Caps repeated agent jobs so runaway planning, coding, CI, merge, clarification, or remediation loops stop predictably.",
    controls: "Per-job caps and on-limit actions determine whether Code UX blocks, waits, warns, or continues.",
    recommended: "Keep guardrails enabled and use block-and-escalate for expensive or destructive job types.",
    risks: "Very high caps can burn provider quota; very low caps can stop recoverable work too early.",
    relatedDocs: ["Quality Guardrails", "Operations Runbook"],
  },
  "rate-limit": {
    id: "rate-limit",
    title: "Rate Limit",
    docsHref: settingsDocsPath("rate-limit"),
    summary: "Controls retries after provider quota or rate-limit responses.",
    controls: "Quota reset waits, fixed retry delays, retry counts, and no-timer quota retry caps define retry behavior.",
    recommended: "Retry on concrete quota reset timers and keep fixed retries modest.",
    risks: "Aggressive retries can keep failing tasks occupied and delay operator escalation.",
    relatedDocs: ["Operations Runbook", "Provider Routing"],
  },
  "watch-loop": {
    id: "watch-loop",
    title: "Watch Loop",
    docsHref: settingsDocsPath("watch-loop"),
    summary: "Controls whether live sprint orchestration keeps polling and how frequently it emits work.",
    controls: "The watch-loop toggle, evaluation interval, and output interval drive recurring orchestration checks.",
    recommended: "Keep the loop enabled with moderate intervals for active sprints.",
    risks: "Very short intervals can add noise; disabling the loop means progress depends on manual or external triggers.",
    relatedDocs: ["Atomic Sprint Loop", "Operations Runbook"],
  },
  "workspace-hygiene": {
    id: "workspace-hygiene",
    title: "Workspace Hygiene",
    docsHref: settingsDocsPath("workspace-hygiene"),
    summary: "Controls cleanup of temporary worktree state after provider CLI runs.",
    controls: "Success and failure cleanup toggles decide whether Code UX removes temporary execution workspace state.",
    recommended: "Clean successful worktrees and keep failed worktrees only when you are actively debugging.",
    risks: "Keeping failed worktrees can consume disk; removing them can erase useful repro artifacts.",
    relatedDocs: ["Operations Runbook", "Security Hardening"],
  },
  "workspace-visibility": {
    id: "workspace-visibility",
    title: "Workspace Visibility",
    docsHref: settingsDocsPath("workspace-visibility"),
    summary: "Controls automatic preview lifecycle and whether browser workspace entry points appear in the dashboard.",
    controls: "Preview enablement, in-app browser visibility, auto-start, rebuild triggers, and auto-stop define the preview lifecycle.",
    recommended: "Enable previews for UI projects and stop terminal previews automatically to conserve local resources.",
    risks: "Automatic rebuilds can be noisy for slow projects or heavy Docker images.",
    relatedDocs: ["Browser Preview", "Sprint Preview Browser"],
  },
  "runtime-limits": {
    id: "runtime-limits",
    title: "Runtime Limits",
    docsHref: settingsDocsPath("runtime-limits"),
    summary: "Sets preview container concurrency, ports, startup commands, and optional Docker access.",
    controls: "Container cap, host port start/end, internal app port, and startup override path decide how previews launch.",
    recommended: "Keep preview ports on localhost-only ranges and set the app port to the project dev server port.",
    risks: "Port collisions or wrong startup scripts prevent previews from becoming reachable.",
    relatedDocs: ["Browser Preview", "Security Hardening"],
  },
  techstacks: {
    id: "techstacks",
    title: "Techstacks",
    titleAliases: ["Techstacks Catalog", "Project Techstack"],
    docsHref: settingsDocsPath("techstacks"),
    summary: "Manages the system techstack catalog and per-project techstack/application-kind assignment.",
    controls: "System scope owns stack entries, default-stack selection, and technology items; project scope chooses a stack, clears to Unassigned, and selects web or desktop app kind.",
    recommended: "Keep imported projects unassigned until setup or an operator identifies the stack; use the built-in Code UX stack only for Code UX-style Preact dashboards.",
    risks: "Deleting custom stacks clears references to them, while the built-in Code UX Stack is protected and restored by settings normalization.",
    relatedDocs: ["Configuration and Storage", "Settings Reference"],
  },
  guidance: {
    id: "guidance",
    title: "Guidance",
    titleAliases: ["Tech Stack", "Styleguide", "Custom styleguides", "Custom tech stack guidance"],
    docsHref: settingsDocsPath("guidance"),
    summary: "Manages selected tech-stack and styleguide guidance plus custom instruction entries for the active settings scope.",
    controls: "Each section has a selector with None support, custom entry add/edit/delete controls, and styleguide visibility controls for hiding built-in defaults from the UI.",
    recommended: "Use None until a scope needs explicit design guidance; keep custom ids stable once projects or sprints reference them.",
    risks: "Built-in guidance is protected. Deleting a selected custom entry clears that selection back to None for the edited scope.",
    relatedDocs: ["Configuration and Storage", "Settings Reference"],
  },
  "project-markdown-mirror": {
    id: "project-markdown-mirror",
    title: "Project Markdown Mirror",
    docsHref: settingsDocsPath("project-markdown-mirror"),
    summary: "Controls whether dashboard-authored agent presets are mirrored into project-local markdown files.",
    controls: "The mirror toggle writes companion files under `.code-ux/agents` for selected project agents.",
    recommended: "Enable it when agent instructions should be reviewable with project changes.",
    risks: "Mirrored files can make agent edits visible in repository diffs if `.code-ux/agents` is tracked.",
    relatedDocs: ["Agent Sync And Planning Agent", "Agent Routing"],
  },
  "agent-routing": {
    id: "agent-routing",
    title: "Agent Routing",
    docsHref: settingsDocsPath("agent-routing"),
    summary: "Assigns built-in or project agent presets to planning, coding, CI, merge, dashboard, and clarification work.",
    controls: "Coding can be manual or orchestrator-selected; each route can use a project preset or built-in fallback.",
    recommended: "Use built-ins first, then assign specialists where project-specific instructions materially improve outcomes.",
    risks: "Missing or overly narrow project agents can reduce task quality or block routing choices.",
    relatedDocs: ["Agent Routing", "Agent Knowledge Base"],
  },
  "memory-system": {
    id: "memory-system",
    title: "Memory System",
    docsHref: settingsDocsPath("memory-system"),
    summary: "Controls capture, promotion, and remediation of sprint and project memory.",
    controls: "Enablement, sprint capture, agent capture, auto-promotion, and remediation mode decide what knowledge is stored and curated.",
    recommended: "Enable memory with deterministic remediation unless you need AI-assisted cleanup.",
    risks: "Disabling memory reduces long-term learning; AI remediation consumes routed provider capacity.",
    relatedDocs: ["Memory Architecture and Search", "Memory Claims and Evidence"],
  },
  "long-term-remediation-schedule": {
    id: "long-term-remediation-schedule",
    title: "Long-Term Remediation Schedule",
    docsHref: settingsDocsPath("long-term-remediation-schedule"),
    summary: "Schedules recurring project memory cleanup and claim maintenance.",
    controls: "Cadence, remediation mode, and local run time create or pause a project-specific scheduler entry.",
    recommended: "Use weekly deterministic cleanup for active projects with steady sprint volume.",
    risks: "AI cleanup schedules can surprise provider budgets if routed to expensive models.",
    relatedDocs: ["Scheduler", "Memory Architecture and Search"],
  },
  limits: {
    id: "limits",
    title: "Limits",
    docsHref: settingsDocsPath("limits"),
    summary: "Caps memory promotion thresholds, retained memories, graph density, and remediation promotions.",
    controls: "Thresholds and maximum counts bound sprint/project memory volume and neural-map edge density.",
    recommended: "Keep defaults until memory search becomes noisy or storage grows too quickly.",
    risks: "Low limits can evict useful knowledge; high graph density can make maps harder to inspect.",
    relatedDocs: ["Memory Architecture and Search", "Memory Claims and Evidence"],
  },
  "embedding-provider": {
    id: "embedding-provider",
    title: "Embedding Provider",
    docsHref: settingsDocsPath("embedding-provider"),
    summary: "Chooses in-app embeddings or an external OpenAI-compatible embeddings API.",
    controls: "Backend, external URL, model id, and API key control semantic memory embedding.",
    recommended: "Use in-app models for local-first operation; use external APIs only when you need a managed embedding model.",
    risks: "External APIs send memory text to the configured endpoint and require careful key handling.",
    relatedDocs: ["Memory Architecture and Search", "Security Hardening"],
  },
  "worker-learnings-instruction": {
    id: "worker-learnings-instruction",
    title: "Worker Learnings Instruction",
    docsHref: settingsDocsPath("worker-learnings-instruction"),
    summary: "Defines the prompt appended to worker tasks so useful lessons are captured for memory processing.",
    controls: "The text area controls exactly what workers are asked to observe and write into the temporary learnings file.",
    recommended: "Keep instructions specific to reusable engineering lessons and avoid asking workers to record secrets.",
    risks: "Overbroad instructions can capture noisy or sensitive details.",
    relatedDocs: ["Memory Architecture and Search", "Instruction Template System"],
  },
  integrations: {
    id: "integrations",
    title: "Integrations",
    docsHref: settingsDocsPath("integrations"),
    summary: "Lists provider, git-host, issue-tracker, storage mount, and read-only importer integrations and exposes manage/add actions.",
    controls: "Cards show connection state, auth hints, active/configured status, and management entry points. Google Drive controls link a host directory, enable its Docker-only mount, and choose read-only or read-write access.",
    recommended: "Keep Google Drive read-only unless containerized agents must modify synced files. Configure shared provider and storage defaults at system scope, then use project overrides only where needed.",
    risks: "Read-write mounts let containerized agents change or delete synced Drive files. Imported hints can reveal local auth paths, and broad importer tokens can expose external workspaces to search.",
    relatedDocs: ["Configuration and Storage", "Security Hardening"],
  },
  "jules-automation": {
    id: "jules-automation",
    title: "Jules Automation",
    docsHref: settingsDocsPath("jules-automation"),
    summary: "Configures Jules clarification automation and CI autofix handoff behavior.",
    controls: "Clarification auto-answer, answer mode/template, Jules CI autofix, and retry cap decide when hosted Jules automation runs.",
    recommended: "Use template answers for routine clarifications and keep retry caps low.",
    risks: "Automatic clarification replies can answer with stale assumptions if the template is too broad.",
    relatedDocs: ["Operations Runbook", "Provider Routing"],
  },
  "git-host-configuration": {
    id: "git-host-configuration",
    title: "Git Host Configuration",
    titleAliases: ["GitHub Configuration", "GitLab Configuration"],
    docsHref: settingsDocsPath("git-host-configuration"),
    summary: "Stores GitHub or GitLab tokens and Docker git-auth behavior for repository automation.",
    controls: "Tokens, GitHub auth mounting, auth paths, local git config copy, and container git identity control remote repository access.",
    recommended: "Prefer least-privilege tokens and use local auth copy only on trusted machines.",
    risks: "Tokens and copied auth directories can grant repository write access inside provider containers.",
    relatedDocs: ["Security Hardening", "Operations Runbook"],
  },
  "jira-configuration": {
    id: "jira-configuration",
    title: "Jira Configuration",
    docsHref: settingsDocsPath("jira-configuration"),
    summary: "Connects Jira issue search, import transitions, and completion transitions.",
    controls: "Site URL, account email, API token, project key, transition names, and move/close toggles drive Jira automation.",
    recommended: "Use a dedicated API token and test transition names against the target Jira workflow.",
    risks: "Wrong transition names prevent issue movement; broad tokens expose more Jira scope than needed.",
    relatedDocs: ["Sprint Imports", "Security Hardening"],
  },
  "importer-configuration": {
    id: "importer-configuration",
    title: "Importer Configuration",
    titleAliases: ["Notion Configuration", "Asana Configuration", "Linear Configuration", "Miro Configuration", "Lucid Configuration", "Figma / FigJam Configuration", "Mural Configuration"],
    docsHref: settingsDocsPath("importer-configuration"),
    summary: "Configures read-only external work imports for project management, whiteboard, diagram, and design providers.",
    controls: "Enablement, API token, optional secret, base URL, default IDs, and search limit decide when each importer is active.",
    recommended: "Store shared credentials at system scope, then add project overrides only when one project needs different defaults.",
    risks: "Broad tokens can expose external workspaces to import searches; use read-only or least-privilege credentials where providers support them.",
    relatedDocs: ["Sprint Imports", "Security Hardening"],
  },
  "provider-integration": {
    id: "provider-integration",
    title: "Provider Integration",
    titleAliases: ["Jules Integration", "Gemini Integration", "Codex Integration", "Claude Code Integration", "Qwen Code Integration", "OpenCode Integration", "Antigravity Integration"],
    docsHref: settingsDocsPath("provider-integration"),
    summary: "Explains that provider credentials are system-owned while project scopes still control routing and auth-copy behavior.",
    controls: "The notices clarify where provider instances live and which settings remain project-scoped.",
    recommended: "Switch to system scope to add credentials, then route them from AI Models.",
    risks: "Expecting project scope to create credentials can leave routes without provider instances.",
    relatedDocs: ["Provider Routing", "Configuration and Storage"],
  },
  "provider-credentials": {
    id: "provider-credentials",
    title: "Provider Credentials",
    titleAliases: ["Jules Credentials", "Gemini Credentials", "Codex Credentials", "Claude Code Credentials", "Qwen Code Credentials", "OpenCode Credentials", "Antigravity Credentials"],
    docsHref: settingsDocsPath("provider-credentials"),
    summary: "Manages named provider instances, authentication mode, local auth copy, dashboard login, provider config files, and base model defaults.",
    controls: "Each instance owns API key/auth path/login/config-file mode plus routing-visible identity and availability.",
    recommended: "Use named instances per account or quota pool; use Provider Config File only when a CLI needs a specific config copied.",
    risks: "Local auth copy and config-file mounts expose host credentials to Docker-backed provider runs.",
    relatedDocs: ["Provider Routing", "Qwen Code Integration", "OpenCode Integration", "Security Hardening"],
  },
  "mcp-servers": {
    id: "mcp-servers",
    title: "MCP Servers",
    docsHref: settingsDocsPath("mcp-servers"),
    summary: "Lists built-in and custom MCP servers injected into provider CLI runtimes.",
    controls: "The list configures built-in tool access, custom server enablement, transport, provider restrictions, and server creation.",
    recommended: "Keep built-in tools enabled and restrict custom servers to the CLIs that need them.",
    risks: "Broad custom MCP access can expose external tools to more providers than intended.",
    relatedDocs: ["MCP Tools and Contracts", "MCP Runtime and Dispatch"],
  },
  "built-in-mcp": {
    id: "built-in-mcp",
    title: "Built-in MCP (Code UX)",
    docsHref: settingsDocsPath("built-in-mcp"),
    summary: "Controls which built-in Code UX MCP tool categories are available to containerized CLIs.",
    controls: "Tool-category and individual-tool toggles decide what providers may call on their next run.",
    recommended: "Disable only categories you know a provider should not access.",
    risks: "Disabling required tools can make provider workflows fail; enabling broad tools increases capability exposure.",
    relatedDocs: ["MCP Tools and Contracts", "Security Hardening"],
  },
  "mcp-tool-category": {
    id: "mcp-tool-category",
    title: "MCP Tool Category",
    docsHref: settingsDocsPath("mcp-tool-category"),
    summary: "Enables or disables one built-in MCP tool category and its individual tools.",
    controls: "The category toggle sets all tools in the group; each row can override a specific tool.",
    recommended: "Keep category-level changes coarse and document why any tool is disabled.",
    risks: "Fine-grained disablement can be hard to diagnose when a provider expects a missing tool.",
    relatedDocs: ["MCP Tools and Contracts", "MCP Runtime and Dispatch"],
  },
  "custom-mcp-server": {
    id: "custom-mcp-server",
    title: "Custom MCP Server",
    titleAliases: ["MCP server"],
    docsHref: settingsDocsPath("custom-mcp-server"),
    summary: "Configures one custom MCP server injected into compatible provider CLIs.",
    controls: "Display name, server key, transport, URL or command, args/env/headers, description, CLI restrictions, and preview define the server.",
    recommended: "Prefer HTTP/SSE for managed remote servers and restrict sensitive servers to specific CLIs.",
    risks: "Invalid JSON, unavailable commands, or leaked auth headers can break provider startup or expose secrets.",
    relatedDocs: ["External MCP Worker Client", "Security Hardening"],
  },
  "danger-zone": {
    id: "danger-zone",
    title: "Danger Zone",
    docsHref: settingsDocsPath("danger-zone"),
    summary: "Groups irreversible project deletion and project override reset actions.",
    controls: "Project reset clears saved overrides; project delete removes the project and associated local runtime data.",
    recommended: "Reset overrides before deleting a project when you only need to return to inherited defaults.",
    risks: "Delete actions are irreversible after confirmation.",
    relatedDocs: ["Operations Runbook", "Configuration and Storage"],
  },
  "project-memory": {
    id: "project-memory",
    title: "Project Memory",
    docsHref: settingsDocsPath("project-memory"),
    summary: "Clears selected memory tiers for the active project only.",
    controls: "Short-term, long-term, and all-memory actions remove progressively broader memory records.",
    recommended: "Clear short-term first when fixing noisy sprint memory; use all-memory only for a full project memory reset.",
    risks: "Clearing long-term or all memory removes claims, evidence, and vectors permanently.",
    relatedDocs: ["Memory Claims and Evidence", "Memory Architecture and Search"],
  },
  "system-memory": {
    id: "system-memory",
    title: "System Memory",
    docsHref: settingsDocsPath("system-memory"),
    summary: "Clears memory tiers across every project in the local database.",
    controls: "Short-term, long-term, and all-memory actions apply globally.",
    recommended: "Use only during local maintenance or after confirming no project needs the retained knowledge.",
    risks: "System memory clears are broad and irreversible.",
    relatedDocs: ["Memory Claims and Evidence", "Operations Runbook"],
  },
  "system-database": {
    id: "system-database",
    title: "System Database",
    docsHref: settingsDocsPath("system-database"),
    summary: "Wipes the local Code UX database so the app returns to a clean state on reload.",
    controls: "The hard reset action removes projects, sprints, tasks, histories, and system state.",
    recommended: "Use only for local reset or unrecoverable database corruption after exporting anything needed.",
    risks: "This deletes all local runtime state and cannot be undone from the dashboard.",
    relatedDocs: ["Configuration and Storage", "Operations Runbook"],
  },
} as const satisfies Record<string, SettingsSubcategoryDoc>;

export type SettingsSubcategoryId = keyof typeof SETTINGS_SUBCATEGORY_DOCS;

const normalizeTitle = (title: string): string => (
  title
    .replace(/\s+\([^)]*\)$/u, "")
    .trim()
    .toLowerCase()
);

const TITLE_TO_ID = new Map<string, SettingsSubcategoryId>(
  Object.entries(SETTINGS_SUBCATEGORY_DOCS).flatMap(([id, doc]) => {
    const entry = doc as SettingsSubcategoryDoc;
    return [entry.title, ...(entry.titleAliases ?? [])].map((title) => [normalizeTitle(title), id as SettingsSubcategoryId]);
  }),
);

const GERMAN_SUBCATEGORY_TITLES: Partial<Record<SettingsSubcategoryId, string>> = {
  "project-context": "Projektkontext",
  automation: "Automatisierung",
  "docker-runtime": "Docker-Laufzeit",
  "system-runtime": "Systemlaufzeit",
  "restart-behavior": "Neustartverhalten",
  "database-settings": "Datenbankeinstellungen",
  onboarding: "Einrichtung",
  "display-settings": "Anzeigeeinstellungen",
  background: "Hintergrund",
  "default-routing-anchors": "Standard-Routing-Anker",
  "base-provider-configuration": "Anbieter-Grundkonfiguration",
  "route-mapping": "Routenzuordnung",
  "model-pricing": "Modellpreise",
  "git-flow": "Git-Ablauf",
  "merge-gates-autofix": "Merge-Prüfungen & automatische Reparatur",
  "quality-assurance": "Qualitätssicherung",
  guardrails: "Leitplanken",
  "rate-limit": "Ratenbegrenzung",
  "watch-loop": "Überwachungsschleife",
  "workspace-hygiene": "Arbeitsbereichsbereinigung",
  "workspace-visibility": "Sichtbarkeit des Arbeitsbereichs",
  "runtime-limits": "Laufzeitgrenzen",
  techstacks: "Technologie-Stacks",
  guidance: "Vorgaben",
  "project-markdown-mirror": "Projekt-Markdown-Spiegelung",
  "agent-routing": "Agenten-Routing",
  "memory-system": "Speichersystem",
  "long-term-remediation-schedule": "Zeitplan für langfristige Bereinigung",
  limits: "Grenzwerte",
  "embedding-provider": "Einbettungsanbieter",
  "worker-learnings-instruction": "Anweisung für Worker-Lernerfahrungen",
  integrations: "Integrationen",
  "jules-automation": "Jules-Automatisierung",
  "git-host-configuration": "Git-Host-Konfiguration",
  "jira-configuration": "Jira-Konfiguration",
  "importer-configuration": "Importer-Konfiguration",
  "provider-integration": "Anbieterintegration",
  "provider-credentials": "Anbieterzugangsdaten",
  "mcp-servers": "MCP-Server",
  "built-in-mcp": "Integriertes MCP",
  "mcp-tool-category": "MCP-Werkzeugkategorie",
  "custom-mcp-server": "Benutzerdefinierter MCP-Server",
  "danger-zone": "Gefahrenbereich",
  "project-memory": "Projektspeicher",
  "system-memory": "Systemspeicher",
  "system-database": "Systemdatenbank",
};

type SettingsSubcategoryHelpCopy = Pick<SettingsSubcategoryDoc, "summary" | "controls" | "recommended" | "risks">;

const GERMAN_SUBCATEGORY_HELP = {
  "project-context": {
    summary: "Benennt und kennzeichnet das aktive Projekt, ohne die gespeicherte Projekt-ID oder den Ausführungsverlauf zu ändern.",
    controls: "Der Projektname ist bearbeitbar; Projekt-ID, Quelltyp und Basisverzeichnis zeigen, wie Code UX den Arbeitsbereich adressiert und öffnet.",
    recommended: "Verwende einen eindeutigen Projektnamen und richte das Basisverzeichnis am Repository-Stamm aus, den Worker verwenden sollen.",
    risks: "Eine Umbenennung ist rein optisch; ein unerwartetes Basisverzeichnis deutet meist darauf hin, dass das Projekt aus dem falschen Pfad erstellt wurde.",
  },
  automation: {
    summary: "Steuert, wie weit Code UX ohne Unterbrechung für Entscheidungen der Bedienperson fortfahren darf.",
    controls: "Die Automatisierungsstufe legt die allgemeine Freigabestrategie fest; automatische Planfreigabe und Fortsetzung pausierter Läufe behandeln routinemäßige Fortsetzungspunkte.",
    recommended: "Verwende Halbautomatisch für normale Arbeit, Vollautomatisch nur für vertrauenswürdige Projekte und Immer fragen für sensible Repositories.",
    risks: "Mehr Automatisierung kann schneller sein, aber auch mit einem fehlerhaften Plan oder veraltetem Kontext fortfahren, bevor du eingreifst.",
  },
  "docker-runtime": {
    summary: "Definiert die Standard-Containerumgebung für Docker-basierte Anbieter-CLIs.",
    controls: "Image, Einrichtungsskript, Speichergrenze, Zwischenspeicherung des Setup-Images und die Playwright-Browserinstallation gestalten jeden Worker-Container.",
    recommended: "Behalte das Standard-Image bei, sofern dein Repository keine eigene Toolchain benötigt; aktiviere vorinstallierte Playwright-Browser für browserintensive QA.",
    risks: "Fehlerhafte Einrichtungsskripte oder zu knappe Speichergrenzen können jeden Anbieteraufruf im Bereich scheitern lassen.",
  },
  "system-runtime": {
    summary: "Konfiguriert Dashboard-Port und Laufzeitprotokollierung des lokalen Code-UX-Prozesses.",
    controls: "Der Dashboard-Port steuert den HTTP-Listener; Konsolen- und Debugdatei-Stufen bestimmen die Protokollausführlichkeit.",
    recommended: "Behalte Port 4444 sowie Info-/Fehlerprotokollierung im Alltag bei und erhöhe die Ausführlichkeit nur zur Fehlersuche.",
    risks: "Nach einer Portänderung müssen Clients neu verbunden werden; Debugprotokollierung kann große lokale Dateien erzeugen.",
  },
  "restart-behavior": {
    summary: "Legt fest, wie aktive Sprints und unterbrochene Anbieteraufrufe nach einem App-Neustart abgeglichen werden.",
    controls: "Die Sprint-Richtlinie setzt aktive Sprints fort, pausiert oder bricht sie ab; die Aufrufrichtlinie setzt unterbrochene Arbeit fort, bricht sie ab oder startet sie neu.",
    recommended: "Setze Sprints und Aufrufe bei lokaler Entwicklung fort; pausiere sie, wenn nach einer Unterbrechung eine manuelle Prüfung erfolgen soll.",
    risks: "Ein Neustart unterbrochener Arbeit kann Anbieteraufwand duplizieren, falls der vorherige CLI-Lauf extern noch aktiv war.",
  },
  "database-settings": {
    summary: "Verwaltet Aufbewahrung und Wartung lokaler SQLite-Laufzeitaktivitäten.",
    controls: "Bereinigung entfernt alte abgeschlossene Aktivitäten, die Aufbewahrung bestimmt das Zeitfenster und Vacuum komprimiert den Speicher beim Start.",
    recommended: "Lasse Bereinigung und Vacuum aktiviert, sofern du keinen lokalen forensischen Verlauf aufbewahren musst.",
    risks: "Kurze Aufbewahrung kann nützliche Diagnosedetails entfernen; ohne Bereinigung kann die lokale Datenbank schnell wachsen.",
  },
  onboarding: {
    summary: "Öffnet die geführte Einrichtung erneut, ohne allein dadurch gespeicherte Einstellungen zu ändern.",
    controls: "Die Aktionsschaltfläche startet die Einrichtung, damit Anbieter-, Projekt- und Einrichtungsfragen erneut bearbeitet werden können.",
    recommended: "Nutze sie beim Einrichten eines neuen Rechners oder nach dem Hinzufügen von Anbieterzugangsdaten.",
    risks: "Das Speichern neuer Einrichtungsoptionen kann die aktuellen Systemvorgaben überschreiben.",
  },
  "display-settings": {
    summary: "Steuert Layout, Design, Akzentfarbe, Bewegung, Sprache und – sofern verfügbar – den Desktop-Zoom der Dashboard-Oberfläche.",
    controls: "Navigationsmodus, Farbschema, Akzent, Bewegungsreduktion, Sprache und Zoom verändern ausschließlich die Darstellung des Dashboards.",
    recommended: "Verwende das Systemdesign und automatische Bewegungsreduktion, sofern du keine feste barrierefreie Einstellung benötigst.",
    risks: "Ein hoher Zoom oder eine dichte Seitenleiste kann auf kleinen Bildschirmen den sichtbaren Arbeitsbereich verkleinern.",
  },
  background: {
    summary: "Passt Hintergrundbild, Animationsmodus, statische Farbe und Musterüberlagerung des Dashboards an.",
    controls: "Bildupload, animierter oder statischer Modus, Animationsstil, Farbauswahl und Muster gestalten die visuelle Ebene hinter den Bereichen.",
    recommended: "Bevorzuge kleine Bilder mit gutem Kontrast und verwende den statischen Modus, wenn Bewegung ablenkt.",
    risks: "Große Bilder und unruhige Muster können die Leistung oder Lesbarkeit beeinträchtigen.",
  },
  "default-routing-anchors": {
    summary: "Legt die globalen und Worker-Anbieterinstanzen fest, die Aufrufrouten beim Erben von Vorgaben verwenden.",
    controls: "Globale und Worker-Vorgaben wählen benannte Anbieterinstanzen und Basismodelle; Parallelität und Zeitlimit begrenzen die Worker-Zuweisung.",
    recommended: "Wähle für beide Anker stabile, authentifizierte Instanzen, bevor du Routenüberschreibungen verfeinerst.",
    risks: "Nicht konfigurierte Anker lassen geerbte Routen ohne nutzbaren Anbieter zurück.",
  },
  "base-provider-configuration": {
    summary: "Definiert für jede benannte Anbieterinstanz standardmäßige Eignung, Modell, Denktiefe, Gewichtung und Parallelität.",
    controls: "Anbieterkarten bestimmen Standard-Routenteilnahme, Modell, Denkmodus, Routing-Gewicht und maximale parallele Aufgaben.",
    recommended: "Lasse nur funktionsfähige Instanzen zu und drücke Präferenzen durch Gewichtungen aus, statt jede Route fest zu binden.",
    risks: "Inkompatible Modelle oder hohe Parallelität können wiederholte Anbieterfehler oder Kontingentdruck verursachen.",
  },
  "route-mapping": {
    summary: "Leitet jeden Aufruftyp an geerbte, manuelle, gewichtete oder vom Agenten ausgewählte Anbieterpools weiter.",
    controls: "Jede Route wählt Profil, Strategie, primäre Instanz, zulässigen gewichteten Pool und anbieterspezifische Überschreibungen.",
    recommended: "Nutze zuerst geerbte Vorgaben und überschreibe danach risikoreiche Routen wie Planung, QA, CI-Reparatur und Bereinigung.",
    risks: "Gewichtete Pools mit nicht verfügbaren Anbietern können Fehler auf mehrere Aufgabentypen verteilen.",
  },
  "model-pricing": {
    summary: "Speichert Token-Preisdaten für Modellkostenschätzungen in Dashboard-Ansichten.",
    controls: "Preiszeilen definieren Eingabe- und Ausgabe-Tokenkosten pro Modell, sofern das Dashboard die Nutzung schätzen kann.",
    recommended: "Halte Preise aktiv gerouteter Anbieter aktuell und lasse unbekannte Modelle ohne Wert.",
    risks: "Veraltete Preise beeinflussen nur Schätzungen und ändern nicht die Abrechnung des Anbieters.",
  },
  "git-flow": {
    summary: "Steuert Branch-Benennung, PR-Erstellung, Ticketabschluss und Bereinigung für Sprint-Arbeit.",
    controls: "Git-Modus, Standard-Branch, Präfixe, Sprint-Schlüssel, Branch-Vorlage, PR-Schalter, Ticketabschluss und Branch-Löschung definieren den Ablauf.",
    recommended: "Nutze den Remote-Modus für PR-/CI-Automatisierung und den lokalen Modus, wenn Code UX keine Remotes verändern darf.",
    risks: "Falsche Standard-Branches oder aggressive Bereinigung können den erwarteten Repository-Ablauf stören.",
  },
  "merge-gates-autofix": {
    summary: "Konfiguriert Review-, Konflikt-, CI- und Auto-Merge-Prüfungen für Feature- und Haupt-Branch-Merges.",
    controls: "Kommentarauflösung, Konflikt- und CI-Reparatur sowie automatische Feature- und Haupt-PR-Merges bestimmen die Merge-Bereitschaft.",
    recommended: "Verlange erfolgreiche Prüfungen und gelöste Kommentare für gemeinsame Branches; nutze sofortiges Auto-Merge nur in risikoarmen Repositories.",
    risks: "Gelockerte Merge-Prüfungen können unvollständige Arbeit übernehmen; der lokale Modus deaktiviert Remote-PR-Prüfungen bewusst.",
  },
  "quality-assurance": {
    summary: "Steuert die QA-Abschlussprüfung, das QA-Routing und die auslöserspezifische Agentenzuweisung.",
    controls: "QA-Schalter, Routenauswahl und Auslöser bestimmen, wann und wie Abschlussprüfungen ausgeführt werden.",
    recommended: "Lasse QA für Sprints mit mehreren Aufgaben aktiviert und leite sie an einen Anbieter mit starkem Review-Verhalten weiter.",
    risks: "Ohne QA entfällt eine wichtige letzte Prüfung, bevor die Merge-Automatisierung fortfährt.",
  },
  guardrails: {
    summary: "Begrenzt wiederholte Agentenjobs, damit außer Kontrolle geratene Planungs-, Coding-, CI-, Merge-, Klärungs- oder Bereinigungsschleifen vorhersehbar stoppen.",
    controls: "Grenzen pro Job und Aktionen beim Erreichen bestimmen, ob Code UX blockiert, wartet, warnt oder fortfährt.",
    recommended: "Lasse Leitplanken aktiviert und verwende Blockieren und eskalieren für teure oder destruktive Jobtypen.",
    risks: "Sehr hohe Grenzen können Anbieterkontingent verbrauchen; sehr niedrige Grenzen können behebbares Arbeiten zu früh stoppen.",
  },
  "rate-limit": {
    summary: "Steuert Wiederholungen nach Kontingent- oder Ratenbegrenzungsantworten eines Anbieters.",
    controls: "Wartezeiten bis zur Kontingentrücksetzung, feste Verzögerungen, Wiederholungszahlen und Grenzen ohne Zeitangabe definieren das Wiederholungsverhalten.",
    recommended: "Wiederhole bei konkreten Rücksetzungszeitpunkten und halte feste Wiederholungszahlen niedrig.",
    risks: "Aggressive Wiederholungen können fehlschlagende Aufgaben belegen und die Eskalation verzögern.",
  },
  "watch-loop": {
    summary: "Steuert, ob die aktive Sprint-Orchestrierung weiter prüft und wie häufig sie Arbeit ausgibt.",
    controls: "Schalter, Auswertungsintervall und Ausgabeintervall der Überwachungsschleife treiben wiederkehrende Orchestrierungsprüfungen an.",
    recommended: "Lasse die Schleife für aktive Sprints mit moderaten Intervallen aktiviert.",
    risks: "Sehr kurze Intervalle können Rauschen erzeugen; ohne Schleife hängt der Fortschritt von manuellen oder externen Auslösern ab.",
  },
  "workspace-hygiene": {
    summary: "Steuert die Bereinigung temporärer Worktree-Zustände nach Anbieter-CLI-Läufen.",
    controls: "Bereinigungsschalter für Erfolg und Fehler bestimmen, ob Code UX temporäre Ausführungszustände entfernt.",
    recommended: "Bereinige erfolgreiche Worktrees und behalte fehlgeschlagene nur während aktiver Fehlersuche.",
    risks: "Behaltene Worktrees verbrauchen Speicherplatz; entfernte Worktrees können nützliche Reproduktionsartefakte löschen.",
  },
  "workspace-visibility": {
    summary: "Steuert den automatischen Vorschaulebenszyklus und ob Browser-Einstiege in den Arbeitsbereich im Dashboard erscheinen.",
    controls: "Vorschauaktivierung, Sichtbarkeit im App-Browser, automatischer Start, Neuaufbau-Auslöser und automatisches Stoppen definieren den Lebenszyklus.",
    recommended: "Aktiviere Vorschauen für UI-Projekte und stoppe Terminalvorschauen automatisch, um lokale Ressourcen zu sparen.",
    risks: "Automatische Neuaufbauten können bei langsamen Projekten oder großen Docker-Images störend sein.",
  },
  "runtime-limits": {
    summary: "Legt Parallelität, Ports, Startbefehle und optionalen Docker-Zugriff für Vorschaucontainer fest.",
    controls: "Containergrenze, Host-Portbereich, interner App-Port und Pfad zur Startüberschreibung bestimmen den Vorschau-Start.",
    recommended: "Beschränke Vorschauports auf lokale Bereiche und setze den App-Port auf den Port des Projektentwicklungsservers.",
    risks: "Portkonflikte oder falsche Startskripte verhindern erreichbare Vorschauen.",
  },
  techstacks: {
    summary: "Verwaltet den systemweiten Technologie-Stack-Katalog sowie die Stack- und Anwendungstypzuweisung pro Projekt.",
    controls: "Der Systembereich verwaltet Einträge, Standardauswahl und Technologien; der Projektbereich wählt einen Stack, setzt auf Nicht zugewiesen zurück und bestimmt Web- oder Desktop-Typ.",
    recommended: "Lasse importierte Projekte bis zur Einrichtung oder eindeutigen Zuordnung unzugewiesen; nutze den integrierten Code-UX-Stack nur für entsprechende Preact-Dashboards.",
    risks: "Das Löschen eigener Stacks entfernt ihre Verweise; der integrierte Code-UX-Stack ist geschützt und wird durch Normalisierung wiederhergestellt.",
  },
  guidance: {
    summary: "Verwaltet ausgewählte Technologie- und Styleguide-Vorgaben sowie eigene Anweisungseinträge für den aktiven Einstellungsbereich.",
    controls: "Jeder Abschnitt bietet eine Auswahl mit Ohne-Option, Aktionen zum Hinzufügen, Bearbeiten und Löschen sowie Sichtbarkeitsschalter für integrierte Styleguides.",
    recommended: "Verwende Ohne, bis ein Bereich ausdrückliche Designvorgaben benötigt, und halte eigene IDs stabil, sobald Projekte oder Sprints darauf verweisen.",
    risks: "Integrierte Vorgaben sind geschützt. Das Löschen eines ausgewählten eigenen Eintrags setzt die Auswahl im bearbeiteten Bereich auf Ohne zurück.",
  },
  "project-markdown-mirror": {
    summary: "Steuert, ob im Dashboard erstellte Agentenvorlagen in projektlokale Markdown-Dateien gespiegelt werden.",
    controls: "Der Spiegelungsschalter schreibt Begleitdateien für ausgewählte Projektagenten unter `.code-ux/agents`.",
    recommended: "Aktiviere ihn, wenn Agentenanweisungen gemeinsam mit Projektänderungen geprüft werden sollen.",
    risks: "Gespiegelte Dateien können in Repository-Diffs erscheinen, wenn `.code-ux/agents` versioniert wird.",
  },
  "agent-routing": {
    summary: "Weist integrierte oder projektbezogene Agentenvorlagen der Planung, Entwicklung, CI, Konfliktlösung, Dashboard-Antwort und Klärung zu.",
    controls: "Coding kann manuell oder durch den Orchestrator gewählt werden; jede Route kann eine Projektvorlage oder den integrierten Fallback nutzen.",
    recommended: "Beginne mit integrierten Agenten und weise Spezialisten zu, wenn projektspezifische Anweisungen die Ergebnisse wesentlich verbessern.",
    risks: "Fehlende oder zu eng gefasste Projektagenten können die Aufgabenqualität senken oder Routingoptionen blockieren.",
  },
  "memory-system": {
    summary: "Steuert Erfassung, Übernahme und Bereinigung von Sprint- und Projektspeicher.",
    controls: "Aktivierung, Sprint- und Agentenerfassung, automatische Übernahme und Bereinigungsmodus bestimmen, welches Wissen gespeichert und gepflegt wird.",
    recommended: "Aktiviere den Speicher mit deterministischer Bereinigung, sofern du keine KI-gestützte Pflege benötigst.",
    risks: "Deaktivierter Speicher verringert langfristiges Lernen; KI-Bereinigung beansprucht geroutete Anbieterkapazität.",
  },
  "long-term-remediation-schedule": {
    summary: "Plant wiederkehrende Bereinigung des Projektspeichers und Pflege von Wissensaussagen.",
    controls: "Takt, Bereinigungsmodus und lokale Ausführungszeit erstellen oder pausieren einen projektspezifischen Zeitplaneintrag.",
    recommended: "Nutze wöchentliche deterministische Bereinigung für aktive Projekte mit regelmäßigem Sprint-Aufkommen.",
    risks: "Zeitpläne mit KI-Bereinigung können Anbieterbudgets unerwartet belasten, wenn teure Modelle geroutet sind.",
  },
  limits: {
    summary: "Begrenzt Übernahmeschwellen, gespeicherte Erinnerungen, Graphdichte und Bereinigungsübernahmen.",
    controls: "Schwellenwerte und Höchstzahlen begrenzen Sprint-/Projektspeicher sowie die Kantendichte der neuronalen Karte.",
    recommended: "Behalte die Vorgaben bei, bis die Speichersuche unübersichtlich wird oder der Speicher zu schnell wächst.",
    risks: "Niedrige Grenzen können nützliches Wissen verdrängen; hohe Graphdichte kann Karten schwerer prüfbar machen.",
  },
  "embedding-provider": {
    summary: "Wählt integrierte Einbettungen oder eine externe OpenAI-kompatible Einbettungs-API.",
    controls: "Backend, externe URL, Modell-ID und API-Schlüssel steuern die semantische Einbettung des Speichers.",
    recommended: "Nutze integrierte Modelle für lokalen Betrieb und externe APIs nur, wenn ein verwaltetes Einbettungsmodell benötigt wird.",
    risks: "Externe APIs senden Speichertexte an den konfigurierten Endpunkt und erfordern sorgfältigen Umgang mit Schlüsseln.",
  },
  "worker-learnings-instruction": {
    summary: "Definiert den an Worker-Aufgaben angehängten Prompt, damit nützliche Erkenntnisse für die Speicherverarbeitung erfasst werden.",
    controls: "Das Textfeld bestimmt genau, welche Beobachtungen Worker in die temporäre Lerndatei schreiben sollen.",
    recommended: "Beschränke die Anweisung auf wiederverwendbare technische Erkenntnisse und fordere niemals die Aufzeichnung von Geheimnissen an.",
    risks: "Zu weit gefasste Anweisungen können irrelevante oder sensible Details erfassen.",
  },
  integrations: {
    summary: "Listet Anbieter-, Git-Host-, Ticket-, Speichereinbindungs- und schreibgeschützte Importer-Integrationen mit Verwaltungsaktionen auf.",
    controls: "Karten zeigen Verbindung, Authentifizierungshinweise und Aktiv-/Konfiguriert-Status. Google Drive verknüpft ein Host-Verzeichnis, aktiviert die reine Docker-Einbindung und wählt Lese- oder Schreibzugriff.",
    recommended: "Lasse Google Drive schreibgeschützt, sofern Container-Agenten keine synchronisierten Dateien ändern müssen. Konfiguriere gemeinsame Anbieter- und Speichervorgaben im Systembereich und überschreibe sie nur bei Bedarf pro Projekt.",
    risks: "Schreibzugriff erlaubt Container-Agenten, synchronisierte Drive-Dateien zu ändern oder zu löschen. Importhinweise können lokale Authentifizierungspfade offenlegen; weitreichende Tokens können externe Arbeitsbereiche für Suchen freigeben.",
  },
  "jules-automation": {
    summary: "Konfiguriert automatische Jules-Klärungen und die Übergabe an automatische CI-Reparatur.",
    controls: "Automatische Klärungsantwort, Antwortmodus und -vorlage, Jules-CI-Reparatur und Wiederholungsgrenze bestimmen, wann gehostete Jules-Automatisierung läuft.",
    recommended: "Nutze Vorlagen für routinemäßige Klärungen und halte Wiederholungsgrenzen niedrig.",
    risks: "Automatische Klärungsantworten können mit veralteten Annahmen reagieren, wenn die Vorlage zu allgemein ist.",
  },
  "git-host-configuration": {
    summary: "Speichert GitHub- oder GitLab-Tokens und das Docker-Verhalten für Git-Authentifizierung bei Repository-Automatisierung.",
    controls: "Tokens, Einbindung der GitHub-Authentifizierung, Authentifizierungspfade, Kopie der lokalen Git-Konfiguration und Containeridentität steuern den Remote-Zugriff.",
    recommended: "Bevorzuge Tokens mit minimalen Rechten und kopiere lokale Authentifizierung nur auf vertrauenswürdigen Rechnern.",
    risks: "Tokens und kopierte Authentifizierungsverzeichnisse können Anbietercontainern Schreibzugriff auf Repositories geben.",
  },
  "jira-configuration": {
    summary: "Verbindet Jira-Ticketsuche, Importübergänge und Abschlussübergänge.",
    controls: "Site-URL, Konto-E-Mail, API-Token, Projektschlüssel, Übergangsnamen sowie Verschieben-/Schließen-Schalter steuern die Jira-Automatisierung.",
    recommended: "Nutze ein eigenes API-Token und prüfe Übergangsnamen am Zielworkflow in Jira.",
    risks: "Falsche Übergangsnamen verhindern Ticketbewegungen; weitreichende Tokens geben mehr Jira-Bereiche als nötig frei.",
  },
  "importer-configuration": {
    summary: "Konfiguriert schreibgeschützte externe Arbeitsimporte aus Projektmanagement-, Whiteboard-, Diagramm- und Designanbietern.",
    controls: "Aktivierung, API-Token, optionales Geheimnis, Basis-URL, Standard-IDs und Suchgrenze bestimmen, wann ein Importer aktiv ist.",
    recommended: "Speichere gemeinsame Zugangsdaten im Systembereich und ergänze Projektüberschreibungen nur für abweichende Vorgaben.",
    risks: "Weitreichende Tokens können externe Arbeitsbereiche für Importsuchen freigeben; nutze schreibgeschützte oder minimal berechtigte Zugangsdaten, sofern unterstützt.",
  },
  "provider-integration": {
    summary: "Erklärt, dass Anbieterzugangsdaten dem System gehören, während Projektbereiche weiterhin Routing und das Kopieren von Authentifizierung steuern.",
    controls: "Die Hinweise erklären, wo Anbieterinstanzen verwaltet werden und welche Einstellungen projektbezogen bleiben.",
    recommended: "Wechsle zum Systembereich, um Zugangsdaten hinzuzufügen, und route sie anschließend unter KI-Modelle.",
    risks: "Werden Zugangsdaten fälschlich im Projektbereich erwartet, können Routen ohne Anbieterinstanz bleiben.",
  },
  "provider-credentials": {
    summary: "Verwaltet benannte Anbieterinstanzen, Authentifizierungsmodus, lokale Authentifizierungskopie, Dashboard-Anmeldung, Konfigurationsdateien und Basismodellvorgaben.",
    controls: "Jede Instanz besitzt API-Schlüssel, Authentifizierungspfad, Anmeldung oder Konfigurationsdateimodus sowie Routing-sichtbare Identität und Verfügbarkeit.",
    recommended: "Nutze benannte Instanzen pro Konto oder Kontingentpool; verwende Anbieter-Konfigurationsdateien nur, wenn eine CLI eine bestimmte kopierte Konfiguration benötigt.",
    risks: "Lokale Authentifizierungskopien und Konfigurationsdatei-Einbindungen geben Docker-basierten Anbieterläufen Zugriff auf Host-Zugangsdaten.",
  },
  "mcp-servers": {
    summary: "Listet integrierte und benutzerdefinierte MCP-Server auf, die in Anbieter-CLI-Laufzeiten eingebunden werden.",
    controls: "Die Liste konfiguriert integrierten Werkzeugzugriff, Aktivierung eigener Server, Transport, Anbieterbeschränkungen und Servererstellung.",
    recommended: "Lasse integrierte Werkzeuge aktiviert und beschränke eigene Server auf die CLIs, die sie benötigen.",
    risks: "Weitreichender Zugriff auf eigene MCP-Server kann externen Werkzeugzugriff für mehr Anbieter als beabsichtigt freigeben.",
  },
  "built-in-mcp": {
    summary: "Steuert, welche integrierten Code-UX-MCP-Werkzeugkategorien Container-CLIs verwenden dürfen.",
    controls: "Schalter für Werkzeugkategorien und einzelne Werkzeuge bestimmen, was Anbieter beim nächsten Lauf aufrufen dürfen.",
    recommended: "Deaktiviere nur Kategorien, auf die ein Anbieter nachweislich nicht zugreifen soll.",
    risks: "Fehlende benötigte Werkzeuge können Anbieterabläufe scheitern lassen; breite Freigaben erhöhen den Funktionszugriff.",
  },
  "mcp-tool-category": {
    summary: "Aktiviert oder deaktiviert eine integrierte MCP-Werkzeugkategorie und ihre einzelnen Werkzeuge.",
    controls: "Der Kategorieschalter setzt alle Werkzeuge der Gruppe; jede Zeile kann ein bestimmtes Werkzeug abweichend steuern.",
    recommended: "Halte Änderungen auf Kategorieebene grob und dokumentiere, warum einzelne Werkzeuge deaktiviert sind.",
    risks: "Feingranulare Deaktivierung kann schwer zu diagnostizieren sein, wenn ein Anbieter ein fehlendes Werkzeug erwartet.",
  },
  "custom-mcp-server": {
    summary: "Konfiguriert einen eigenen MCP-Server, der in kompatible Anbieter-CLIs eingebunden wird.",
    controls: "Anzeigename, Serverschlüssel, Transport, URL oder Befehl, Argumente, Umgebung, Header, Beschreibung, CLI-Beschränkungen und Vorschau definieren den Server.",
    recommended: "Bevorzuge HTTP/SSE für verwaltete Remote-Server und beschränke sensible Server auf bestimmte CLIs.",
    risks: "Ungültiges JSON, nicht verfügbare Befehle oder offengelegte Authentifizierungsheader können Anbieterstarts stören oder Geheimnisse preisgeben.",
  },
  "danger-zone": {
    summary: "Gruppiert die unumkehrbare Projektlöschung und das Zurücksetzen von Projektüberschreibungen.",
    controls: "Projekt zurücksetzen entfernt gespeicherte Überschreibungen; Projekt löschen entfernt das Projekt und zugehörige lokale Laufzeitdaten.",
    recommended: "Setze Überschreibungen zurück, bevor du ein Projekt löschst, wenn nur wieder Systemvorgaben geerbt werden sollen.",
    risks: "Löschaktionen können nach der Bestätigung nicht rückgängig gemacht werden.",
  },
  "project-memory": {
    summary: "Löscht ausgewählte Speicherstufen ausschließlich für das aktive Projekt.",
    controls: "Aktionen für Kurzzeit-, Langzeit- und gesamten Speicher entfernen zunehmend umfassendere Speicherdatensätze.",
    recommended: "Lösche bei störendem Sprint-Speicher zuerst den Kurzzeitspeicher und verwende Gesamter Speicher nur für eine vollständige Projektbereinigung.",
    risks: "Das Löschen von Langzeit- oder Gesamtspeicher entfernt Aussagen, Belege und Vektoren dauerhaft.",
  },
  "system-memory": {
    summary: "Löscht Speicherstufen über alle Projekte in der lokalen Datenbank hinweg.",
    controls: "Aktionen für Kurzzeit-, Langzeit- und gesamten Speicher gelten systemweit.",
    recommended: "Nutze sie nur für lokale Wartung oder nachdem bestätigt wurde, dass kein Projekt das gespeicherte Wissen benötigt.",
    risks: "Systemweite Speicherlöschungen sind umfassend und unumkehrbar.",
  },
  "system-database": {
    summary: "Löscht die lokale Code-UX-Datenbank, sodass die App nach dem Neuladen in einen sauberen Zustand zurückkehrt.",
    controls: "Das vollständige Zurücksetzen entfernt Projekte, Sprints, Aufgaben, Verläufe und Systemzustand.",
    recommended: "Nutze es nur für einen lokalen Neustart oder bei nicht behebbarer Datenbankbeschädigung, nachdem benötigte Daten exportiert wurden.",
    risks: "Dadurch wird der gesamte lokale Laufzeitzustand gelöscht; die Aktion kann im Dashboard nicht rückgängig gemacht werden.",
  },
} as const satisfies Record<SettingsSubcategoryId, SettingsSubcategoryHelpCopy>;

const localizeSettingsSubcategoryDoc = (
  doc: SettingsSubcategoryDoc,
  locale: DashboardLocale,
): SettingsSubcategoryDoc => {
  if (locale !== "de") {
    return doc;
  }
  const localizedTitle = GERMAN_SUBCATEGORY_TITLES[doc.id as SettingsSubcategoryId] ?? doc.title;
  return {
    ...doc,
    title: localizedTitle,
    ...GERMAN_SUBCATEGORY_HELP[doc.id as SettingsSubcategoryId],
  };
};

export const getSettingsSubcategoryDoc = (
  idOrTitle: SettingsSubcategoryId | string | undefined,
  locale: DashboardLocale = getDocumentDashboardLocale(),
): SettingsSubcategoryDoc | undefined => {
  if (!idOrTitle) {
    return undefined;
  }
  if (idOrTitle in SETTINGS_SUBCATEGORY_DOCS) {
    return localizeSettingsSubcategoryDoc(SETTINGS_SUBCATEGORY_DOCS[idOrTitle as SettingsSubcategoryId], locale);
  }
  const resolvedId = TITLE_TO_ID.get(normalizeTitle(idOrTitle));
  return resolvedId ? localizeSettingsSubcategoryDoc(SETTINGS_SUBCATEGORY_DOCS[resolvedId], locale) : undefined;
};

export const toHelpSections = (
  doc: SettingsSubcategoryDoc,
  locale: DashboardLocale = getDocumentDashboardLocale(),
): SettingsSubcategoryHelpSection[] => [
  { heading: getSettingsShellMessage(locale, "helpControls"), body: doc.controls },
  { heading: getSettingsShellMessage(locale, "helpRecommended"), body: doc.recommended },
  { heading: getSettingsShellMessage(locale, "helpRisks"), body: doc.risks },
];
