import { useCallback, useEffect, useMemo, useRef, useState } from "preact/hooks";
import { fetchExternalSettingsHints } from "../../lib/api/dashboard-api.js";
import { useProjectData } from "../context/project-data.js";
import {
  fetchProjectEffectiveSettings,
  fetchSystemSettings,
  resetProjectSettings,
  resetSystemDatabase,
  saveProjectSettings,
  saveSystemSettings,
} from "../lib/settings-api.js";
import { fetchAgentPresets } from "../lib/agent-preset-api.js";
import {
  applyExternalHintsToSystemSettings,
  cloneProjectSettings,
  cloneSystemSettings,
  dashboardSettingsToProjectSettings,
} from "../lib/settings-view-models.js";
import type {
  InvocationRoutingId,
  ProviderConfigId,
  ProjectSettings,
  ProviderId,
  SettingsValueSource,
  SystemSettings,
  ThinkingMode,
} from "../../types.js";
import type { AgentAvatarConfig } from "../types.js";
import { AlertTriangle, Bot, BrainCircuit, Cpu, Plug, Settings, SlidersHorizontal, Target } from "lucide-preact";

type SettingsScope = "system" | "project";
type CategoryId = "general" | "appearance" | "models" | "sprint" | "browser" | "agents" | "memory" | "integrations" | "mcp" | "danger";
type AgentInstructionTemplateId = keyof ProjectSettings["agents"]["instructionTemplates"];

interface Category {
  id: CategoryId;
  num: string;
  label: string;
  description: string;
  icon: typeof Settings;
  danger?: boolean;
}





const providerLabels: Record<ProviderId, string> = {
  jules: "Jules",
  gemini: "Gemini",
  codex: "Codex",
  "claude-code": "Claude Code",
  "qwen-code": "Qwen Code",
  opencode: "OpenCode",
  antigravity: "Antigravity",
};

const thinkingModeOptions: Array<{ value: ThinkingMode; label: string }> = [
  { value: "SMALL", label: "Small" },
  { value: "MEDIUM", label: "Medium" },
  { value: "HIGH", label: "High" },
];

const invocationRouteDefinitions: Array<{
  id: InvocationRoutingId;
  label: string;
  description: string;
}> = [
  { id: "task_coding", label: "Task coding", description: "Primary coding execution for provider-routed task work." },
  { id: "planning", label: "Planning", description: "Virtual planning and prompt-improvement requests." },
  { id: "dashboard_reply", label: "Dashboard reply", description: "Reply-only dashboard chat responses generated by a CLI provider." },
  { id: "clarification_reply", label: "Clarification reply", description: "Automatic clarification answers sent back to blocked workers." },
  { id: "qa_review", label: "QA review", description: "Completion-time quality assurance reviews that can request follow-up fixes." },
  { id: "ci_fix", label: "CI fix", description: "Worker-owned CI repair loops and retry work." },
  { id: "merge_conflict", label: "Merge conflict", description: "Worker-owned merge conflict resolution runs." },
];

const routingProfileOptions = [
  { value: "GLOBAL", label: "Global defaults" },
  { value: "WORKER", label: "Worker defaults" },
];

type IntegrationId = "jules" | "gemini" | "codex" | "claude-code" | "qwen-code" | "opencode" | "antigravity" | "github" | "gitlab" | "jira";

interface IntegrationDefinition {
  id: IntegrationId;
  label: string;
  description: string;
}

const INTEGRATIONS: IntegrationDefinition[] = [
  { id: "jules", label: "Jules", description: "Google Jules API service for agent session and workspace orchestration" },
  { id: "gemini", label: "Gemini", description: "Hosted execution provider and future worker endpoint" },
  { id: "antigravity", label: "Antigravity", description: "Google Antigravity CLI (agy) local container worker execution" },
  { id: "codex", label: "Codex", description: "Hosted execution provider and future worker endpoint" },
  { id: "claude-code", label: "Claude Code", description: "Hosted execution provider and future worker endpoint" },
  { id: "qwen-code", label: "Qwen Code", description: "Qwen CLI with OAuth, Alibaba Coding Plan, and custom model providers" },
  { id: "opencode", label: "OpenCode", description: "OpenCode CLI with local auth, provider keys, and custom OpenAI-compatible endpoints" },
  { id: "github", label: "GitHub", description: "Repository, pull request, branch, and CI integration" },
  { id: "gitlab", label: "GitLab", description: "GitLab repository, merge request, and CI token integration" },
  { id: "jira", label: "Jira", description: "Atlassian Jira issue search, sprint linking, and completion transitions" },
];

const AGENT_INSTRUCTION_TEMPLATE_OPTIONS: Array<{
  value: AgentInstructionTemplateId;
  label: string;
  description: string;
}> = [
  { value: "planningMissing", label: "Planning Missing", description: "Shown when a sprint has no planned tasks yet." },
  { value: "planningCreated", label: "Planning Created", description: "Shown after a planning request is prepared." },
  { value: "branchMissing", label: "Branch Missing", description: "Shown when the sprint feature branch must be created first." },
  { value: "mergeHeader", label: "Merge Header", description: "Header for merge-required intervention output." },
  { value: "mergeTask", label: "Merge Task", description: "Per-task merge instruction block." },
  { value: "actionRequiredAgentHeader", label: "Agent Attention Header", description: "Header for agent-owned intervention items." },
  { value: "actionRequiredAgentTask", label: "Agent Attention Task", description: "Per-task agent intervention block." },
  { value: "actionRequiredHumanHeader", label: "Human Attention Header", description: "Header for human-owned intervention items." },
  { value: "actionRequiredHumanTask", label: "Human Attention Task", description: "Per-task human intervention block." },
  { value: "watchHeader", label: "Run Header", description: "Top section for live orchestration status output." },
  { value: "watchMergeRequired", label: "Run Merge Required", description: "Shown when orchestration pauses for merges." },
  { value: "watchNoMoreActions", label: "Run No More Actions", description: "Shown when orchestration pauses with nothing runnable." },
  { value: "completionSteps", label: "Completion Steps", description: "Final sprint completion guidance." },
  { value: "cleanupAllMerged", label: "Cleanup All Merged", description: "Shown when cleanup confirms a fully merged sprint." },
  { value: "cleanupFailed", label: "Cleanup Failed", description: "Shown when cleanup is skipped because tasks failed." },
  { value: "cleanupDeferred", label: "Cleanup Deferred", description: "Shown when cleanup waits on merges." },
  { value: "cleanupEmpty", label: "Cleanup Empty", description: "Shown when the sprint is still empty." },
];

const QA_PRESET_LABEL_PATTERN = /(?:^|[\s_-])qa(?:$|[\s_-])|quality[\s_-]*assurance/i;

const sortAgentPresetOptions = (
  presets: Array<{ id: string; name: string; labels?: string[]; avatarConfig?: AgentAvatarConfig }>,
): Array<{ value: string; label: string; avatarConfig?: AgentAvatarConfig }> => (
  [...presets]
    .sort((left, right) => {
      const leftIsQa = (left.labels || []).some((label) => QA_PRESET_LABEL_PATTERN.test(label));
      const rightIsQa = (right.labels || []).some((label) => QA_PRESET_LABEL_PATTERN.test(label));
      if (leftIsQa !== rightIsQa) {
        return leftIsQa ? -1 : 1;
      }
      return left.name.localeCompare(right.name, undefined, { sensitivity: "base" });
    })
    .map((preset) => ({
      value: preset.id,
      label: preset.name,
      avatarConfig: preset.avatarConfig,
    }))
);


export const useSettingsPageState = (
  categories: Category[],
  searchHints: Record<CategoryId, string[]>
) => {
  const { deleteProject, selectedProject, selectedProjectId } = useProjectData();

  const isDirtyRef = useRef(false);

  const searchInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    const handleKeydown = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null;
      const isTypingTarget = target && (
        target.tagName === "INPUT"
        || target.tagName === "TEXTAREA"
        || target.tagName === "SELECT"
        || target.isContentEditable
      );
      if (event.key === "/" && !isTypingTarget) {
        event.preventDefault();
        searchInputRef.current?.focus();
        searchInputRef.current?.select();
      }
    };

    window.addEventListener("keydown", handleKeydown);
    return () => window.removeEventListener("keydown", handleKeydown);
  }, []);


  const [activeCategory, setActiveCategory] = useState<CategoryId>("general");
  const [activeScope, setActiveScope] = useState<SettingsScope>("system");
  const [selectedIntegration, setSelectedIntegration] = useState<IntegrationId | null>(null);
  const [selectedAgentTemplate, setSelectedAgentTemplate] = useState<AgentInstructionTemplateId>("planningMissing");
  const [activeInvocationRoute, setActiveInvocationRoute] = useState<InvocationRoutingId>("task_coding");
  const [activeProviderPanel, setActiveProviderPanel] = useState<ProviderConfigId | null>(null);
  const [settingsSearch, setSettingsSearch] = useState("");
  const [systemSettings, setSystemSettings] = useState<SystemSettings | null>(null);
  const [savedSystemSettings, setSavedSystemSettings] = useState<SystemSettings | null>(null);
  const [projectSettings, setProjectSettings] = useState<ProjectSettings | null>(null);
  const [savedProjectSettings, setSavedProjectSettings] = useState<ProjectSettings | null>(null);
  const [projectSources, setProjectSources] = useState<Record<string, SettingsValueSource>>({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [saveMessage, setSaveMessage] = useState<string | null>(null);
  const [savingSystem, setSavingSystem] = useState(false);
  const [savingProject, setSavingProject] = useState(false);
  const [resettingProject, setResettingProject] = useState(false);
  const [deletingProject, setDeletingProject] = useState(false);
  const [resettingDatabase, setResettingDatabase] = useState(false);
  const [importingHints, setImportingHints] = useState(false);
  const [externalHints, setExternalHints] = useState<import("../../types.js").ExternalSettingsHints | null>(null);
  const [projectAgentPresetOptions, setProjectAgentPresetOptions] = useState<Array<{ value: string; label: string; avatarConfig?: AgentAvatarConfig }>>([]);

  const loadSettings = useCallback(async (): Promise<void> => {
    setLoading(true);
    try {
      const [nextSystem, hints] = await Promise.all([
        fetchSystemSettings(),
        fetchExternalSettingsHints()
      ]);

      // Restore last active scope on initial settings load
      if (!systemSettings) {
        const initialScope = nextSystem.runtime.lastActiveScope === "project" && selectedProjectId ? "project" : "system";
        setActiveScope(initialScope);
      }

      // Preserve local dirty edits during background reload
      if (!isDirtyRef.current || !systemSettings) {
        setSystemSettings(cloneSystemSettings(nextSystem));
      }

      setSavedSystemSettings(cloneSystemSettings(nextSystem));
      setExternalHints(hints);

      if (selectedProjectId) {
        const [effectiveProject, projectAgentPresets] = await Promise.all([
          fetchProjectEffectiveSettings(selectedProjectId),
          fetchAgentPresets(selectedProjectId).catch(() => []),
        ]);
        const nextProject = dashboardSettingsToProjectSettings(effectiveProject.settings);

        // Preserve local dirty edits during background reload by not overwriting them
        if (!isDirtyRef.current || !projectSettings) {
          setProjectSettings(cloneProjectSettings(nextProject));
        }

        setSavedProjectSettings(cloneProjectSettings(nextProject));
        setProjectSources(effectiveProject.sources);
        setProjectAgentPresetOptions(sortAgentPresetOptions(projectAgentPresets));
      } else {
        setProjectSettings(null);
        setSavedProjectSettings(null);
        setProjectSources({});
        setProjectAgentPresetOptions([]);
      }
      setError(null);
    } catch (loadError) {
      setError(loadError instanceof Error ? loadError.message : String(loadError));
    } finally {
      setLoading(false);
    }
  }, [selectedProjectId]);

  useEffect(() => {
    void loadSettings();
  }, [loadSettings]);

  useEffect(() => {
    if (!selectedProject && activeScope === "project") {
      setActiveScope("system");
    }
  }, [activeScope, selectedProject]);

  useEffect(() => {
    if (!saveMessage) {
      return;
    }
    const timeoutId = window.setTimeout(() => setSaveMessage(null), 2400);
    return () => window.clearTimeout(timeoutId);
  }, [saveMessage]);

  const systemDirty = useMemo(() => (
    systemSettings && savedSystemSettings
      ? JSON.stringify(systemSettings) !== JSON.stringify(savedSystemSettings)
      : false
  ), [savedSystemSettings, systemSettings]);

  const projectDirty = useMemo(() => (
    projectSettings && savedProjectSettings
      ? JSON.stringify(projectSettings) !== JSON.stringify(savedProjectSettings)
      : false
  ), [projectSettings, savedProjectSettings]);

  useEffect(() => {
    isDirtyRef.current = systemDirty || projectDirty;
  }, [systemDirty, projectDirty]);

  const editableSettings = activeScope === "system" ? systemSettings?.defaults ?? null : projectSettings;
  const activeCategoryConfig = categories.find((category) => category.id === activeCategory) ?? categories[0]!;

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }
    window.dispatchEvent(new CustomEvent("codeux:appearance-preview", {
      detail: { appearance: editableSettings?.appearance ?? null },
    }));
  }, [editableSettings?.appearance]);

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }
    return () => {
      window.dispatchEvent(new CustomEvent("codeux:appearance-preview", {
        detail: { appearance: null },
      }));
    };
  }, []);

  const normalizedSearch = settingsSearch.trim().toLowerCase();
  const filteredCategories = useMemo(() => {
    if (!normalizedSearch) {
      return categories;
    }

    return categories.filter((category) => {
      const haystack = [
        category.label,
        category.description,
        ...(searchHints[category.id] || []),
      ].join(" ").toLowerCase();
      return haystack.includes(normalizedSearch);
    });
  }, [normalizedSearch]);

  useEffect(() => {
    if (filteredCategories.length === 0) {
      return;
    }
    if (!filteredCategories.some((category) => category.id === activeCategory)) {
      setActiveCategory(filteredCategories[0]!.id);
    }
  }, [activeCategory, filteredCategories]);

  const updateSystem = useCallback((recipe: (current: SystemSettings) => SystemSettings): void => {
    setSystemSettings((current) => (current ? recipe(current) : current));
  }, []);

  const updateProject = useCallback((recipe: (current: ProjectSettings) => ProjectSettings): void => {
    setProjectSettings((current) => (current ? recipe(current) : current));
  }, []);

  const updateEditableSettings = useCallback((recipe: (current: ProjectSettings) => ProjectSettings): void => {
    if (activeScope === "system") {
      updateSystem((current) => ({ ...current, defaults: recipe(current.defaults) }));
      return;
    }
    updateProject(recipe);
  }, [activeScope, updateProject, updateSystem]);

  const handleImportHints = useCallback(async (): Promise<void> => {
    if (!systemSettings) {
      return;
    }
    setImportingHints(true);
    try {
      const hints = await fetchExternalSettingsHints();
      const nextSettings = applyExternalHintsToSystemSettings(systemSettings, hints);
      setSystemSettings(nextSettings);
      setSaveMessage("Imported missing integration secrets from env/settings.json.");
      setError(null);
    } catch (hintError) {
      setError(hintError instanceof Error ? hintError.message : String(hintError));
    } finally {
      setImportingHints(false);
    }
  }, [systemSettings]);

  const handleSave = useCallback(async (): Promise<void> => {
    if (activeScope === "system") {
      if (!systemSettings) {
        return;
      }
      setSavingSystem(true);
      try {
        const saved = await saveSystemSettings(systemSettings);
        setSystemSettings(cloneSystemSettings(saved));
        setSavedSystemSettings(cloneSystemSettings(saved));

        if (selectedProject) {
          const effectiveProject = await fetchProjectEffectiveSettings(selectedProject.id);
          const nextProject = dashboardSettingsToProjectSettings(effectiveProject.settings);
          setProjectSettings(cloneProjectSettings(nextProject));
          setSavedProjectSettings(cloneProjectSettings(nextProject));
          setProjectSources(effectiveProject.sources);
        }

        setError(null);
        setSaveMessage("System settings saved.");
      } catch (saveError) {
        setError(saveError instanceof Error ? saveError.message : String(saveError));
      } finally {
        setSavingSystem(false);
      }
      return;
    }

    if (!selectedProject || !projectSettings) {
      return;
    }

    setSavingProject(true);
    try {
      await saveProjectSettings(selectedProject.id, projectSettings);
      const effectiveProject = await fetchProjectEffectiveSettings(selectedProject.id);
      const nextProject = dashboardSettingsToProjectSettings(effectiveProject.settings);
      setProjectSettings(cloneProjectSettings(nextProject));
      setSavedProjectSettings(cloneProjectSettings(nextProject));
      setProjectSources(effectiveProject.sources);
      setError(null);
      setSaveMessage(`Project settings saved for ${selectedProject.name}.`);
    } catch (saveError) {
      setError(saveError instanceof Error ? saveError.message : String(saveError));
    } finally {
      setSavingProject(false);
    }
  }, [activeScope, systemSettings, selectedProject, projectSettings]);

  const handleResetProject = useCallback(async (): Promise<void> => {
    if (!selectedProject) {
      return;
    }
    setResettingProject(true);
    try {
      await resetProjectSettings(selectedProject.id);
      const effectiveProject = await fetchProjectEffectiveSettings(selectedProject.id);
      const nextProject = dashboardSettingsToProjectSettings(effectiveProject.settings);
      setProjectSettings(cloneProjectSettings(nextProject));
      setSavedProjectSettings(cloneProjectSettings(nextProject));
      setProjectSources(effectiveProject.sources);
      setError(null);
      setSaveMessage(`Project overrides reset for ${selectedProject.name}.`);
    } catch (resetError) {
      setError(resetError instanceof Error ? resetError.message : String(resetError));
    } finally {
      setResettingProject(false);
    }
  }, [selectedProject]);

  const handleDeleteProject = useCallback(async (): Promise<void> => {
    if (!selectedProject) {
      return;
    }
    if (!window.confirm(`Delete project "${selectedProject.name}" and all of its sprints, tasks, chats, and runtime records?`)) {
      return;
    }

    setDeletingProject(true);
    try {
      await deleteProject(selectedProject.id);
      setActiveScope("system");
      setActiveCategory("general");
      setSaveMessage(`Project ${selectedProject.name} deleted.`);
      setError(null);
    } catch (deleteError) {
      setError(deleteError instanceof Error ? deleteError.message : String(deleteError));
    } finally {
      setDeletingProject(false);
    }
  }, [selectedProject, deleteProject]);

  const handleResetDatabase = useCallback(async (): Promise<void> => {
    if (!window.confirm("Reset the full database and scoped settings back to a clean development state? This deletes all projects, sprints, tasks, runtime state, chats, and saved settings.")) {
      return;
    }

    setResettingDatabase(true);
    try {
      await resetSystemDatabase();
      setActiveScope("system");
      setActiveCategory("general");
      await loadSettings();
      setSaveMessage("Database reset to a clean state.");
      setError(null);
    } catch (resetError) {
      setError(resetError instanceof Error ? resetError.message : String(resetError));
    } finally {
      setResettingDatabase(false);
    }
  }, [loadSettings]);

  const getValueByPath = useCallback((obj: any, path: string): any => {
    return path.split(".").reduce((acc, part) => acc && acc[part], obj);
  }, []);

  const setValueByPath = useCallback((obj: any, path: string, value: any): any => {
    const parts = path.split(".");
    const next = { ...obj };
    let current = next;
    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i]!;
      current[part] = { ...current[part] };
      current = current[part];
    }
    current[parts[parts.length - 1]!] = value;
    return next;
  }, []);

  const resetFieldToDefault = useCallback((path: string): void => {
    if (!systemSettings || !projectSettings) {
      return;
    }
    const defaultValue = getValueByPath(systemSettings.defaults, path);
    setProjectSettings((current) => {
      if (!current) return current;
      return setValueByPath(current, path, defaultValue);
    });
    setProjectSources((current) => ({
      ...current,
      [path]: "system",
    }));
  }, [systemSettings, projectSettings, getValueByPath, setValueByPath]);

  const getFieldReset = useCallback((path: string) => {
    if (activeScope === "project" && projectSources[path] === "project") {
      return () => resetFieldToDefault(path);
    }
    return undefined;
  }, [activeScope, projectSources, resetFieldToDefault]);

  const setPersistedActiveScope = useCallback(async (scope: SettingsScope) => {
    setActiveScope(scope);
    if (systemSettings) {
      const updatedSystem = {
        ...systemSettings,
        runtime: {
          ...systemSettings.runtime,
          lastActiveScope: scope,
        },
      };
      setSystemSettings(updatedSystem);
      setSavedSystemSettings(cloneSystemSettings(updatedSystem));
      try {
        await saveSystemSettings(updatedSystem);
      } catch (e) {
        // Ignore background persistence errors
      }
    }
  }, [systemSettings]);

  const activeDirty = activeScope === "system" ? systemDirty : projectDirty;
  const activeSaving = activeScope === "system" ? savingSystem : savingProject;

  return {
    activeCategory, setActiveCategory,
    activeScope, setActiveScope: setPersistedActiveScope,
    selectedIntegration, setSelectedIntegration,
    selectedAgentTemplate, setSelectedAgentTemplate,
    activeInvocationRoute, setActiveInvocationRoute,
    activeProviderPanel, setActiveProviderPanel,
    settingsSearch, setSettingsSearch,
    systemSettings,
    projectSettings,
    projectSources,
    editableSettings,
    loading, error, saveMessage,
    savingSystem, savingProject, activeSaving, activeDirty,
    resettingProject, deletingProject, resettingDatabase, importingHints,
    externalHints,
    activeCategoryConfig, filteredCategories,
    categories: categories,
    providerLabels,
    thinkingModeOptions,
    invocationRouteDefinitions,
    routingProfileOptions,
    integrations: INTEGRATIONS,
    agentInstructionTemplateOptions: AGENT_INSTRUCTION_TEMPLATE_OPTIONS,
    projectAgentPresetOptions,
    selectedProject,
    updateSystem, updateProject, updateEditableSettings,
    handleImportHints, handleSave, handleResetProject,
    handleDeleteProject, handleResetDatabase,
    loadSettings,
    isDirtyRef,
    searchInputRef,
    resetFieldToDefault,
    getFieldReset
  };
};

export type SettingsPageState = ReturnType<typeof useSettingsPageState>;
export type { Category, IntegrationDefinition, CategoryId, SettingsScope, AgentInstructionTemplateId, IntegrationId };
