import { useCallback, useEffect, useMemo, useRef, useState } from "preact/hooks";
import { fetchExternalSettingsHints } from "../../lib/api/dashboard-api.js";
import { useProjectData } from "../context/project-data.js";
import {
  fetchProjectEffectiveSettings,
  fetchSystemSettings,
  resetProjectSettings,
  resetSystemDatabase,
  saveProjectSettings,
  saveSystemSettings,
} from "../lib/settings-api.js";
import { fetchAgentPresets } from "../lib/agent-preset-api.js";
import { clearProjectMemories, clearSystemMemories, type MemoryClearTier } from "../lib/memory-api.js";
import {
  createChatProviderChannelBinding,
  createChatProviderConnection,
  deleteChatProviderChannelBinding,
  deleteChatProviderConnection,
  fetchChatProviderChannelBindings,
  fetchChatProviderConnectionDeliveries,
  fetchChatProviderConnections,
  fetchChatProviderSetupDefinitions,
  updateChatProviderChannelBinding,
  updateChatProviderConnection,
  type DashboardChatProviderConnectionRecord,
  type DashboardChatProviderSetupDefinition,
} from "../lib/chat-provider-api.js";
import { registerNavigationBlocker } from "../router/navigation-blocker.js";
import {
  applyExternalHintsToSystemSettings,
  cloneProjectSettings,
  cloneSystemSettings,
  dashboardSettingsToProjectSettings,
  thinkingModeOptions,
} from "../lib/settings-view-models.js";
import { DEFAULT_DASHBOARD_SETTINGS } from "../../lib/settings.js";
import {
  buildSettingsSearchIndex,
  searchSettingsCategories,
} from "../lib/settings-search-index.js";
import {
  providerDescriptions,
  providerLabels,
} from "../lib/onboarding-provider-settings.js";
import {
  clearAppearancePreview,
  publishAppearancePreview,
} from "../lib/appearance-preview.js";
import type {
  InvocationRoutingId,
  ProviderConfigId,
  ChatProviderChannelBindingRecord,
  ChatProviderKind,
  ChatProviderMessageDeliveryRecord,
  CreateChatProviderChannelBindingInput,
  CreateChatProviderConnectionInput,
  ProjectSettings,
  SettingsValueSource,
  SystemSettings,
  UpdateChatProviderChannelBindingInput,
  UpdateChatProviderConnectionInput,
} from "../../types.js";
import type { AgentAvatarConfig, AgentPreset } from "../types.js";
import { AlertTriangle, Bot, BrainCircuit, Cpu, Plug, Settings, SlidersHorizontal, Target } from "lucide-preact";

type SettingsScope = "system" | "project";
type CategoryId = "general" | "appearance" | "models" | "sprint" | "browser" | "techstacks" | "guidance" | "agents" | "memory" | "integrations" | "mcp" | "danger";
type AgentInstructionTemplateId = keyof ProjectSettings["agents"]["instructionTemplates"];

interface Category {
  id: CategoryId;
  num: string;
  label: string;
  description: string;
  icon: typeof Settings;
  danger?: boolean;
}





const normalizeSystemSettingsPayload = (settings: SystemSettings): SystemSettings => ({
  ...settings,
  techstackCatalog: settings.techstackCatalog ?? DEFAULT_DASHBOARD_SETTINGS.techstackCatalog,
});

const invocationRouteDefinitions: Array<{
  id: InvocationRoutingId;
  label: string;
  description: string;
}> = [
  { id: "task_coding", label: "Task coding", description: "Primary coding execution for provider-routed task work." },
  { id: "planning", label: "Planning", description: "Virtual planning and prompt-improvement requests." },
  { id: "dashboard_reply", label: "Dashboard reply", description: "Reply-only dashboard chat responses generated by a CLI provider." },
  { id: "clarification_reply", label: "Clarification reply", description: "Automatic clarification answers sent back to blocked workers." },
  { id: "qa_review", label: "QA review", description: "Completion-time quality assurance reviews that can request follow-up fixes." },
  { id: "ci_fix", label: "CI fix", description: "Worker-owned CI repair loops and retry work." },
  { id: "merge_conflict", label: "Merge conflict", description: "Worker-owned merge conflict resolution runs." },
  { id: "remediation", label: "Remediation", description: "Memory curation and long-term remediation reviews." },
];

const routingProfileOptions = [
  { value: "GLOBAL", label: "Global defaults" },
  { value: "WORKER", label: "Worker defaults" },
];

type IntegrationId =
  | "jules"
  | "gemini"
  | "codex"
  | "claude-code"
  | "qwen-code"
  | "opencode"
  | "antigravity"
  | "github"
  | "gitlab"
  | "jira"
  | "notion"
  | "asana"
  | "linear"
  | "miro"
  | "lucid"
  | "figma"
  | "mural"
  | ChatProviderKind;

interface IntegrationDefinition {
  id: IntegrationId;
  label: string;
  description: string;
}

const INTEGRATIONS: IntegrationDefinition[] = [
  { id: "jules", label: providerLabels.jules, description: providerDescriptions.jules },
  { id: "gemini", label: providerLabels.gemini, description: providerDescriptions.gemini },
  { id: "antigravity", label: providerLabels.antigravity, description: providerDescriptions.antigravity },
  { id: "codex", label: providerLabels.codex, description: providerDescriptions.codex },
  { id: "claude-code", label: providerLabels["claude-code"], description: providerDescriptions["claude-code"] },
  { id: "qwen-code", label: providerLabels["qwen-code"], description: providerDescriptions["qwen-code"] },
  { id: "opencode", label: providerLabels.opencode, description: providerDescriptions.opencode },
  { id: "github", label: "GitHub", description: "Repository, pull request, branch, and CI integration" },
  { id: "gitlab", label: "GitLab", description: "GitLab repository, merge request, and CI token integration" },
  { id: "jira", label: "Jira", description: "Atlassian Jira issue search, sprint linking, and completion transitions" },
  { id: "whatsapp", label: "WhatsApp", description: "Managed or webhook bridge for WhatsApp groups and business conversations" },
  { id: "imessage", label: "iMessage", description: "Managed or native macOS bridge for iMessage routing" },
  { id: "telegram", label: "Telegram", description: "Telegram bot or managed bridge for channel ingress and replies" },
  { id: "slack", label: "Slack", description: "Slack Events or managed bridge with signed webhooks" },
  { id: "microsoft-teams", label: "Microsoft Teams", description: "Teams bot or managed bridge for tenant channels" },
  { id: "discord", label: "Discord", description: "Discord bot or gateway connection for project chat" },
  { id: "notion", label: "Notion", description: "Read-only import from Notion workspace pages and databases" },
  { id: "asana", label: "Asana", description: "Read-only import from Asana workspaces, teams, and projects" },
  { id: "linear", label: "Linear", description: "Read-only import from Linear teams, projects, and issues" },
  { id: "miro", label: "Miro", description: "Read-only import from Miro teams and boards" },
  { id: "lucid", label: "Lucid", description: "Read-only import from Lucid or Lucidspark documents" },
  { id: "figma", label: "Figma / FigJam", description: "Read-only import from Figma files and FigJam boards" },
  { id: "mural", label: "Mural", description: "Read-only import from Mural workspaces and murals" },
];

const AGENT_INSTRUCTION_TEMPLATE_OPTIONS: Array<{
  value: AgentInstructionTemplateId;
  label: string;
  description: string;
}> = [
  { value: "planningMissing", label: "Planning Missing", description: "Shown when a sprint has no planned tasks yet." },
  { value: "planningCreated", label: "Planning Created", description: "Shown after a planning request is prepared." },
  { value: "branchMissing", label: "Branch Missing", description: "Shown when the sprint feature branch must be created first." },
  { value: "mergeHeader", label: "Merge Header", description: "Header for merge-required intervention output." },
  { value: "mergeTask", label: "Merge Task", description: "Per-task merge instruction block." },
  { value: "actionRequiredAgentHeader", label: "Agent Attention Header", description: "Header for agent-owned intervention items." },
  { value: "actionRequiredAgentTask", label: "Agent Attention Task", description: "Per-task agent intervention block." },
  { value: "actionRequiredHumanHeader", label: "Human Attention Header", description: "Header for human-owned intervention items." },
  { value: "actionRequiredHumanTask", label: "Human Attention Task", description: "Per-task human intervention block." },
  { value: "watchHeader", label: "Run Header", description: "Top section for live orchestration status output." },
  { value: "watchMergeRequired", label: "Run Merge Required", description: "Shown when orchestration pauses for merges." },
  { value: "watchNoMoreActions", label: "Run No More Actions", description: "Shown when orchestration pauses with nothing runnable." },
  { value: "completionSteps", label: "Completion Steps", description: "Final sprint completion guidance." },
  { value: "cleanupAllMerged", label: "Cleanup All Merged", description: "Shown when cleanup confirms a fully merged sprint." },
  { value: "cleanupFailed", label: "Cleanup Failed", description: "Shown when cleanup is skipped because tasks failed." },
  { value: "cleanupDeferred", label: "Cleanup Deferred", description: "Shown when cleanup waits on merges." },
  { value: "cleanupEmpty", label: "Cleanup Empty", description: "Shown when the sprint is still empty." },
];

const QA_PRESET_LABEL_PATTERN = /(?:^|[\s_-])qa(?:$|[\s_-])|quality[\s_-]*assurance/i;

const sortAgentPresetOptions = (
  presets: Array<{ id: string; name: string; labels?: string[]; avatarConfig?: AgentAvatarConfig }>,
): Array<{ value: string; label: string; avatarConfig?: AgentAvatarConfig }> => (
  [...presets]
    .sort((left, right) => {
      const leftIsQa = (left.labels || []).some((label) => QA_PRESET_LABEL_PATTERN.test(label));
      const rightIsQa = (right.labels || []).some((label) => QA_PRESET_LABEL_PATTERN.test(label));
      if (leftIsQa !== rightIsQa) {
        return leftIsQa ? -1 : 1;
      }
      return left.name.localeCompare(right.name, undefined, { sensitivity: "base" });
    })
    .map((preset) => ({
      value: preset.id,
      label: preset.name,
      avatarConfig: preset.avatarConfig,
    }))
);


export const useSettingsPageState = (
  categories: Category[],
) => {
  const { deleteProject, projects, selectedProject, selectedProjectId } = useProjectData();

  const isDirtyRef = useRef(false);

  const searchInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    const handleKeydown = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null;
      const isTypingTarget = target && (
        target.tagName === "INPUT"
        || target.tagName === "TEXTAREA"
        || target.tagName === "SELECT"
        || target.isContentEditable
      );
      if (event.key === "/" && !isTypingTarget) {
        event.preventDefault();
        searchInputRef.current?.focus();
        searchInputRef.current?.select();
      }
    };

    window.addEventListener("keydown", handleKeydown);
    return () => window.removeEventListener("keydown", handleKeydown);
  }, []);


  const [activeCategory, setActiveCategory] = useState<CategoryId>("general");
  const [activeScope, setActiveScopeState] = useState<SettingsScope>("system");
  const [selectedIntegration, setSelectedIntegration] = useState<IntegrationId | null>(null);
  const [selectedAgentTemplate, setSelectedAgentTemplate] = useState<AgentInstructionTemplateId>("planningMissing");
  const [activeInvocationRoute, setActiveInvocationRoute] = useState<InvocationRoutingId>("task_coding");
  const [activeProviderPanel, setActiveProviderPanel] = useState<ProviderConfigId | null>(null);
  const [settingsSearch, setSettingsSearch] = useState("");
  const [systemSettings, setSystemSettings] = useState<SystemSettings | null>(null);
  const [savedSystemSettings, setSavedSystemSettings] = useState<SystemSettings | null>(null);
  const [projectSettings, setProjectSettings] = useState<ProjectSettings | null>(null);
  const [savedProjectSettings, setSavedProjectSettings] = useState<ProjectSettings | null>(null);
  const [projectSources, setProjectSources] = useState<Record<string, SettingsValueSource>>({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [saveMessage, setSaveMessage] = useState<string | null>(null);
  const clearFeedback = useCallback(() => {
    setError(null);
    setSaveMessage(null);
  }, []);
  const [savingSystem, setSavingSystem] = useState(false);
  const [savingProject, setSavingProject] = useState(false);
  const [resettingProject, setResettingProject] = useState(false);
  const [deletingProject, setDeletingProject] = useState(false);
  const [resettingDatabase, setResettingDatabase] = useState(false);
  const [memoryClearBusy, setMemoryClearBusy] = useState<string | null>(null);
  const [importingHints, setImportingHints] = useState(false);
  const [externalHints, setExternalHints] = useState<import("../../types.js").ExternalSettingsHints | null>(null);
  const [projectAgentPresets, setProjectAgentPresets] = useState<AgentPreset[]>([]);
  const [projectAgentPresetOptions, setProjectAgentPresetOptions] = useState<Array<{ value: string; label: string; avatarConfig?: AgentAvatarConfig }>>([]);
  const [chatProviderDefinitions, setChatProviderDefinitions] = useState<DashboardChatProviderSetupDefinition[]>([]);
  const [chatProviderConnections, setChatProviderConnections] = useState<DashboardChatProviderConnectionRecord[]>([]);
  const [chatProviderBindings, setChatProviderBindings] = useState<ChatProviderChannelBindingRecord[]>([]);
  const [chatProviderDeliveriesByConnection, setChatProviderDeliveriesByConnection] = useState<Record<string, ChatProviderMessageDeliveryRecord[]>>({});
  const [chatProvidersLoading, setChatProvidersLoading] = useState(false);
  const [chatProvidersSavingId, setChatProvidersSavingId] = useState<string | null>(null);
  const [chatProvidersError, setChatProvidersError] = useState<string | null>(null);
  const previousCategoryRef = useRef<CategoryId>("general");
  const scopePersistenceRequestRef = useRef(0);

  const loadSettings = useCallback(async (): Promise<void> => {
    setLoading(true);
    try {
      const [nextSystem, hints] = await Promise.all([
        fetchSystemSettings(),
        fetchExternalSettingsHints()
      ]);

      // Restore last active scope on initial settings load
      if (!systemSettings) {
        const initialScope = nextSystem.runtime.lastActiveScope === "project" && selectedProjectId ? "project" : "system";
        setActiveScopeState(initialScope);
      }

      const normalizedSystem = normalizeSystemSettingsPayload(nextSystem);

      // Preserve local dirty edits during background reload
      if (!isDirtyRef.current || !systemSettings) {
        setSystemSettings(cloneSystemSettings(normalizedSystem));
      }

      setSavedSystemSettings(cloneSystemSettings(normalizedSystem));
      setExternalHints(hints);

      if (selectedProjectId) {
        const [effectiveProject, nextProjectAgentPresets] = await Promise.all([
          fetchProjectEffectiveSettings(selectedProjectId, { cache: "reload" }),
          fetchAgentPresets(selectedProjectId).catch(() => []),
        ]);
        const nextProject = dashboardSettingsToProjectSettings(effectiveProject.settings);

        // Preserve local dirty edits during background reload by not overwriting them
        if (!isDirtyRef.current || !projectSettings) {
          setProjectSettings(cloneProjectSettings(nextProject));
        }

        setSavedProjectSettings(cloneProjectSettings(nextProject));
        setProjectSources(effectiveProject.sources);
        setProjectAgentPresets(nextProjectAgentPresets);
        setProjectAgentPresetOptions(sortAgentPresetOptions(nextProjectAgentPresets));
      } else {
        setProjectSettings(null);
        setSavedProjectSettings(null);
        setProjectSources({});
        setProjectAgentPresets([]);
        setProjectAgentPresetOptions([]);
      }
      setError(null);
    } catch (loadError) {
      setError(loadError instanceof Error ? loadError.message : String(loadError));
    } finally {
      setLoading(false);
    }
  }, [selectedProjectId]);

  useEffect(() => {
    void loadSettings();
  }, [loadSettings]);

  const loadChatProviders = useCallback(async (): Promise<void> => {
    setChatProvidersLoading(true);
    try {
      const [definitions, connections, bindings] = await Promise.all([
        fetchChatProviderSetupDefinitions(),
        fetchChatProviderConnections(),
        fetchChatProviderChannelBindings(),
      ]);
      const deliveryEntries = await Promise.all(
        connections.map(async (connection) => [
          connection.id,
          await fetchChatProviderConnectionDeliveries(connection.id, 25).catch(() => []),
        ] as const),
      );

      setChatProviderDefinitions(definitions);
      setChatProviderConnections(connections);
      setChatProviderBindings(bindings);
      setChatProviderDeliveriesByConnection(Object.fromEntries(deliveryEntries));
      setChatProvidersError(null);
    } catch (loadError) {
      setChatProvidersError(loadError instanceof Error ? loadError.message : String(loadError));
    } finally {
      setChatProvidersLoading(false);
    }
  }, []);

  useEffect(() => {
    if (activeCategory !== "integrations") {
      return;
    }
    void loadChatProviders();
  }, [activeCategory, loadChatProviders]);

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }

    const handleSettingsUpdated = () => {
      if (activeCategory !== "models" || isDirtyRef.current) {
        return;
      }
      void loadSettings();
    };

    window.addEventListener("codeux:settings-updated", handleSettingsUpdated);
    return () => window.removeEventListener("codeux:settings-updated", handleSettingsUpdated);
  }, [activeCategory, loadSettings]);

  useEffect(() => {
    const wasModels = previousCategoryRef.current === "models";
    const isModels = activeCategory === "models";
    previousCategoryRef.current = activeCategory;

    if (!isModels || wasModels || isDirtyRef.current) {
      return;
    }

    void loadSettings();
  }, [activeCategory, loadSettings]);

  useEffect(() => {
    if (!saveMessage) {
      return;
    }
    const timeoutId = window.setTimeout(() => setSaveMessage(null), 2400);
    return () => window.clearTimeout(timeoutId);
  }, [saveMessage]);

  const systemDirty = useMemo(() => (
    systemSettings && savedSystemSettings
      ? JSON.stringify(systemSettings) !== JSON.stringify(savedSystemSettings)
      : false
  ), [savedSystemSettings, systemSettings]);

  const projectDirty = useMemo(() => (
    projectSettings && savedProjectSettings
      ? JSON.stringify(projectSettings) !== JSON.stringify(savedProjectSettings)
      : false
  ), [projectSettings, savedProjectSettings]);

  // Keep the dirty flag in sync synchronously rather than in a post-commit effect.
  // `loadSettings` reads `isDirtyRef.current` to decide whether to preserve in-progress
  // edits; with an effect, a background reload landing in the one-render gap after the
  // user's first keystroke would still read `false`, overwrite the edit with server state,
  // and leave the Save button greyed out. Assigning during render closes that gap.
  isDirtyRef.current = systemDirty || projectDirty;

  const setPersistedActiveScope = useCallback(async (scope: SettingsScope): Promise<void> => {
    setActiveScopeState(scope);

    const persistenceBase = savedSystemSettings ?? systemSettings;
    if (!persistenceBase) {
      return;
    }

    const previousSavedSettings = cloneSystemSettings(normalizeSystemSettingsPayload(persistenceBase));
    const previousLastActiveScope = previousSavedSettings.runtime.lastActiveScope ?? "system";
    if (previousLastActiveScope === scope) {
      return;
    }

    const requestId = scopePersistenceRequestRef.current + 1;
    scopePersistenceRequestRef.current = requestId;
    const hadSystemDraft = Boolean(systemSettings && savedSystemSettings && JSON.stringify(systemSettings) !== JSON.stringify(savedSystemSettings));
    const nextSavedSettings = cloneSystemSettings({
      ...previousSavedSettings,
      runtime: {
        ...previousSavedSettings.runtime,
        lastActiveScope: scope,
      },
    });

    setSavedSystemSettings(cloneSystemSettings(nextSavedSettings));
    setSystemSettings((current) => current
      ? {
          ...current,
          runtime: {
            ...current.runtime,
            lastActiveScope: scope,
          },
        }
      : current);

    try {
      const saved = await saveSystemSettings(nextSavedSettings);
      if (scopePersistenceRequestRef.current !== requestId) {
        return;
      }
      const normalizedSaved = normalizeSystemSettingsPayload({
        ...nextSavedSettings,
        ...saved,
        runtime: {
          ...nextSavedSettings.runtime,
          ...saved.runtime,
        },
      });
      setSavedSystemSettings(cloneSystemSettings(normalizedSaved));
      setSystemSettings((current) => {
        if (hadSystemDraft && current) {
          return {
            ...current,
            runtime: {
              ...current.runtime,
              lastActiveScope: normalizedSaved.runtime.lastActiveScope,
            },
          };
        }
        return cloneSystemSettings(normalizedSaved);
      });
      setError((current) => current === "Failed to persist Settings scope selection." ? null : current);
    } catch {
      if (scopePersistenceRequestRef.current !== requestId) {
        return;
      }
      setSavedSystemSettings(previousSavedSettings);
      setSystemSettings((current) => current
        ? {
            ...current,
            runtime: {
              ...current.runtime,
              lastActiveScope: previousLastActiveScope,
            },
          }
        : current);
      setError("Failed to persist Settings scope selection.");
    }
  }, [savedSystemSettings, systemSettings]);

  useEffect(() => {
    if (!selectedProject && activeScope === "project") {
      void setPersistedActiveScope("system");
    }
  }, [activeScope, selectedProject, setPersistedActiveScope]);

  const editableSettings = activeScope === "system" ? systemSettings?.defaults ?? null : projectSettings;
  const activeCategoryConfig = categories.find((category) => category.id === activeCategory) ?? categories[0]!;

  useEffect(() => {
    publishAppearancePreview(editableSettings?.appearance ?? null);
  }, [editableSettings?.appearance]);

  useEffect(() => {
    return clearAppearancePreview;
  }, []);

  const normalizedSearch = settingsSearch.trim().toLowerCase();
  const settingsSearchIndex = useMemo(() => buildSettingsSearchIndex({
    categories,
    providerLabels,
    integrations: INTEGRATIONS,
    invocationRouteDefinitions,
    agentInstructionTemplateOptions: AGENT_INSTRUCTION_TEMPLATE_OPTIONS,
    thinkingModeOptions,
  }), [categories]);
  const settingsSearchMatches = useMemo(
    () => searchSettingsCategories(settingsSearchIndex, normalizedSearch),
    [normalizedSearch, settingsSearchIndex],
  );
  const filteredCategories = useMemo(() => {
    if (!normalizedSearch) {
      return categories;
    }

    return categories.filter((category) => Boolean(settingsSearchMatches[category.id]));
  }, [categories, normalizedSearch, settingsSearchMatches]);

  useEffect(() => {
    if (filteredCategories.length === 0) {
      return;
    }
    if (!filteredCategories.some((category) => category.id === activeCategory)) {
      setActiveCategory(filteredCategories[0]!.id);
    }
  }, [activeCategory, filteredCategories]);

  const updateSystem = useCallback((recipe: (current: SystemSettings) => SystemSettings): void => {
    setSystemSettings((current) => (current ? recipe(current) : current));
  }, []);

  const updateProject = useCallback((recipe: (current: ProjectSettings) => ProjectSettings): void => {
    setProjectSettings((current) => (current ? recipe(current) : current));
  }, []);

  const updateEditableSettings = useCallback((recipe: (current: ProjectSettings) => ProjectSettings): void => {
    if (activeScope === "system") {
      updateSystem((current) => ({ ...current, defaults: recipe(current.defaults) }));
      return;
    }
    updateProject(recipe);
  }, [activeScope, updateProject, updateSystem]);

  const handleImportHints = useCallback(async (): Promise<void> => {
    if (!systemSettings) {
      return;
    }
    setImportingHints(true);
    try {
      const hints = await fetchExternalSettingsHints();
      const nextSettings = applyExternalHintsToSystemSettings(systemSettings, hints);
      setSystemSettings(nextSettings);
      setSaveMessage("Imported missing integration secrets from env/settings.json.");
      setError(null);
    } catch (hintError) {
      setError(hintError instanceof Error ? hintError.message : String(hintError));
    } finally {
      setImportingHints(false);
    }
  }, [systemSettings]);

  const handleSave = useCallback(async (): Promise<boolean> => {
    let systemSaved = true;
    let projectSaved = true;
    const errors: string[] = [];

    if (systemDirty && systemSettings) {
      setSavingSystem(true);
      try {
        const saved = await saveSystemSettings(systemSettings);
        const normalizedSaved = normalizeSystemSettingsPayload(saved);
        setSystemSettings(cloneSystemSettings(normalizedSaved));
        setSavedSystemSettings(cloneSystemSettings(normalizedSaved));

        if (selectedProject && !projectDirty) {
          const effectiveProject = await fetchProjectEffectiveSettings(selectedProject.id, { cache: "reload" });
          const nextProject = dashboardSettingsToProjectSettings(effectiveProject.settings);
          setProjectSettings(cloneProjectSettings(nextProject));
          setSavedProjectSettings(cloneProjectSettings(nextProject));
          setProjectSources(effectiveProject.sources);
        }
      } catch (saveError) {
        errors.push(saveError instanceof Error ? saveError.message : String(saveError));
        systemSaved = false;
      } finally {
        setSavingSystem(false);
      }
    }

    if (projectDirty && selectedProject && projectSettings) {
      setSavingProject(true);
      try {
        await saveProjectSettings(selectedProject.id, projectSettings);
        const effectiveProject = await fetchProjectEffectiveSettings(selectedProject.id, { cache: "reload" });
        const nextProject = dashboardSettingsToProjectSettings(effectiveProject.settings);
        setProjectSettings(cloneProjectSettings(nextProject));
        setSavedProjectSettings(cloneProjectSettings(nextProject));
        setProjectSources(effectiveProject.sources);
      } catch (saveError) {
        errors.push(saveError instanceof Error ? saveError.message : String(saveError));
        projectSaved = false;
      } finally {
        setSavingProject(false);
      }
    }

    if (errors.length > 0) {
      setError(errors.join(" | "));
    } else {
      setError(null);
    }

    if (systemSaved && projectSaved) {
      const scopeMsg = systemDirty && projectDirty
        ? "All settings saved."
        : systemDirty
          ? "System settings saved."
          : projectDirty && selectedProject
            ? `Project settings saved for ${selectedProject.name}.`
            : "Settings saved.";
      setSaveMessage(scopeMsg);
      return true;
    }
    return false;
  }, [systemDirty, projectDirty, systemSettings, selectedProject, projectSettings]);

  const handleResetProject = useCallback(async (): Promise<void> => {
    if (!selectedProject) {
      return;
    }
    setResettingProject(true);
    try {
      await resetProjectSettings(selectedProject.id);
      const effectiveProject = await fetchProjectEffectiveSettings(selectedProject.id, { cache: "reload" });
      const nextProject = dashboardSettingsToProjectSettings(effectiveProject.settings);
      setProjectSettings(cloneProjectSettings(nextProject));
      setSavedProjectSettings(cloneProjectSettings(nextProject));
      setProjectSources(effectiveProject.sources);
      setError(null);
      setSaveMessage(`Project overrides reset for ${selectedProject.name}.`);
    } catch (resetError) {
      setError(resetError instanceof Error ? resetError.message : String(resetError));
    } finally {
      setResettingProject(false);
    }
  }, [selectedProject]);

  const handleDeleteProject = useCallback(async (): Promise<void> => {
    if (!selectedProject) {
      return;
    }


    setDeletingProject(true);
    try {
      await deleteProject(selectedProject.id);
      await setPersistedActiveScope("system");
      setActiveCategory("general");
      setSaveMessage(`Project ${selectedProject.name} deleted.`);
      setError(null);
    } catch (deleteError) {
      setError(deleteError instanceof Error ? deleteError.message : String(deleteError));
    } finally {
      setDeletingProject(false);
    }
  }, [selectedProject, deleteProject, setPersistedActiveScope]);

  const handleResetDatabase = useCallback(async (): Promise<void> => {


    setResettingDatabase(true);
    try {
      await resetSystemDatabase();
      setActiveScopeState("system");
      setActiveCategory("general");
      await loadSettings();
      setSaveMessage("Database reset to a clean state.");
      setError(null);
    } catch (resetError) {
      setError(resetError instanceof Error ? resetError.message : String(resetError));
    } finally {
      setResettingDatabase(false);
    }
  }, [loadSettings]);

  const handleClearMemory = useCallback(async (
    scope: "project" | "system",
    tier: MemoryClearTier,
  ): Promise<void> => {
    if (scope === "project" && !selectedProject) {
      return;
    }
    setMemoryClearBusy(`${scope}:${tier}`);
    try {
      const result = scope === "project"
        ? await clearProjectMemories(selectedProject!.id, tier)
        : await clearSystemMemories(tier);

      const parts = [`${result.memories} ${result.memories === 1 ? "memory" : "memories"}`];
      if (result.claims > 0) {
        parts.push(`${result.claims} ${result.claims === 1 ? "claim" : "claims"}`);
      }
      const tierLabel = tier === "short_term" ? "Short-term" : tier === "long_term" ? "Long-term" : "All";
      const scopeLabel = scope === "project" ? selectedProject!.name : "system-wide";
      setSaveMessage(`${tierLabel} memory cleared (${scopeLabel}): removed ${parts.join(", ")}.`);
      setError(null);
    } catch (clearError) {
      setError(clearError instanceof Error ? clearError.message : String(clearError));
    } finally {
      setMemoryClearBusy(null);
    }
  }, [selectedProject]);

  const createChatProviderConnectionRecord = useCallback(async (
    input: CreateChatProviderConnectionInput,
  ): Promise<DashboardChatProviderConnectionRecord | null> => {
    setChatProvidersSavingId(`connection:${input.providerKind}:create`);
    try {
      const created = await createChatProviderConnection(input);
      await loadChatProviders();
      return created;
    } catch (createError) {
      setChatProvidersError(createError instanceof Error ? createError.message : String(createError));
      return null;
    } finally {
      setChatProvidersSavingId(null);
    }
  }, [loadChatProviders]);

  const updateChatProviderConnectionRecord = useCallback(async (
    connectionId: string,
    input: UpdateChatProviderConnectionInput,
  ): Promise<DashboardChatProviderConnectionRecord | null> => {
    setChatProvidersSavingId(`connection:${connectionId}`);
    try {
      const updated = await updateChatProviderConnection(connectionId, input);
      await loadChatProviders();
      return updated;
    } catch (updateError) {
      setChatProvidersError(updateError instanceof Error ? updateError.message : String(updateError));
      return null;
    } finally {
      setChatProvidersSavingId(null);
    }
  }, [loadChatProviders]);

  const deleteChatProviderConnectionRecord = useCallback(async (connectionId: string): Promise<boolean> => {
    setChatProvidersSavingId(`connection:${connectionId}:delete`);
    try {
      await deleteChatProviderConnection(connectionId);
      await loadChatProviders();
      return true;
    } catch (deleteError) {
      setChatProvidersError(deleteError instanceof Error ? deleteError.message : String(deleteError));
      return false;
    } finally {
      setChatProvidersSavingId(null);
    }
  }, [loadChatProviders]);

  const createChatProviderBindingRecord = useCallback(async (
    input: CreateChatProviderChannelBindingInput,
  ): Promise<ChatProviderChannelBindingRecord | null> => {
    setChatProvidersSavingId(`binding:${input.providerConnectionId}:create`);
    try {
      const created = await createChatProviderChannelBinding(input);
      await loadChatProviders();
      return created;
    } catch (createError) {
      setChatProvidersError(createError instanceof Error ? createError.message : String(createError));
      return null;
    } finally {
      setChatProvidersSavingId(null);
    }
  }, [loadChatProviders]);

  const updateChatProviderBindingRecord = useCallback(async (
    bindingId: string,
    input: UpdateChatProviderChannelBindingInput,
  ): Promise<ChatProviderChannelBindingRecord | null> => {
    setChatProvidersSavingId(`binding:${bindingId}`);
    try {
      const updated = await updateChatProviderChannelBinding(bindingId, input);
      await loadChatProviders();
      return updated;
    } catch (updateError) {
      setChatProvidersError(updateError instanceof Error ? updateError.message : String(updateError));
      return null;
    } finally {
      setChatProvidersSavingId(null);
    }
  }, [loadChatProviders]);

  const deleteChatProviderBindingRecord = useCallback(async (bindingId: string): Promise<boolean> => {
    setChatProvidersSavingId(`binding:${bindingId}:delete`);
    try {
      await deleteChatProviderChannelBinding(bindingId);
      await loadChatProviders();
      return true;
    } catch (deleteError) {
      setChatProvidersError(deleteError instanceof Error ? deleteError.message : String(deleteError));
      return false;
    } finally {
      setChatProvidersSavingId(null);
    }
  }, [loadChatProviders]);

  const getValueByPath = useCallback((obj: any, path: string): any => {
    return path.split(".").reduce((acc, part) => acc && acc[part], obj);
  }, []);

  const setValueByPath = useCallback((obj: any, path: string, value: any): any => {
    const parts = path.split(".");
    const next = { ...obj };
    let current = next;
    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i]!;
      current[part] = { ...current[part] };
      current = current[part];
    }
    current[parts[parts.length - 1]!] = value;
    return next;
  }, []);

  const resetFieldToDefault = useCallback((path: string): void => {
    if (!systemSettings || !projectSettings) {
      return;
    }
    const defaultValue = getValueByPath(systemSettings.defaults, path);
    setProjectSettings((current) => {
      if (!current) return current;
      return setValueByPath(current, path, defaultValue);
    });
    setProjectSources((current) => ({
      ...current,
      [path]: "system",
    }));
  }, [systemSettings, projectSettings, getValueByPath, setValueByPath]);

  const getFieldReset = useCallback((path: string) => {
    if (activeScope === "project" && projectSources[path] === "project") {
      return () => resetFieldToDefault(path);
    }
    return undefined;
  }, [activeScope, projectSources, resetFieldToDefault]);

  const [showUnsavedModal, setShowUnsavedModal] = useState(false);
  const pendingNavigationRef = useRef<(() => void) | null>(null);
  // When the user resolves the unsaved-changes modal we navigate away on purpose.
  // That navigation must not re-trigger the native `beforeunload` prompt: in the
  // browser it would surface a second, redundant confirm dialog, and in Electron a
  // returned value silently cancels the navigation (leaving the user stuck). This
  // ref lets the beforeunload handler distinguish an intentional leave from a real
  // tab-close / hard-refresh.
  const bypassUnloadGuardRef = useRef(false);

  const runPendingNavigation = useCallback(() => {
    const navigate = pendingNavigationRef.current;
    pendingNavigationRef.current = null;
    if (navigate) {
      bypassUnloadGuardRef.current = true;
      navigate();
    }
  }, []);

  const confirmDiscard = useCallback(() => {
    setShowUnsavedModal(false);
    runPendingNavigation();
  }, [runPendingNavigation]);

  const cancelDiscard = useCallback(() => {
    setShowUnsavedModal(false);
    pendingNavigationRef.current = null;
  }, []);

  const saveAndLeave = useCallback(async () => {
    const saved = await handleSave();
    if (!saved) {
      // Keep the modal open so the user can retry, discard, or keep editing; the
      // failure reason is surfaced in the settings error panel behind the modal.
      return;
    }
    setShowUnsavedModal(false);
    runPendingNavigation();
  }, [handleSave, runPendingNavigation]);

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }

    const unregisterNavigationBlocker = registerNavigationBlocker({
      shouldBlock: () => isDirtyRef.current,
      confirmNavigation: (retry) => {
        pendingNavigationRef.current = retry;
        setShowUnsavedModal(true);
        return false;
      },
    });

    return () => {
      unregisterNavigationBlocker();
    };
  }, []);

  const activeDirty = systemDirty || projectDirty;

  useEffect(() => {
    if (typeof window === "undefined" || !activeDirty) {
      return;
    }

    const onBeforeUnload = (event: BeforeUnloadEvent): void => {
      if (bypassUnloadGuardRef.current) {
        return;
      }
      event.preventDefault();
      event.returnValue = "";
    };

    window.addEventListener("beforeunload", onBeforeUnload);
    return () => window.removeEventListener("beforeunload", onBeforeUnload);
  }, [activeDirty]);

  const activeSaving = savingSystem || savingProject;

  return {
    clearFeedback,
    activeCategory, setActiveCategory,
    activeScope, setActiveScope: setPersistedActiveScope,
    selectedIntegration, setSelectedIntegration,
    selectedAgentTemplate, setSelectedAgentTemplate,
    activeInvocationRoute, setActiveInvocationRoute,
    activeProviderPanel, setActiveProviderPanel,
    settingsSearch, setSettingsSearch,
    systemSettings,
    projectSettings,
    projectSources,
    editableSettings,
    loading, error, saveMessage,
    savingSystem, savingProject, activeSaving, activeDirty,
    resettingProject, deletingProject, resettingDatabase, memoryClearBusy, importingHints,
    externalHints,
    activeCategoryConfig, filteredCategories, settingsSearchMatches,
    categories: categories,
    providerLabels,
    thinkingModeOptions,
    invocationRouteDefinitions,
    routingProfileOptions,
    integrations: INTEGRATIONS,
    agentInstructionTemplateOptions: AGENT_INSTRUCTION_TEMPLATE_OPTIONS,
    projectAgentPresets,
    projectAgentPresetOptions,
    chatProviders: {
      definitions: chatProviderDefinitions,
      connections: chatProviderConnections,
      bindings: chatProviderBindings,
      deliveriesByConnection: chatProviderDeliveriesByConnection,
      loading: chatProvidersLoading,
      savingId: chatProvidersSavingId,
      error: chatProvidersError,
      load: loadChatProviders,
      createConnection: createChatProviderConnectionRecord,
      updateConnection: updateChatProviderConnectionRecord,
      deleteConnection: deleteChatProviderConnectionRecord,
      createBinding: createChatProviderBindingRecord,
      updateBinding: updateChatProviderBindingRecord,
      deleteBinding: deleteChatProviderBindingRecord,
    },
    selectedProject,
    projects,
    updateSystem, updateProject, updateEditableSettings,
    handleImportHints, handleSave, handleResetProject,
    handleDeleteProject, handleResetDatabase, handleClearMemory,
    loadSettings,
    isDirtyRef,
    searchInputRef,
    resetFieldToDefault,
    getFieldReset,
    showUnsavedModal, confirmDiscard, cancelDiscard, saveAndLeave
  };
};

export type SettingsPageState = ReturnType<typeof useSettingsPageState>;
export type { Category, IntegrationDefinition, CategoryId, SettingsScope, AgentInstructionTemplateId, IntegrationId };
