import type { TaskPrTemplateSections, SprintPrTemplateSections, TaskPrSectionKey, SprintPrSectionKey } from "../../../contracts/app-types.js";
import { formatCostUsd, formatDurationMs, formatIsoTimestamp, formatTokenCount, providerDisplayName } from "./pr-description-format-utils.js";

export type { TaskPrTemplateSections, SprintPrTemplateSections, TaskPrSectionKey, SprintPrSectionKey };

const FOOTER = "---\n*🤖 Generated by [Code UX](https://github.com/codeux-ai/codeux)*";

export const DEFAULT_TASK_SECTION_ORDER: TaskPrSectionKey[] = [
  "summary",
  "modelAndProvider",
  "timing",
  "tokenUsage",
  "qaFindings",
  "fullPrompt",
  "branchInfo",
];

export const DEFAULT_SPRINT_SECTION_ORDER: SprintPrSectionKey[] = [
  "summary",
  "planningModel",
  "mainPrompt",
  "taskChecklist",
  "providerBreakdown",
  "timing",
  "tokenUsage",
  "qaFindings",
  "branchInfo",
];

export interface PrUsageStats {
  invocationCount: number;
  inputTokens: number;
  cachedInputTokens: number;
  outputTokens: number;
  totalTokens: number;
  toolCallCount: number;
  activeTimeMs: number;
  /** Sum across API/billed invocations only. Null when nothing was billed. */
  costUsd: number | null;
  /**
   * Reference cost of the subscription/flat-fee usage, priced at the same catalog rate as billed
   * usage, for comparison — not an actual charge. Null when nothing ran under a subscription.
   */
  includedCostUsd: number | null;
  /** Invocations that ran via a metered API key. */
  billedInvocationCount: number;
  /** Invocations that ran via a flat-fee login (local auth / dashboard login), or any Jules invocation. */
  subscriptionInvocationCount: number;
}

export interface PrQaFinding {
  summary: string | null;
  findings: string[];
  outcome: string | null;
  reviewer: string | null;
  finishedAt: string | null;
}

export interface TaskPrComposerInput {
  taskId: string;
  taskTitle: string;
  taskPrompt: string;
  provider: string;
  model: string | null;
  sprintGoal?: string | null;
  sprintNumber?: number | null;
  sprintName?: string | null;
  featureBranch: string;
  workerBranch: string;
  startedAt: string | null;
  finishedAt: string | null;
  durationMs: number | null;
  usage: PrUsageStats | null;
  /** null => QA has not run yet at PR-creation time; render a pending placeholder. */
  qa: PrQaFinding | null;
  sections: TaskPrTemplateSections;
  /** Display order for enabled sections. Unknown/duplicate keys are dropped; missing known keys are appended. */
  sectionOrder?: TaskPrSectionKey[];
}

export interface SprintPrSubtaskSummary {
  id: string;
  title: string;
  provider?: string | null;
  model?: string | null;
  prUrl?: string | null;
  completed: boolean;
}

export interface SprintPrLinkedIssueSummary {
  provider: "github" | "gitlab" | "jira";
  issueKey?: string | null;
  issueNumber?: number | null;
  title: string;
  url?: string | null;
}

export interface SprintPrComposerInput {
  sprintId: string;
  sprintNumber?: number | null;
  sprintName?: string | null;
  sprintGoal: string;
  sprintOriginalPrompt?: string | null;
  defaultBranch: string;
  featureBranch: string;
  subtasks: SprintPrSubtaskSummary[];
  linkedIssues?: SprintPrLinkedIssueSummary[];
  planning: { provider: string | null; model: string | null; usage: PrUsageStats | null } | null;
  aggregateUsage: PrUsageStats | null;
  startedAt: string | null;
  finishedAt: string | null;
  qa: PrQaFinding | null;
  sections: SprintPrTemplateSections;
  /** Display order for enabled sections. Unknown/duplicate keys are dropped; missing known keys are appended. */
  sectionOrder?: SprintPrSectionKey[];
}

function sprintLabel(sprintNumber?: number | null, sprintName?: string | null): string {
  if (sprintName && sprintNumber != null) return `Sprint ${sprintNumber} · ${sprintName}`;
  if (sprintName) return sprintName;
  if (sprintNumber != null) return `Sprint ${sprintNumber}`;
  return "this sprint";
}

function renderFindingsList(findings: string[]): string {
  const items = findings.map((f) => `- ${f}`).join("\n");
  if (findings.length > 3) {
    return `<details>\n<summary>${findings.length} findings</summary>\n\n${items}\n</details>`;
  }
  return items;
}

function renderQaBlock(qa: PrQaFinding | null, pendingMessage: string): string {
  if (!qa) return pendingMessage;

  const lines: string[] = [];
  if (qa.outcome) lines.push(`**Outcome:** ${qa.outcome}`);
  if (qa.summary) lines.push(qa.summary.trim());
  if (qa.findings.length > 0) lines.push(renderFindingsList(qa.findings));
  if (lines.length === 0) lines.push("No findings recorded.");
  return lines.join("\n\n");
}

function renderUsageBlock(usage: PrUsageStats | null, heading: string): string {
  if (!usage || usage.invocationCount === 0) {
    return `${heading ? `${heading}\n\n` : ""}_No usage data recorded._`;
  }

  const rows: string[] = [
    "| Metric | Value |",
    "|---|---|",
    `| Input tokens | ${formatTokenCount(usage.inputTokens)} |`,
    `| Cached input tokens | ${formatTokenCount(usage.cachedInputTokens)} |`,
    `| Output tokens | ${formatTokenCount(usage.outputTokens)} |`,
    `| Total tokens | ${formatTokenCount(usage.totalTokens)} |`,
    `| Invocations | ${formatTokenCount(usage.invocationCount)} |`,
    `| Tool calls | ${formatTokenCount(usage.toolCallCount)} |`,
    `| Active time | ${formatDurationMs(usage.activeTimeMs)} |`,
  ];

  const billedCostLabel = formatCostUsd(usage.costUsd);
  const includedCostLabel = formatCostUsd(usage.includedCostUsd);
  const totalCostUsd = (usage.costUsd ?? 0) + (usage.includedCostUsd ?? 0);
  const totalCostLabel = formatCostUsd(totalCostUsd);

  const noteLines: string[] = [];
  if (usage.billedInvocationCount > 0 && billedCostLabel) {
    noteLines.push(`**Estimated metered cost (API-billed):** ${billedCostLabel}`);
  }
  if (usage.subscriptionInvocationCount > 0 && includedCostLabel) {
    noteLines.push(`**Included usage estimate (subscription/local login):** ${includedCostLabel}`);
  }
  if (billedCostLabel && includedCostLabel && totalCostLabel) {
    noteLines.push(`**Reference total (metered + included estimate):** ${totalCostLabel}`);
  }
  const parts = [rows.join("\n")];
  if (noteLines.length > 0) parts.push(noteLines.join("\n"));

  return `${heading ? `${heading}\n\n` : ""}${parts.join("\n\n")}`;
}

/** Filters to known keys, dedupes, then appends any known keys missing from `order` (new sections, or a stale/partial saved order). */
export function resolveSectionOrder<K extends string>(order: K[] | undefined, defaultOrder: K[]): K[] {
  const known = new Set(defaultOrder);
  const seen = new Set<K>();
  const resolved: K[] = [];
  for (const key of order ?? []) {
    if (known.has(key) && !seen.has(key)) {
      resolved.push(key);
      seen.add(key);
    }
  }
  for (const key of defaultOrder) {
    if (!seen.has(key)) {
      resolved.push(key);
      seen.add(key);
    }
  }
  return resolved;
}

const TASK_SECTION_RENDERERS: Record<TaskPrSectionKey, (input: TaskPrComposerInput) => string> = {
  summary: (input) => {
    const lines = [`**Sprint:** ${sprintLabel(input.sprintNumber, input.sprintName)}  ·  **Task:** \`${input.taskId}\``];
    if (input.sprintGoal?.trim()) {
      lines.push(`> ${input.sprintGoal.trim().replace(/\n+/g, "\n> ")}`);
    }
    return `### 📋 Summary\n${lines.join("\n\n")}`;
  },
  modelAndProvider: (input) => (
    `### 🤖 Model & Provider\n\n| | |\n|---|---|\n| Provider | ${providerDisplayName(input.provider)} |\n| Model | \`${input.model || "unknown"}\` |`
  ),
  timing: (input) => (
    `### ⏱️ Timing\n\n| | |\n|---|---|\n| Started | ${formatIsoTimestamp(input.startedAt)} |\n| Finished | ${formatIsoTimestamp(input.finishedAt)} |\n| Duration | ${formatDurationMs(input.durationMs)} |`
  ),
  tokenUsage: (input) => renderUsageBlock(input.usage, "### 📊 Token Usage"),
  qaFindings: (input) => {
    const qaBody = renderQaBlock(
      input.qa,
      "⏳ QA review runs after this PR is opened. Check the task card in the dashboard for the outcome once it lands.",
    );
    return `### ✅ QA Review\n\n${qaBody}`;
  },
  fullPrompt: (input) => `<details>\n<summary>📝 Full Task Prompt</summary>\n\n\`\`\`\n${input.taskPrompt}\n\`\`\`\n</details>`,
  branchInfo: (input) => `<details>\n<summary>🌿 Branch Info</summary>\n\nBase: \`${input.featureBranch}\`\nHead: \`${input.workerBranch}\`\n</details>`,
};

function sprintProviderStatsLine(subtasks: SprintPrSubtaskSummary[]): string {
  const providerCounts = new Map<string, number>();
  for (const task of subtasks) {
    if (!task.provider) continue;
    providerCounts.set(task.provider, (providerCounts.get(task.provider) || 0) + 1);
  }
  return Array.from(providerCounts.entries())
    .map(([provider, count]) => `${count} by ${provider}`)
    .join(" · ");
}

function linkedIssueProviderLabel(provider: SprintPrLinkedIssueSummary["provider"]): string {
  if (provider === "github") return "GitHub";
  if (provider === "gitlab") return "GitLab";
  return "Jira";
}

function linkedIssueReference(issue: SprintPrLinkedIssueSummary): string {
  const explicitKey = issue.issueKey?.trim();
  if (explicitKey) return explicitKey;
  if (issue.issueNumber != null) {
    if (issue.provider === "github") return `#${issue.issueNumber}`;
    if (issue.provider === "gitlab") return `!${issue.issueNumber}`;
    return String(issue.issueNumber);
  }
  return "Issue";
}

function renderLinkedIssuesBlock(issues: SprintPrLinkedIssueSummary[] | undefined): string | null {
  const normalized = (issues || []).filter((issue) => issue.title.trim() || issue.issueKey?.trim() || issue.url?.trim());
  if (normalized.length === 0) return null;

  const lines = normalized.map((issue) => {
    const provider = linkedIssueProviderLabel(issue.provider);
    const reference = linkedIssueReference(issue);
    const linkedReference = issue.url?.trim() ? `[${reference}](${issue.url.trim()})` : reference;
    const title = issue.title.trim() || "Untitled issue";
    return `- **${provider}** ${linkedReference}: ${title}`;
  });

  return `### 🔗 Linked Issues\n\n${lines.join("\n")}`;
}

const SPRINT_SECTION_RENDERERS: Record<SprintPrSectionKey, (input: SprintPrComposerInput) => string | null> = {
  summary: (input) => {
    const completedCount = input.subtasks.filter((t) => t.completed).length;
    const label = sprintLabel(input.sprintNumber, input.sprintName);
    const summary = `### 📋 Summary\n**Sprint:** ${label}   **Tasks:** ${completedCount}/${input.subtasks.length} completed`;
    const linkedIssues = renderLinkedIssuesBlock(input.linkedIssues);
    return linkedIssues ? `${summary}\n\n${linkedIssues}` : summary;
  },
  planningModel: (input) => {
    if (!input.planning) {
      return "### 🧭 Planning\n\n_No planning invocation recorded for this sprint._";
    }
    const planningLines = [
      "| | |",
      "|---|---|",
      `| Planning provider | ${providerDisplayName(input.planning.provider)} |`,
      `| Planning model | \`${input.planning.model || "unknown"}\` |`,
    ].join("\n");
    const planningUsage = input.planning.usage ? `\n\n${renderUsageBlock(input.planning.usage, "")}` : "";
    return `### 🧭 Planning\n\n${planningLines}${planningUsage}`;
  },
  mainPrompt: (input) => {
    const prompt = input.sprintOriginalPrompt?.trim() || input.sprintGoal?.trim() || "No prompt recorded.";
    return `<details>\n<summary>🎯 Original Sprint Prompt</summary>\n\n${prompt}\n</details>`;
  },
  taskChecklist: (input) => {
    const checklist = input.subtasks
      .map((task) => {
        const checkbox = task.completed ? "[x]" : "[ ]";
        const providerStr = task.provider ? ` — \`${task.provider}\`` : "";
        const prStr = task.prUrl ? ` ([PR](${task.prUrl}))` : "";
        return `- ${checkbox} **${task.id}**: ${task.title}${providerStr}${prStr}`;
      })
      .join("\n");
    return `### ✅ Task Checklist\n\n${checklist}`;
  },
  providerBreakdown: (input) => {
    const providerStatsLine = sprintProviderStatsLine(input.subtasks);
    return providerStatsLine ? `### 👥 Provider Breakdown\n\n${providerStatsLine}` : null;
  },
  timing: (input) => (
    `### ⏱️ Sprint Timing\n\n| | |\n|---|---|\n| Started | ${formatIsoTimestamp(input.startedAt)} |\n| Finished | ${formatIsoTimestamp(input.finishedAt)} |\n| Duration | ${formatDurationMs(
      input.startedAt && input.finishedAt ? new Date(input.finishedAt).getTime() - new Date(input.startedAt).getTime() : null,
    )} |`
  ),
  tokenUsage: (input) => renderUsageBlock(input.aggregateUsage, "### 📊 Aggregate CLI Token Usage"),
  qaFindings: (input) => {
    const qaBody = renderQaBlock(input.qa, "_Sprint completion did not run a QA review._");
    return `### 🕵️ QA Review Summary\n\n${qaBody}`;
  },
  branchInfo: (input) => `<details>\n<summary>🌿 Branch Info</summary>\n\nBase: \`${input.defaultBranch}\`\nHead: \`${input.featureBranch}\`\n</details>`,
};

export function composeTaskPrTitle(input: Pick<TaskPrComposerInput, "taskTitle" | "provider">): string {
  return `${input.taskTitle} (${input.provider})`;
}

export function composeSprintPrTitle(
  input: Pick<SprintPrComposerInput, "sprintNumber" | "sprintName" | "featureBranch" | "defaultBranch">,
): string {
  const label = input.sprintName
    ? `Sprint ${input.sprintNumber ?? "?"}: ${input.sprintName}`
    : `Sprint ${input.sprintNumber ?? "?"}`;
  return `${label} — merge ${input.featureBranch} into ${input.defaultBranch}`;
}

export function composeTaskPrBody(input: TaskPrComposerInput): string {
  const order = resolveSectionOrder(input.sectionOrder, DEFAULT_TASK_SECTION_ORDER);
  const parts: string[] = [`## 🧩 Task: ${input.taskTitle}\n> Automated task PR opened by Code UX for \`${input.taskId}\`.`];

  for (const key of order) {
    if (!input.sections[key]) continue;
    parts.push(TASK_SECTION_RENDERERS[key](input));
  }

  parts.push(FOOTER);
  return parts.join("\n\n");
}

export function composeSprintPrBody(input: SprintPrComposerInput): string {
  const order = resolveSectionOrder(input.sectionOrder, DEFAULT_SPRINT_SECTION_ORDER);
  const label = sprintLabel(input.sprintNumber, input.sprintName);
  const parts: string[] = [`## 🚀 Sprint Completion: ${label}\n> Automated sprint completion PR opened by Code UX.`];

  for (const key of order) {
    if (!input.sections[key]) continue;
    const rendered = SPRINT_SECTION_RENDERERS[key](input);
    if (rendered) parts.push(rendered);
  }

  parts.push(FOOTER);
  return parts.join("\n\n");
}
