import type { FunctionComponent } from "preact";
import { updateCiIntelligence } from "../../lib/settings-updaters.js";
import { SettingsCard, ToggleRow } from "./primitives.js";
import type { SettingsSectionProps } from "./types.js";

export const CiIntelligenceSection: FunctionComponent<SettingsSectionProps> = ({ settings, onChange }) => (
  <SettingsCard
    title="CI Intelligence"
    description="Controls protocol checks generated by the sprint loop for feature branch and main branch merge stages."
  >
    <ToggleRow
      label="Enable CI Intelligence"
      checked={settings.ciIntelligence.enabled}
      onToggle={(checked) =>
        onChange(updateCiIntelligence(settings, {
          enabled: checked,
        }))
      }
    />
    <ToggleRow
      label="Enable Live PR Monitoring"
      checked={settings.ciIntelligence.enableLivePrMonitoring}
      disabled={!settings.ciIntelligence.enabled || settings.git.githubMode === "LOCAL"}
      onToggle={(checked) =>
        onChange(updateCiIntelligence(settings, {
          enableLivePrMonitoring: checked,
        }))
      }
    />
    <ToggleRow
      label="Wait for CI before merge into main"
      checked={settings.ciIntelligence.waitForCiBeforeMainMerge}
      disabled={!settings.ciIntelligence.enabled}
      onToggle={(checked) =>
        onChange(updateCiIntelligence(settings, {
          waitForCiBeforeMainMerge: checked,
        }))
      }
    />
    <ToggleRow
      label="Resolve all comments before merge into main"
      checked={settings.ciIntelligence.resolveAllCommentsBeforeMainMerge}
      disabled={!settings.ciIntelligence.enabled}
      onToggle={(checked) =>
        onChange(updateCiIntelligence(settings, {
          resolveAllCommentsBeforeMainMerge: checked,
        }))
      }
    />
    <ToggleRow
      label="Wait for CI before merge into feature branch"
      checked={settings.ciIntelligence.waitForCiBeforeFeatureMerge}
      disabled={!settings.ciIntelligence.enabled}
      onToggle={(checked) =>
        onChange(updateCiIntelligence(settings, {
          waitForCiBeforeFeatureMerge: checked,
        }))
      }
    />
    <ToggleRow
      label="Resolve all comments before merge into feature branch"
      checked={settings.ciIntelligence.resolveAllCommentsBeforeFeatureMerge}
      disabled={!settings.ciIntelligence.enabled}
      onToggle={(checked) =>
        onChange(updateCiIntelligence(settings, {
          resolveAllCommentsBeforeFeatureMerge: checked,
        }))
      }
    />
    <ToggleRow
      label="Wait for Jules CI Autofix on feature PRs"
      checked={settings.ciIntelligence.waitForJulesCiAutofix}
      disabled={!settings.ciIntelligence.enabled || !settings.ciIntelligence.waitForCiBeforeFeatureMerge}
      onToggle={(checked) =>
        onChange(updateCiIntelligence(settings, {
          waitForJulesCiAutofix: checked,
        }))
      }
    />
    <label className="block space-y-2 rounded-lg border border-slate-700/70 bg-slate-950/50 px-3 py-2">
      <span className="text-sm text-slate-200">Jules CI Autofix Max Retries</span>
      <input
        type="number"
        min={0}
        max={20}
        value={settings.ciIntelligence.julesCiAutofixMaxRetries}
        disabled={!settings.ciIntelligence.enabled || !settings.ciIntelligence.waitForJulesCiAutofix}
        onInput={(event) =>
          onChange(updateCiIntelligence(settings, {
            julesCiAutofixMaxRetries: Number(event.currentTarget.value),
          }))
        }
        className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-200 focus:outline-none focus:ring-2 focus:ring-sky-500/50 disabled:opacity-50"
      />
      <p className="text-[11px] text-slate-500">
        After this many failed CI autofix attempts, escalation is raised with exact task IDs and PR links.
      </p>
    </label>
    <label className="block space-y-2 rounded-lg border border-slate-700/70 bg-slate-950/50 px-3 py-2">
      <span className="text-sm text-slate-200">Feature PR Auto-merge Policy</span>
      <select
        value={settings.ciIntelligence.featurePrAutoMergeMode}
        disabled={!settings.ciIntelligence.enabled}
        onChange={(event) =>
          onChange(updateCiIntelligence(settings, {
            featurePrAutoMergeMode: event.currentTarget.value as typeof settings.ciIntelligence.featurePrAutoMergeMode,
          }))
        }
        className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-200 focus:outline-none focus:ring-2 focus:ring-sky-500/50 disabled:opacity-50"
      >
        <option value="OFF">Disabled</option>
        <option value="WHEN_GREEN">When CI and review are clear</option>
        <option value="ALWAYS">Always attempt auto-merge</option>
      </select>
      <p className="text-[11px] text-slate-500">
        Choose whether feature PR auto-merge is disabled, gated on green checks, or always attempted.
      </p>
    </label>
  </SettingsCard>
);
