import { describe, expect, it } from "vitest";
import {
  composeTaskPrBody,
  composeTaskPrTitle,
  composeSprintPrBody,
  composeSprintPrTitle,
  resolveSectionOrder,
  DEFAULT_TASK_SECTION_ORDER,
  DEFAULT_SPRINT_SECTION_ORDER,
  type TaskPrComposerInput,
  type SprintPrComposerInput,
} from "../../../../../src/domain/sprint/composer/pr-description-composer.js";

const ALL_TASK_SECTIONS_ON: TaskPrComposerInput["sections"] = {
  summary: true,
  modelAndProvider: true,
  timing: true,
  fullPrompt: true,
  tokenUsage: true,
  qaFindings: true,
  branchInfo: true,
};

const ALL_SPRINT_SECTIONS_ON: SprintPrComposerInput["sections"] = {
  summary: true,
  taskChecklist: true,
  providerBreakdown: true,
  planningModel: true,
  mainPrompt: true,
  timing: true,
  tokenUsage: true,
  qaFindings: true,
  branchInfo: true,
};

const baseTaskInput: TaskPrComposerInput = {
  taskId: "task-1",
  taskTitle: "Add rate limiting",
  taskPrompt: "Implement a token bucket rate limiter for the webhook endpoint.",
  provider: "claude-code",
  model: "claude-opus-4-6",
  sprintGoal: "Improve webhook reliability",
  sprintNumber: 3,
  sprintName: "Webhook Reliability",
  featureBranch: "sprint/3-webhook",
  workerBranch: "sprint/3-webhook/task-1",
  startedAt: "2026-07-01T10:00:00.000Z",
  finishedAt: "2026-07-01T10:14:00.000Z",
  durationMs: 14 * 60 * 1000,
  usage: {
    invocationCount: 2,
    inputTokens: 10000,
    cachedInputTokens: 2000,
    outputTokens: 3000,
    totalTokens: 15000,
    toolCallCount: 12,
    activeTimeMs: 14 * 60 * 1000,
    costUsd: 0.42,
    includedCostUsd: null,
    billedInvocationCount: 2,
    subscriptionInvocationCount: 0,
  },
  qa: {
    summary: "Looks good overall.",
    findings: ["Minor: missing a test for the boundary case."],
    outcome: "pass",
    reviewer: "qa-agent",
    finishedAt: "2026-07-01T10:20:00.000Z",
  },
  sections: ALL_TASK_SECTIONS_ON,
};

const baseSprintInput: SprintPrComposerInput = {
  sprintId: "sprint-3",
  sprintNumber: 3,
  sprintName: "Webhook Reliability",
  sprintGoal: "Improve webhook reliability",
  sprintOriginalPrompt: "Build a rate-limited webhook ingestion pipeline.",
  defaultBranch: "main",
  featureBranch: "sprint/3-webhook",
  subtasks: [
    { id: "task-1", title: "Add rate limiting", provider: "claude-code", model: "claude-opus-4-6", prUrl: "https://github.com/x/y/pull/1", completed: true },
    { id: "task-2", title: "Add retry queue", provider: "codex", model: "gpt-6-codex", completed: false },
  ],
  linkedIssues: [],
  planning: {
    provider: "claude-code",
    model: "claude-opus-4-6",
    usage: {
      invocationCount: 1,
      inputTokens: 4000,
      cachedInputTokens: 500,
      outputTokens: 1200,
      totalTokens: 5200,
      toolCallCount: 2,
      activeTimeMs: 30000,
      costUsd: 0.1,
      includedCostUsd: null,
      billedInvocationCount: 1,
      subscriptionInvocationCount: 0,
    },
  },
  aggregateUsage: {
    invocationCount: 6,
    inputTokens: 50000,
    cachedInputTokens: 8000,
    outputTokens: 15000,
    totalTokens: 65000,
    toolCallCount: 40,
    activeTimeMs: 3600000,
    costUsd: 1.8,
    includedCostUsd: 0.35,
    billedInvocationCount: 4,
    subscriptionInvocationCount: 2,
  },
  startedAt: "2026-07-01T09:00:00.000Z",
  finishedAt: "2026-07-01T11:00:00.000Z",
  qa: {
    summary: "Sprint reviewed, no blockers.",
    findings: ["Consider adding an alert for repeated dead-letter entries."],
    outcome: "pass",
    reviewer: "qa-agent",
    finishedAt: "2026-07-01T11:05:00.000Z",
  },
  sections: ALL_SPRINT_SECTIONS_ON,
};

describe("composeTaskPrBody", () => {
  it("includes every section header when all sections are enabled", () => {
    const body = composeTaskPrBody(baseTaskInput);
    expect(body).toContain("## 🧩 Task: Add rate limiting");
    expect(body).toContain("### 📋 Summary");
    expect(body).toContain("### 🤖 Model & Provider");
    expect(body).toContain("### ⏱️ Timing");
    expect(body).toContain("### 📊 Token Usage");
    expect(body).toContain("### ✅ QA Review");
    expect(body).toContain("📝 Full Task Prompt");
    expect(body).toContain("🌿 Branch Info");
    expect(body).toContain("Generated by [Code UX]");
  });

  it("always renders the full prompt inside a collapsed <details> block", () => {
    const body = composeTaskPrBody(baseTaskInput);
    const detailsMatch = body.match(/<details>\n<summary>📝 Full Task Prompt<\/summary>\n\n```\n([\s\S]*?)\n```\n<\/details>/);
    expect(detailsMatch).not.toBeNull();
    expect(detailsMatch![1]).toContain(baseTaskInput.taskPrompt);
    // The prompt text must not appear outside of the collapsed block.
    const withoutDetails = body.replace(/<details>[\s\S]*?<\/details>/g, "");
    expect(withoutDetails).not.toContain(baseTaskInput.taskPrompt);
  });

  for (const key of Object.keys(ALL_TASK_SECTIONS_ON) as Array<keyof TaskPrComposerInput["sections"]>) {
    it(`omits only the ${key} section when it is toggled off`, () => {
      const withAllOn = composeTaskPrBody(baseTaskInput);
      const withOneOff = composeTaskPrBody({
        ...baseTaskInput,
        sections: { ...ALL_TASK_SECTIONS_ON, [key]: false },
      });
      expect(withOneOff.length).toBeLessThan(withAllOn.length);

      const headingByKey: Record<string, string> = {
        summary: "### 📋 Summary",
        modelAndProvider: "### 🤖 Model & Provider",
        timing: "### ⏱️ Timing",
        fullPrompt: "📝 Full Task Prompt",
        tokenUsage: "### 📊 Token Usage",
        qaFindings: "### ✅ QA Review",
        branchInfo: "🌿 Branch Info",
      };
      expect(withOneOff).not.toContain(headingByKey[key]);
    });
  }

  it("renders a graceful pending placeholder when QA has not run yet", () => {
    const body = composeTaskPrBody({ ...baseTaskInput, qa: null });
    expect(body).toContain("⏳ QA review runs after this PR is opened");
  });

  it("renders a graceful message when usage is null", () => {
    const body = composeTaskPrBody({ ...baseTaskInput, usage: null });
    expect(body).toContain("No usage data recorded");
    expect(body).not.toContain("undefined");
    expect(body).not.toContain("NaN");
  });

  it("omits the metered cost line and billing notice but keeps token counts when nothing was billed", () => {
    const body = composeTaskPrBody({
      ...baseTaskInput,
      usage: {
        ...baseTaskInput.usage!,
        costUsd: null,
        billedInvocationCount: 0,
        subscriptionInvocationCount: 2,
      },
    });
    expect(body).not.toContain("Est. cost");
    expect(body).not.toContain("ran via subscription/local login");
    expect(body).not.toContain("not billed separately");
    expect(body).toContain("Total tokens");
  });

  it("shows metered, included estimate, and reference total rows when usage is a mix of billed and subscription", () => {
    const body = composeTaskPrBody({
      ...baseTaskInput,
      usage: {
        ...baseTaskInput.usage!,
        costUsd: 0.42,
        includedCostUsd: 0.1,
        billedInvocationCount: 2,
        subscriptionInvocationCount: 1,
      },
    });
    expect(body).toContain("**Estimated metered cost (API-billed):** $0.42");
    expect(body).toContain("**Included usage estimate (subscription/local login):** $0.10");
    expect(body).toContain("**Reference total (metered + included estimate):** $0.52");
  });

  it("shows only the included estimate, no reference total row, when usage is entirely subscription-priced", () => {
    const body = composeTaskPrBody({
      ...baseTaskInput,
      usage: {
        ...baseTaskInput.usage!,
        costUsd: null,
        includedCostUsd: 0.25,
        billedInvocationCount: 0,
        subscriptionInvocationCount: 2,
      },
    });
    expect(body).not.toContain("Est. cost");
    expect(body).toContain("**Included usage estimate (subscription/local login):** $0.25");
    expect(body).not.toContain("Total cost");
  });
});

describe("composeSprintPrBody", () => {
  it("includes every section header when all sections are enabled", () => {
    const body = composeSprintPrBody(baseSprintInput);
    expect(body).toContain("## 🚀 Sprint Completion");
    expect(body).toContain("### 📋 Summary");
    expect(body).toContain("### 🧭 Planning");
    expect(body).toContain("🎯 Original Sprint Prompt");
    expect(body).toContain("### ✅ Task Checklist");
    expect(body).toContain("### 👥 Provider Breakdown");
    expect(body).toContain("### ⏱️ Sprint Timing");
    expect(body).toContain("### 📊 Aggregate CLI Token Usage");
    expect(body).toContain("### 🕵️ QA Review Summary");
    expect(body).toContain("🌿 Branch Info");
  });

  it("always renders the original prompt inside a collapsed <details> block", () => {
    const body = composeSprintPrBody(baseSprintInput);
    expect(body).toMatch(/<details>\n<summary>🎯 Original Sprint Prompt<\/summary>\n\n[\s\S]*?<\/details>/);
    const withoutDetails = body.replace(/<details>[\s\S]*?<\/details>/g, "");
    expect(withoutDetails).not.toContain(baseSprintInput.sprintOriginalPrompt);
  });

  it("falls back to the sprint goal when there is no original prompt", () => {
    const body = composeSprintPrBody({ ...baseSprintInput, sprintOriginalPrompt: null });
    expect(body).toContain(baseSprintInput.sprintGoal);
  });

  it("renders the task checklist with checkboxes and PR links", () => {
    const body = composeSprintPrBody(baseSprintInput);
    expect(body).toContain("- [x] **task-1**: Add rate limiting — `claude-code` ([PR](https://github.com/x/y/pull/1))");
    expect(body).toContain("- [ ] **task-2**: Add retry queue — `codex`");
  });

  it("omits the linked issues section when the sprint has no linked issues", () => {
    const body = composeSprintPrBody(baseSprintInput);
    expect(body).not.toContain("### 🔗 Linked Issues");
  });

  it("renders every linked Jira ticket with the stored Jira URL", () => {
    const body = composeSprintPrBody({
      ...baseSprintInput,
      linkedIssues: [
        {
          provider: "jira",
          issueKey: "OPS-123",
          issueNumber: 123,
          title: "Fix import status copy",
          url: "https://jira.example.test/browse/OPS-123",
        },
        {
          provider: "jira",
          issueKey: "OPS-124",
          issueNumber: 124,
          title: "Clarify completion handoff",
          url: "https://jira.example.test/browse/OPS-124",
        },
      ],
    });

    expect(body).toContain("### 🔗 Linked Issues");
    expect(body).toContain("- **Jira** [OPS-123](https://jira.example.test/browse/OPS-123): Fix import status copy");
    expect(body).toContain("- **Jira** [OPS-124](https://jira.example.test/browse/OPS-124): Clarify completion handoff");
  });

  it("renders mixed Jira, GitHub, and GitLab linked issues", () => {
    const body = composeSprintPrBody({
      ...baseSprintInput,
      linkedIssues: [
        {
          provider: "jira",
          issueKey: "OPS-123",
          issueNumber: 123,
          title: "Fix import status copy",
          url: "https://jira.example.test/browse/OPS-123",
        },
        {
          provider: "github",
          issueKey: "#42",
          issueNumber: 42,
          title: "Restore completion note",
          url: "https://github.example.test/example/app/issues/42",
        },
        {
          provider: "gitlab",
          issueKey: "!7",
          issueNumber: 7,
          title: "Tighten merge gate wording",
          url: "https://gitlab.example.test/example/app/-/issues/7",
        },
      ],
    });

    expect(body).toContain("- **Jira** [OPS-123](https://jira.example.test/browse/OPS-123): Fix import status copy");
    expect(body).toContain("- **GitHub** [#42](https://github.example.test/example/app/issues/42): Restore completion note");
    expect(body).toContain("- **GitLab** [!7](https://gitlab.example.test/example/app/-/issues/7): Tighten merge gate wording");
  });

  for (const key of Object.keys(ALL_SPRINT_SECTIONS_ON) as Array<keyof SprintPrComposerInput["sections"]>) {
    it(`omits only the ${key} section when it is toggled off`, () => {
      const withAllOn = composeSprintPrBody(baseSprintInput);
      const withOneOff = composeSprintPrBody({
        ...baseSprintInput,
        sections: { ...ALL_SPRINT_SECTIONS_ON, [key]: false },
      });
      expect(withOneOff.length).toBeLessThan(withAllOn.length);

      const headingByKey: Record<string, string> = {
        summary: "### 📋 Summary",
        taskChecklist: "### ✅ Task Checklist",
        providerBreakdown: "### 👥 Provider Breakdown",
        planningModel: "### 🧭 Planning",
        mainPrompt: "🎯 Original Sprint Prompt",
        timing: "### ⏱️ Sprint Timing",
        tokenUsage: "### 📊 Aggregate CLI Token Usage",
        qaFindings: "### 🕵️ QA Review Summary",
        branchInfo: "🌿 Branch Info",
      };
      expect(withOneOff).not.toContain(headingByKey[key]);
    });
  }

  it("renders a graceful message when there was no planning invocation", () => {
    const body = composeSprintPrBody({ ...baseSprintInput, planning: null });
    expect(body).toContain("No planning invocation recorded");
  });

  it("renders a graceful fallback when there was no QA review", () => {
    const body = composeSprintPrBody({ ...baseSprintInput, qa: null });
    expect(body).toContain("did not run a QA review");
  });

  it("omits all cost lines when aggregate usage was entirely subscription-based with no known pricing", () => {
    const body = composeSprintPrBody({
      ...baseSprintInput,
      planning: null,
      aggregateUsage: {
        ...baseSprintInput.aggregateUsage!,
        costUsd: null,
        includedCostUsd: null,
        billedInvocationCount: 0,
        subscriptionInvocationCount: 6,
      },
    });
    expect(body).not.toContain("Est. cost");
    expect(body).not.toContain("Included cost");
    expect(body).not.toContain("Total cost");
    expect(body).not.toContain("ran via subscription/local login");
    expect(body).not.toContain("not billed separately");
  });

  it("shows metered, included estimate, and reference total rows for the aggregate sprint usage mix", () => {
    const body = composeSprintPrBody(baseSprintInput);
    expect(body).toContain("**Estimated metered cost (API-billed):** $1.80");
    expect(body).toContain("**Included usage estimate (subscription/local login):** $0.35");
    expect(body).toContain("**Reference total (metered + included estimate):** $2.15");
  });
});

describe("composeTaskPrTitle", () => {
  it("formats as '<title> (<provider>)'", () => {
    expect(composeTaskPrTitle({ taskTitle: "Add rate limiting", provider: "claude-code" })).toBe("Add rate limiting (claude-code)");
  });
});

describe("composeSprintPrTitle", () => {
  it("includes the sprint number and name when both are present", () => {
    const title = composeSprintPrTitle({
      sprintNumber: 3,
      sprintName: "Webhook Reliability",
      featureBranch: "sprint/3-webhook",
      defaultBranch: "main",
    });
    expect(title).toBe("Sprint 3: Webhook Reliability — merge sprint/3-webhook into main");
  });

  it("falls back to a bare sprint number when there is no name", () => {
    const title = composeSprintPrTitle({
      sprintNumber: 5,
      sprintName: null,
      featureBranch: "sprint/5-x",
      defaultBranch: "main",
    });
    expect(title).toBe("Sprint 5 — merge sprint/5-x into main");
  });
});

describe("resolveSectionOrder", () => {
  it("returns the default order when no order is given", () => {
    expect(resolveSectionOrder(undefined, DEFAULT_TASK_SECTION_ORDER)).toEqual(DEFAULT_TASK_SECTION_ORDER);
  });

  it("preserves a valid custom order as-is", () => {
    const custom = ["branchInfo", "summary", "tokenUsage", "modelAndProvider", "timing", "qaFindings", "fullPrompt"];
    expect(resolveSectionOrder(custom, DEFAULT_TASK_SECTION_ORDER)).toEqual(custom);
  });

  it("drops unknown keys and de-duplicates", () => {
    const result = resolveSectionOrder(["summary", "bogus", "summary", "timing"], DEFAULT_TASK_SECTION_ORDER);
    expect(result).not.toContain("bogus");
    expect(result.filter((k) => k === "summary")).toHaveLength(1);
  });

  it("appends known keys missing from a partial/stale saved order", () => {
    const result = resolveSectionOrder(["timing", "summary"], DEFAULT_TASK_SECTION_ORDER);
    expect(result.slice(0, 2)).toEqual(["timing", "summary"]);
    expect(new Set(result)).toEqual(new Set(DEFAULT_TASK_SECTION_ORDER));
  });
});

describe("section reordering", () => {
  it("composeTaskPrBody renders enabled sections in the given sectionOrder", () => {
    const body = composeTaskPrBody({
      ...baseTaskInput,
      sectionOrder: ["branchInfo", "modelAndProvider", "summary"],
      sections: { ...ALL_TASK_SECTIONS_ON, timing: false, fullPrompt: false, tokenUsage: false, qaFindings: false },
    });
    const branchIndex = body.indexOf("🌿 Branch Info");
    const modelIndex = body.indexOf("### 🤖 Model & Provider");
    const summaryIndex = body.indexOf("### 📋 Summary");
    expect(branchIndex).toBeGreaterThan(-1);
    expect(modelIndex).toBeGreaterThan(branchIndex);
    expect(summaryIndex).toBeGreaterThan(modelIndex);
  });

  it("composeSprintPrBody renders enabled sections in the given sectionOrder", () => {
    const body = composeSprintPrBody({
      ...baseSprintInput,
      sectionOrder: ["qaFindings", "taskChecklist", "summary"],
      sections: { ...ALL_SPRINT_SECTIONS_ON, planningModel: false, mainPrompt: false, providerBreakdown: false, timing: false, tokenUsage: false, branchInfo: false },
    });
    const qaIndex = body.indexOf("### 🕵️ QA Review Summary");
    const checklistIndex = body.indexOf("### ✅ Task Checklist");
    const summaryIndex = body.indexOf("### 📋 Summary");
    expect(qaIndex).toBeGreaterThan(-1);
    expect(checklistIndex).toBeGreaterThan(qaIndex);
    expect(summaryIndex).toBeGreaterThan(checklistIndex);
  });

  it("falls back to the default order when sectionOrder is omitted", () => {
    const withDefaultOrder = composeTaskPrBody(baseTaskInput);
    const withExplicitDefaultOrder = composeTaskPrBody({ ...baseTaskInput, sectionOrder: [...DEFAULT_TASK_SECTION_ORDER] });
    expect(withDefaultOrder).toBe(withExplicitDefaultOrder);
  });
});
