export type McpRuntimeRole = "project_manager";

export type McpToolCategory = "orchestration" | "agents_memory" | "platform" | "advanced";

export const TOOL_DEFINITIONS = [
  {
    name: "manage_code_ux",
    runtimeRoles: ["project_manager"],
    category: "advanced",
    description: "(Deprecated) Manage internal Code UX state. Used for configuration and destructive actions. Destructive actions require approval confirmation.",
    inputSchema: {
      type: "object",
      properties: {
        domain: { type: "string", description: "The management domain (e.g., 'system', 'projects', 'settings')." },
        action: { type: "string", description: "The specific management action to perform." },
        payload: { type: "object", additionalProperties: true, description: "Action-specific parameters." },
        approval: {
          type: "object",
          properties: {
            confirmed: { type: "boolean", description: "Set to true to confirm a destructive action after reviewing the approval requirement." },
          },
        },
      },
      required: ["domain", "action", "payload"],
    },
  },
  {
    name: "manage_projects",
    runtimeRoles: ["project_manager"],
    category: "orchestration",
    description: "Manage Code UX projects. Used to list, get, create, update, select, setup, and delete projects. Destructive actions require approval confirmation.",
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["list", "get", "create", "update", "select", "setup", "delete"], description: "The project action to perform." },
        projectId: { type: "string", description: "Required for get, update, select, setup, delete." },
        name: { type: "string", description: "Required for create. Optional for update." },
        description: { type: "string", description: "Optional for create and update." },
        setup: {
          type: "object",
          additionalProperties: true,
          description: "Optional setup request with enabled and options flags. For setup action, options.docs=true embeds discovered repository documentation into Knowledge docs.",
          properties: {
            enabled: { type: "boolean", description: "Set to true when requesting setup during project creation." },
            options: {
              type: "object",
              additionalProperties: true,
              description: "Project setup options. docs defaults to false unless explicitly requested.",
              properties: {
                agents: { type: "boolean", description: "Generate repository-specific coding agents." },
                quicksprints: { type: "boolean", description: "Generate repository-specific quicksprint templates." },
                previewScript: { type: "boolean", description: "Generate a preview container startup script." },
                ci: { type: "boolean", description: "Generate basic CI workflow files." },
                techstack: { type: "boolean", description: "Detect and select the project techstack." },
                docs: { type: "boolean", description: "Embed discovered repository documentation into the Knowledge docs library. Defaults to false." },
              },
            },
          },
        },
        options: {
          type: "object",
          additionalProperties: true,
          description: "Top-level project setup options for action=setup. Supports docs=true to embed discovered repository documentation.",
          properties: {
            agents: { type: "boolean", description: "Generate repository-specific coding agents." },
            quicksprints: { type: "boolean", description: "Generate repository-specific quicksprint templates." },
            previewScript: { type: "boolean", description: "Generate a preview container startup script." },
            ci: { type: "boolean", description: "Generate basic CI workflow files." },
            techstack: { type: "boolean", description: "Detect and select the project techstack." },
            docs: { type: "boolean", description: "Embed discovered repository documentation into the Knowledge docs library. Defaults to false." },
          },
        },
        approval: {
          type: "object",
          properties: {
            confirmed: { type: "boolean", description: "Set to true to confirm a destructive action." },
          },
        },
      },
      required: ["action"],
    },
  },
  {
    name: "manage_sprints",
    runtimeRoles: ["project_manager"],
    category: "orchestration",
    description: "Manage Code UX sprints. Used to list, get, create, update, delete, start, pause, cancel, force_cancel, inspect_run, import_issues, and plan. Destructive actions require approval.",
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["list", "get", "create", "update", "delete", "start", "pause", "cancel", "force_cancel", "inspect_run", "import_issues", "plan"], description: "The sprint action to perform." },
        projectId: { type: "string", description: "Required for list, create, start, inspect_run." },
        sprintId: { type: "string", description: "Required for get, update, delete, start, inspect_run." },
        sprintRunId: { type: "string", description: "Required for pause, cancel, force_cancel. Optional for inspect_run." },
        name: { type: "string", description: "Optional sprint title for create and update." },
        title: { type: "string", description: "Alias for name. Optional for create and update." },
        goal: { type: "string", description: "Optional for create and update." },
        goalMarkdown: { type: "string", description: "Alias for goal. Optional for create and update." },
        originalPrompt: { type: "string", description: "Optional source prompt for create and update." },
        status: { type: "string", description: "Optional sprint status for create/update, Jira status (open, in_progress, done, all), or provider status for import_issues." },
        showcasePinned: { type: "boolean", description: "Optional for create and update." },
        agentPresetId: { type: "string", description: "Optional for create and update." },
        planningAgentPresetId: { type: "string", description: "Optional for plan." },
        autoStart: { type: "boolean", description: "Optional for plan and for import_issues when planAfterImport is true." },
        replan: { type: "boolean", description: "Optional for plan." },
        search: { type: "string", description: "Optional issue search query for import_issues." },
        provider: { type: "string", enum: ["github", "gitlab", "jira", "notion", "asana", "linear", "miro", "lucid", "figma", "mural"], description: "Optional issue provider for import_issues." },
        repository: { type: "string", description: "Optional repository owner/name or project path for import_issues." },
        hostDomain: { type: "string", description: "Optional issue host domain for import_issues, such as github.com, gitlab.com, or a Jira site domain." },
        workspaceId: { type: "string", description: "Optional provider workspace id for Notion, Asana, and Linear imports." },
        providerProjectId: { type: "string", description: "Optional provider project id for Asana or Linear imports. Use this instead of Code UX projectId." },
        externalProjectId: { type: "string", description: "Alias for providerProjectId on import_issues." },
        asanaProjectId: { type: "string", description: "Alias for providerProjectId when importing Asana tasks." },
        linearProjectId: { type: "string", description: "Alias for providerProjectId when importing Linear issues." },
        teamId: { type: "string", description: "Optional Linear team id for import_issues." },
        teamKey: { type: "string", description: "Optional Linear team key for import_issues." },
        databaseId: { type: "string", description: "Optional Notion database id for import_issues." },
        boardId: { type: "string", description: "Optional Miro board id for board/item imports." },
        documentId: { type: "string", description: "Optional Lucid document id for Lucidchart or Lucidspark imports." },
        fileKey: { type: "string", description: "Optional Figma or FigJam file key for file imports." },
        muralId: { type: "string", description: "Optional Mural id for Mural imports." },
        itemTypes: { type: "array", items: { type: "string" }, description: "Optional Miro item type filters for board item imports." },
        projectKey: { type: "string", description: "Optional Jira project key for import_issues." },
        state: { type: "string", description: "Optional GitHub/GitLab issue state (open, closed, all) or Linear workflow state for import_issues." },
        labels: { type: "array", items: { type: "string" }, description: "Optional labels to filter or identify imported issues." },
        assignee: { type: "string", description: "Optional GitHub/GitLab assignee filter for import_issues." },
        assigneeText: { type: "string", description: "Optional Jira assignee text filter for import_issues, such as me, unassigned, or an account identifier." },
        issueText: { type: "string", description: "Optional issue text or exact issue reference for import_issues." },
        issueKeys: { type: "array", items: { type: "string" }, description: "Optional explicit Jira issue keys for import_issues." },
        issueNumbers: { type: "array", items: { type: "number" }, description: "Optional explicit GitHub/GitLab issue numbers for import_issues." },
        issueRefs: { type: "array", items: { type: "string" }, description: "Optional explicit issue references for import_issues, such as #123 or OPS-42." },
        externalIds: { type: "array", items: { type: "string" }, description: "Optional explicit Notion page/database ids, Asana task gids, Linear issue ids/identifiers, Miro item ids, Lucid document ids, Figma file keys, or Mural ids for import_issues." },
        includeConversation: { type: "boolean", description: "Optional import_issues flag controlling whether issue comments/conversation are included." },
        attachToSprint: { type: "boolean", description: "Optional import_issues flag controlling whether matching issues should be attached to sprintId when provided." },
        planAfterImport: { type: "boolean", description: "Optional import_issues flag requesting sprint planning after imported issues are attached." },
        limit: { type: "number", description: "Optional issue result limit for import_issues." },
        overrides: { type: "object", additionalProperties: true, description: "Optional planning overrides for plan." },
        approval: {
          type: "object",
          properties: {
            confirmed: { type: "boolean" },
          },
        },
      },
      required: ["action"],
    },
  },
  {
    name: "manage_tasks",
    runtimeRoles: ["project_manager"],
    category: "orchestration",
    description: "Manage Code UX tasks. Used to list, get, create, update, delete, start, stop, force_stop, pause, and inspect_run.",
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["list", "get", "create", "update", "delete", "start", "stop", "force_stop", "pause", "inspect_run"], description: "The task action to perform." },
        projectId: { type: "string", description: "Required for list and create." },
        sprintId: { type: "string", description: "Required for create. Optional filter for list." },
        taskId: { type: "string", description: "Required for get, update, delete, start, stop, force_stop, pause, inspect_run." },
        taskKey: { type: "string", description: "Optional stable task key for create." },
        name: { type: "string", description: "Alias for title on create and update." },
        title: { type: "string", description: "Optional for create, update." },
        promptMarkdown: { type: "string", description: "Optional for create, update." },
        description: { type: "string", description: "Optional for create, update." },
        status: { type: "string", enum: ["pending", "in_progress", "coding_completed", "completed", "QA_REVIEW_FAILED"], description: "Optional for create, update." },
        priority: { type: "string", enum: ["critical", "high", "medium", "low"], description: "Optional for create, update." },
        executorType: { type: "string", enum: ["auto", "docker_cli", "jules"], description: "Optional for create, update." },
        agentPresetId: { type: ["string", "null"], description: "Optional for create, update." },
        model: { type: ["string", "null"], description: "Optional for create, update." },
        sortOrder: { type: "number", description: "Optional for create, update." },
        dependsOnTaskIds: { type: "array", items: { type: "string" }, description: "Optional for create, update." },
        isIndependent: { type: "boolean", description: "Optional for create, update." },
        isMerged: { type: "boolean", description: "Optional for create, update." },
        provider: { type: "string", description: "Optional for start (rerun)." },
        approval: {
          type: "object",
          properties: {
            confirmed: { type: "boolean" },
          },
        },
      },
      required: ["action"],
    },
  },
  {
    name: "manage_quicksprints",
    runtimeRoles: ["project_manager"],
    category: "orchestration",
    description: "Manage Code UX quicksprints. Used to list, get, create, update, delete templates, and execute or start quicksprints. Deleting custom templates requires approval.",
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["list_templates", "get_template", "create_template", "update_template", "delete_template", "execute", "start"], description: "The quicksprint action to perform. Use start to plan and start immediately." },
        projectId: { type: "string", description: "Required for every action." },
        templateId: { type: "string", description: "Required for get_template, update_template, delete_template, execute, and start." },
        name: { type: "string", description: "Required for create_template. Optional for update_template." },
        description: { type: "string", description: "Required for create_template. Optional for update_template." },
        icon: { type: "string", description: "Required for create_template. Optional for update_template." },
        category: { type: "string", description: "Required for create_template. Optional for update_template." },
        categoryColor: { type: "string", description: "Optional template category color." },
        agentInstructionMarkdown: { type: "string", description: "Required for create_template. Optional for update_template." },
        defaultTaskCount: { type: ["number", "string"], description: "Optional default task count for a custom template." },
        taskCount: { type: ["number", "string"], description: "Optional task count for execute/start; defaults to 5." },
        noTaskLimit: { type: "boolean", description: "Optional flag that lets the planner choose the number of subtasks instead of enforcing taskCount." },
        submitMode: { type: "string", enum: ["plan_only", "plan_and_start"], description: "Optional execution mode. start defaults to plan_and_start; execute defaults to plan_only." },
        routeOverride: { type: "string", description: "Optional route override for execution." },
        modelOverride: { type: "string", description: "Optional model override for planning." },
        planningOverrides: { type: "object", additionalProperties: true, description: "Optional planning overrides." },
        agentPresetId: { type: "string", description: "Optional agent preset override." },
        additionalPrompt: { type: "string", description: "Optional additional planning instructions." },
        approval: {
          type: "object",
          properties: {
            confirmed: { type: "boolean" },
          },
        },
      },
      required: ["action"],
    },
  },
  {
    name: "manage_scheduler",
    runtimeRoles: ["project_manager"],
    category: "orchestration",
    description: "Manage Code UX scheduler entries. Used to list, create, schedule_sprint, schedule_quicksprint, schedule_chat, schedule_node_flow, update, delete, and run_due. Entries can use an absolute scheduledFor time, an after_sprint_end anchor, or an after_task_end anchor. Scheduled chat entries post messages through the chat runtime when due. Scheduled node flows run through the node flow runtime when due. Deleting entries requires approval.",
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["list", "create", "schedule_sprint", "schedule_quicksprint", "schedule_chat", "schedule_node_flow", "update", "delete", "run_due"], description: "The scheduler action to perform." },
        projectId: { type: "string", description: "Required for list and create/schedule actions." },
        entryId: { type: "string", description: "Required for update and delete." },
        from: { type: "string", description: "Optional ISO start for list window." },
        to: { type: "string", description: "Optional ISO end for list window." },
        title: { type: "string", description: "Optional scheduler entry title. For schedule_chat this can also become the chat thread title." },
        targetType: { type: "string", enum: ["sprint", "quicksprint", "chat", "node_flow"], description: "Required for generic create. schedule_* actions infer this." },
        status: { type: "string", enum: ["scheduled", "paused", "completed", "failed", "cancelled"], description: "Optional for update." },
        scheduledFor: { type: "string", description: "Required ISO date for absolute create/schedule actions. Optional for update or anchored entries." },
        scheduleMode: { type: "string", enum: ["absolute", "after_sprint_end", "after_task_end"], description: "Optional schedule mode. Defaults to absolute when scheduledFor is used." },
        anchorMode: { type: "string", enum: ["after_sprint_end", "after_task_end"], description: "Alias for scheduleMode when creating or updating an anchored entry." },
        scheduleAnchor: { type: "object", additionalProperties: true, description: "Nested anchor payload. For after_sprint_end, requires mode and sourceSprintId; for after_task_end, requires mode and sourceTaskId; supports offsetMinutes." },
        sourceSprintId: { type: "string", description: "Flattened source sprint id for after_sprint_end anchored schedules." },
        anchorSourceSprintId: { type: "string", description: "Alias for sourceSprintId for after_sprint_end anchored schedules." },
        sourceTaskId: { type: "string", description: "Flattened source task id for after_task_end anchored schedules." },
        anchorSourceTaskId: { type: "string", description: "Alias for sourceTaskId for after_task_end anchored schedules." },
        offsetMinutes: { type: ["number", "string"], description: "Non-negative delay in minutes after the source sprint or task ends before the entry becomes due." },
        anchorOffsetMinutes: { type: ["number", "string"], description: "Alias for offsetMinutes for anchored schedules." },
        timezone: { type: "string", description: "Optional timezone identifier; defaults to UTC." },
        recurrence: { type: "object", additionalProperties: true, description: "Optional recurrence rule with frequency, interval, endMode, count, and until." },
        sprintTarget: { type: "object", additionalProperties: true, description: "Nested sprint target. Requires sprintId." },
        quicksprintTarget: { type: "object", additionalProperties: true, description: "Nested quicksprint target. Requires templateId; supports taskCount, submitMode, additionalPrompt, agentPresetId, planningOverrides." },
        chatTarget: { type: "object", additionalProperties: true, description: "Nested chat target. Requires bodyMarkdown; supports threadId, title, and connectionId." },
        nodeFlowTarget: { type: "object", additionalProperties: true, description: "Nested node-flow target. Requires flowId; supports optional JSON input and flowVersion." },
        sprintId: { type: "string", description: "Flattened sprint target id for schedule_sprint/create/update." },
        templateId: { type: "string", description: "Flattened quicksprint template id for schedule_quicksprint/create/update." },
        taskCount: { type: ["number", "string"], description: "Flattened quicksprint task count; defaults to 5 unless noTaskLimit is true." },
        noTaskLimit: { type: "boolean", description: "Flattened quicksprint flag that disables the fixed task count prompt." },
        submitMode: { type: "string", enum: ["plan_only", "plan_and_start"], description: "Flattened quicksprint submit mode; defaults to plan_and_start." },
        additionalPrompt: { type: "string", description: "Flattened quicksprint additional prompt." },
        agentPresetId: { type: "string", description: "Flattened quicksprint agent preset override." },
        planningOverrides: { type: "object", additionalProperties: true, description: "Flattened quicksprint planning overrides." },
        bodyMarkdown: { type: "string", description: "Flattened chat message body for schedule_chat/create/update." },
        threadId: { type: ["string", "null"], description: "Optional existing chat thread id for scheduled chat messages." },
        connectionId: { type: ["string", "null"], description: "Optional chat connection id for scheduled chat messages." },
        flowId: { type: "string", description: "Flattened node-flow id for schedule_node_flow/create/update." },
        input: { type: "object", additionalProperties: true, description: "Optional JSON input object for scheduled node-flow runs." },
        flowVersion: { type: ["number", "string"], description: "Optional persisted node-flow version pin metadata." },
        now: { type: "string", description: "Optional ISO override for run_due evaluation." },
        approval: {
          type: "object",
          properties: {
            confirmed: { type: "boolean" },
          },
        },
      },
      required: ["action"],
    },
  },
  {
    name: "scheduler_code_ux",
    runtimeRoles: ["project_manager"],
    category: "orchestration",
    description: "Schedule agent-owned wakeups. Supports list, schedule_wakeup, and cancel only. Cancellation is limited to agent_scheduler wakeup entries created by the calling agent.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        action: { type: "string", enum: ["list", "schedule_wakeup", "cancel"], description: "The restricted agent scheduler action to perform." },
        projectId: { type: "string", description: "Required for list and schedule_wakeup." },
        entryId: { type: "string", description: "Required for cancel." },
        from: { type: "string", description: "Optional ISO start for list window." },
        to: { type: "string", description: "Optional ISO end for list window." },
        scheduledFor: { type: "string", description: "Absolute ISO time for schedule_wakeup. Mutually exclusive with relative delays, wakeAfterReply, and finish anchors." },
        delaySeconds: { type: ["number", "string"], description: "Positive relative delay in seconds for schedule_wakeup." },
        delayMinutes: { type: ["number", "string"], description: "Positive relative delay in minutes for schedule_wakeup." },
        wakeAfterReply: { type: "boolean", description: "For schedule_wakeup, wake the agent as soon as the current reply has been sent. Mutually exclusive with scheduledFor, delaySeconds, delayMinutes, afterSprintId, and afterTaskId." },
        afterSprintId: { type: "string", description: "For schedule_wakeup, wake after this sprint reaches a terminal state. Mutually exclusive with absolute/relative time and afterTaskId." },
        afterTaskId: { type: "string", description: "For schedule_wakeup, wake after this task reaches a terminal project status. Mutually exclusive with absolute/relative time and afterSprintId." },
        offsetMinutes: { type: ["number", "string"], description: "Optional non-negative delay after afterSprintId or afterTaskId completes." },
        title: { type: "string", description: "Optional scheduler entry title. Wakeups also use this as the chat thread title when applicable." },
        timezone: { type: "string", description: "Optional timezone identifier; defaults to UTC." },
        bodyMarkdown: { type: "string", description: "Required for schedule_wakeup." },
        threadId: { type: ["string", "null"], description: "Optional existing chat thread id for schedule_wakeup." },
        connectionId: { type: ["string", "null"], description: "Optional chat connection id for schedule_wakeup." },
      },
      required: ["action"],
    },
  },
  {
    name: "manage_agents",
    runtimeRoles: ["project_manager"],
    category: "agents_memory",
    description: "Manage Code UX agents. Used to list, get, sync, create, update, and delete agent presets.",
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["list", "get", "sync", "create", "update", "delete"], description: "The agent action to perform." },
        projectId: { type: "string", description: "Required for list, get, sync, create, update, delete." },
        presetId: { type: "string", description: "Required for get, update, delete." },
        name: { type: "string", description: "Required for create, optional for update." },
        description: { type: "string", description: "Optional for create, update." },
        instructionMarkdown: { type: "string", description: "Optional for create, update." },
        labels: { type: "array", items: { type: "string" }, description: "Optional for create, update." },
        avatarConfig: { type: "object", additionalProperties: true, description: "Optional for create, update." },
        providerConfigId: { type: ["string", "null"], description: "Optional provider config id for create, update." },
        model: { type: ["string", "null"], description: "Optional model override for create, update." },
        memoryConfig: { type: "object", additionalProperties: true, description: "Optional memory injection config for create, update." },
        mcpAccess: {
          type: "object",
          additionalProperties: true,
          description: "Optional per-agent MCP access config for create, update. Use codeUxEnabled plus codeUxToolToggles to grant tools such as manage_node_flows without replacing unrelated agent settings.",
        },
        memoryTemplateOverrideEnabled: { type: "boolean", description: "Optional for create, update." },
        memoryTemplateMarkdown: { type: "string", description: "Optional for create, update." },
        approval: {
          type: "object",
          properties: {
            confirmed: { type: "boolean" },
          },
        },
      },
      required: ["action"],
    },
  },
  {
    name: "manage_node_flows",
    runtimeRoles: ["project_manager"],
    category: "agents_memory",
    description: "Manage Code UX node flows as reusable agent skills. Supports list, get, create, update, delete, validate, run, list_runs, get_run, attach_to_agent, and detach_from_agent. Build Code UX-adapted flows with typed graph nodes and dynamic widget schemas for editable fields; do not clone n8n workflows one-to-one. Deleting flows requires approval confirmation.",
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["list", "get", "create", "update", "delete", "validate", "run", "list_runs", "get_run", "attach_to_agent", "detach_from_agent"], description: "The node-flow action to perform." },
        projectId: { type: "string", description: "Required for list, create, run, and validation of new graph specs." },
        flowId: { type: "string", description: "Required for get, update, delete, run, list_runs, attach_to_agent, and detach_from_agent." },
        runId: { type: "string", description: "Required for get_run." },
        name: { type: "string", description: "Required for create. Optional title for update." },
        description: { type: "string", description: "Optional flow or attached skill description." },
        graph: { type: "object", additionalProperties: true, description: "Structured node-flow graph. Required for create and standalone validate. Optional for update and validate existing flow." },
        widgets: { type: "object", additionalProperties: true, description: "Optional dynamic widget schemas for editable graph inputs or node fields. Use a fields array for graph inputSchema or node-id keys for node widgetSchema entries." },
        input: { type: "object", additionalProperties: true, description: "Optional JSON object passed to run." },
        agentPresetId: { type: "string", description: "Required for attach_to_agent and detach_from_agent." },
        skillAlias: { type: "string", description: "Optional display name for the attached node-flow skill." },
        approval: {
          type: "object",
          properties: {
            confirmed: { type: "boolean" },
          },
        },
      },
      required: ["action"],
    },
  },
  {
    name: "manage_memory",
    runtimeRoles: ["project_manager"],
    category: "agents_memory",
    description: "Manage Code UX memory. Used to search, list, get, create, update, delete, promote, start_reembed, get_map, count, model_status, and durable claim actions. Destructive memory and claim actions require approval confirmation.",
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["search", "list", "get", "create", "update", "delete", "promote", "start_reembed", "get_map", "count", "model_status", "create_claim", "list_claims", "get_claim", "update_claim", "add_claim_evidence", "deprecate_claim"], description: "The memory action to perform." },
        projectId: { type: "string", description: "Required for search, list, create, promote, start_reembed, get_map, count, and claim actions." },
        memoryId: { type: "string", description: "Required for get, update, delete, and add_claim_evidence." },
        claimId: { type: "string", description: "Required for get_claim, update_claim, add_claim_evidence, and deprecate_claim." },
        query: { type: "string", description: "Required for search." },
        scope: { type: "string", description: "Optional for search, list, create, get_map. Required for count." },
        sprintId: { type: "string", description: "Optional for search, list, create, get_map." },
        agentPresetId: { type: "string", description: "Optional for search, list, create, get_map." },
        limit: { type: "number", description: "Optional for search, list, and list_claims." },
        minSimilarity: { type: "number", description: "Optional for search." },
        content: { type: "string", description: "Required for create. Optional for update." },
        claim: { type: "string", description: "Required for create_claim. Optional for update_claim." },
        category: { type: "string", enum: ["architecture", "codebase", "context", "preferences", "patterns", "decision", "error", "learning"], description: "Optional for create, update, create_claim, update_claim, and list_claims." },
        strength: { type: "number", description: "Optional for create, update." },
        confidence: { type: "number", description: "Optional 0-1 confidence for create_claim and update_claim." },
        durability: { type: "number", description: "Optional 0-1 durability for create_claim and update_claim." },
        status: { type: "string", enum: ["active", "superseded", "deprecated"], description: "Optional for list_claims and update_claim." },
        tags: { type: "array", items: { type: "string" }, description: "Optional for create_claim and update_claim." },
        appliesToPaths: { type: "array", items: { type: "string" }, description: "Optional for create_claim and update_claim." },
        sourceMemoryId: { type: "string", description: "Optional source memory for create_claim; linked as supporting evidence when provided." },
        supersedesClaimId: { type: ["string", "null"], description: "Optional claim superseded by create_claim or update_claim." },
        supportType: { type: "string", enum: ["supports", "contradicts", "supersedes"], description: "Optional for add_claim_evidence and create_claim source evidence." },
        weight: { type: "number", description: "Optional 0-1 evidence weight for add_claim_evidence and create_claim source evidence." },
        evidenceWeight: { type: "number", description: "Alias for weight when adding source evidence during create_claim." },
        memoryIds: { type: "array", items: { type: "string" }, description: "Required for promote." },
        reason: { type: "string", description: "Optional for promote." },
        topKPerNode: { type: "number", description: "Optional for get_map." },
        approval: {
          type: "object",
          properties: {
            confirmed: { type: "boolean" },
          },
        },
      },
      required: ["action"],
    },
  },
  {
    name: "add_long_term_memory",
    runtimeRoles: ["project_manager"],
    category: "agents_memory",
    description: "Store one durable project fact, decision, preference, pattern, or learning directly in canonical long-term memory. This is the Project manager's dedicated remember/learn lane: use it when the user asks you to remember something or when stable project knowledge will materially improve future work. The write creates a canonical claim plus its searchable project-memory mirror and returns data for a rich confirmation widget.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        projectId: { type: "string", minLength: 1, description: "Project that owns the durable memory." },
        memory: { type: "string", minLength: 1, description: "A concise, self-contained durable statement. Record the reusable fact or decision, not the surrounding conversation." },
        category: { type: "string", enum: ["architecture", "codebase", "context", "preferences", "patterns", "decision", "learning"], description: "Durable knowledge category. Defaults to learning." },
        confidence: { type: "number", minimum: 0, maximum: 1, description: "Confidence in the statement. Defaults to 0.9." },
        durability: { type: "number", minimum: 0, maximum: 1, description: "Expected long-term relevance. Defaults to 0.9." },
        tags: { type: "array", maxItems: 20, items: { type: "string" }, description: "Optional concise retrieval tags." },
        appliesToPaths: { type: "array", maxItems: 50, items: { type: "string" }, description: "Optional repository paths where this knowledge applies." },
        sourceMemoryId: { type: "string", description: "Optional short-term memory to link as supporting evidence." },
      },
      required: ["projectId", "memory"],
    },
  },
  {
    name: "manage_skills",
    runtimeRoles: ["project_manager"],
    category: "agents_memory",
    description: "Manage persistent Code UX skills. Used to create and manage skill storages, attach storages to agents, import/export markdown skills, and retrieve the skill authoring guide. Destructive actions require approval confirmation.",
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["authoring_prompt", "list_storages", "get_storage", "create_storage", "update_storage", "delete_storage", "reset_storage", "list_agent_storages", "attach_storage", "detach_storage", "list_skills", "get_skill", "create_skill", "update_skill", "delete_skill", "import_markdown", "export_markdown"], description: "The skill management action to perform." },
        projectId: { type: "string", description: "Required for project-scoped storage, attachment, and skill actions." },
        storageId: { type: "string", description: "Required for storage update/delete/reset, listing skills, imports, and new skill creation." },
        skillId: { type: "string", description: "Required for get_skill, update_skill, delete_skill, export_markdown, and import_markdown updates." },
        agentPresetId: { type: "string", description: "Required for list_agent_storages, attach_storage, detach_storage, and optional for retrieval scoping." },
        name: { type: "string", description: "Required for create_storage. Optional storage name for update_storage." },
        description: { type: "string", description: "Optional storage description." },
        storageKind: { type: "string", enum: ["project", "shared"], description: "Optional storage kind. Defaults to project." },
        markdown: { type: "string", description: "Required for import_markdown, create_skill, and update_skill. Includes frontmatter plus instruction body." },
        sourceType: { type: "string", enum: ["manual", "imported", "generated"], description: "Optional source type for imported skills." },
        sourceRef: { type: ["string", "null"], description: "Optional source reference for imported skills." },
        limit: { type: "number", description: "Optional result limit for list_skills." },
        includeContent: { type: "boolean", description: "When true, get_skill includes full contentMarkdown. List and search responses stay concise." },
        approval: {
          type: "object",
          properties: {
            confirmed: { type: "boolean" },
          },
        },
      },
      required: ["action"],
    },
  },
  {
    name: "search_knowledge",
    runtimeRoles: ["project_manager"],
    category: "agents_memory",
    description: "Search your attached knowledge base. Returns the most relevant passages from the documents subscribed to you. Use a focused natural-language query to pull exact content before answering, instead of guessing. Scope is your own subscriptions — no project id needed.",
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string", description: "Natural-language search query describing what you need to find." },
        limit: { type: "number", description: "Maximum number of passages to return (default 5)." },
        minSimilarity: { type: "number", description: "Optional minimum cosine similarity threshold (0-1)." },
      },
      required: ["query"],
    },
  },
  {
    name: "search_skills",
    runtimeRoles: ["project_manager"],
    category: "agents_memory",
    description: "Search persistent Code UX skills by project, optional agent attachment, or optional storage. Returns concise ranked skill summaries with IDs and metadata; use manage_skills export_markdown or get_skill with includeContent for a full skill.",
    inputSchema: {
      type: "object",
      properties: {
        projectId: { type: "string", description: "Project whose persistent skill storage should be searched." },
        query: { type: "string", description: "Natural-language search query describing the skill guidance needed." },
        agentPresetId: { type: "string", description: "Optional agent preset id. When provided without storageId, only that agent's attached storages are searched." },
        storageId: { type: "string", description: "Optional storage id. When provided, search is limited to that project-owned storage." },
        limit: { type: "number", description: "Maximum number of skills to return. Defaults to 10 and is capped by the handler." },
        minSimilarity: { type: "number", description: "Optional minimum cosine similarity threshold from 0 to 1." },
      },
      required: ["projectId", "query"],
    },
  },
  {
    name: "manage_settings",
    runtimeRoles: ["project_manager"],
    category: "platform",
    description: "Manage Code UX settings. Used to get, resolve, patch, replace, reset, export, and apply system, project, and sprint settings. Mutating settings actions and secret-bearing bundles require a first human-confirmation response; only the same action and payload may execute once with approval.confirmed: true within 15 minutes.",
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["get_system", "get_project_override", "resolve_project_effective", "get_sprint_override", "resolve_sprint_effective", "replace_system_settings", "patch_system_setting", "replace_project_settings", "patch_project_setting", "reset_project_settings", "replace_sprint_settings", "patch_sprint_setting", "reset_sprint_settings", "export_settings_bundle", "apply_settings_bundle"], description: "The settings action to perform." },
        projectId: { type: "string", description: "Required for project and sprint actions." },
        sprintId: { type: "string", description: "Required for sprint actions." },
        projectIds: { type: "array", items: { type: "string" }, description: "Optional project ids for export_settings_bundle." },
        sprintIds: { type: "array", items: { type: "string" }, description: "Optional sprint ids for export_settings_bundle." },
        scopes: { type: "array", items: { type: "string", enum: ["system", "projects", "sprints"] }, description: "Optional bundle scopes for export_settings_bundle or apply_settings_bundle." },
        path: { type: "string", description: "Required for patch actions." },
        value: { description: "Required for patch actions. May be any JSON value." },
        settings: { type: "object", additionalProperties: true, description: "Required for replace actions." },
        bundle: { type: "object", additionalProperties: true, description: "Required for apply_settings_bundle." },
        includeSecrets: { type: "boolean", description: "When true, export_settings_bundle may include configured secret fields after approval." },
        approval: {
          type: "object",
          properties: {
            confirmed: { type: "boolean" },
          },
        },
      },
      required: ["action"],
    },
  },
  {
    name: "manage_custom_dashboards",
    runtimeRoles: ["project_manager"],
    category: "platform",
    description: "Manage project-scoped custom dashboards, immutable revisions, validation sessions, publication, archiving, and data catalog lookup. Archiving requires approval confirmation.",
    inputSchema: {
      type: "object",
      properties: {
        action: {
          type: "string",
          enum: [
            "list",
            "get",
            "create",
            "update",
            "create_revision",
            "validate_revision",
            "validation_status",
            "validation_logs",
            "publish_revision",
            "archive",
            "data_catalog",
          ],
          description: "The custom dashboard action to perform.",
        },
        projectId: { type: "string", description: "Required for list, create, validate_revision, and data_catalog." },
        dashboardId: { type: "string", description: "Required for get, update, create_revision, validate_revision, publish_revision, and archive." },
        revisionId: { type: "string", description: "Required for validate_revision and publish_revision." },
        sessionId: { type: "string", description: "Required for validation_status and validation_logs." },
        validationSessionId: { type: "string", description: "Optional passed validation session id for publish_revision." },
        title: { type: "string", description: "Required for create. Optional for update." },
        description: { type: "string", description: "Optional draft description." },
        manifest: { type: "object", additionalProperties: true, description: "Required for create. Optional override for update or create_revision." },
        fileBundle: { type: "object", additionalProperties: true, description: "Required for create. Optional override for update or create_revision." },
        sourceNodeGraph: { type: "object", additionalProperties: true, description: "Optional source graph for create, update, or create_revision." },
        styleguide: { type: "object", additionalProperties: true, description: "Optional styleguide JSON for create, update, or create_revision." },
        runtimeMetadata: { type: "object", additionalProperties: true, description: "Optional runtime metadata JSON for create, update, or create_revision." },
        tail: { type: ["number", "string"], description: "Optional validation log tail line count." },
        approval: {
          type: "object",
          properties: {
            confirmed: { type: "boolean" },
          },
        },
      },
      required: ["action"],
    },
  },
  {
    name: "manage_preview",
    runtimeRoles: ["project_manager"],
    category: "platform",
    description: "Manage Code UX sprint previews. Used to list, start, rebuild, stop, remove sessions, get script, get logs, and get url.",
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["list_sessions", "start_session", "rebuild_session", "stop_session", "remove_session", "get_script", "get_logs", "get_url"], description: "The preview action to perform." },
        projectId: { type: "string", description: "Required for list_sessions, start_session, get_script." },
        sprintId: { type: "string", description: "Required for start_session, get_script." },
        sessionId: { type: "string", description: "Required for rebuild, stop, remove, get_logs, get_url." },
        path: { type: "string", description: "Optional for get_url." },
        approval: {
          type: "object",
          properties: {
            confirmed: { type: "boolean" },
          },
        },
      },
      required: ["action"],
    },
  },
  {
    name: "manage_chat_providers",
    runtimeRoles: ["project_manager"],
    category: "platform",
    description: "Manage external chat provider setup definitions, provider connections, channel bindings, and outbound delivery state. Deleting records and replacing non-empty secret payloads require approval confirmation.",
    inputSchema: {
      type: "object",
      properties: {
        action: {
          type: "string",
          enum: [
            "list_provider_definitions",
            "list_connections",
            "get_connection",
            "create_connection",
            "update_connection",
            "delete_connection",
            "list_channel_bindings",
            "create_channel_binding",
            "update_channel_binding",
            "delete_channel_binding",
            "list_outbound_deliveries",
          ],
          description: "The chat provider management action to perform.",
        },
        providerKind: { type: "string", enum: ["whatsapp", "imessage", "telegram", "slack", "microsoft-teams", "discord"], description: "Optional provider kind filter, or required for create_connection." },
        providerConnectionId: { type: "string", description: "Provider connection id. Required for get_connection, update_connection, delete_connection, and binding creation." },
        connectionId: { type: "string", description: "Alias for providerConnectionId." },
        displayName: { type: "string", description: "Connection display name. Required for create_connection and optional for update_connection." },
        bridgeMode: { type: "string", enum: ["managed_bridge", "webhook", "native_bridge"], description: "Optional provider bridge mode." },
        status: { type: "string", enum: ["draft", "active", "disabled", "error"], description: "Optional provider connection status for create_connection and update_connection." },
        enabled: { type: "boolean", description: "Optional enabled flag for connection or binding mutations." },
        enabledOnly: { type: "boolean", description: "Optional list filter that returns only enabled connections or bindings." },
        setup: { type: "object", additionalProperties: true, description: "Non-secret provider setup values. Secret-shaped keys are sanitized by the repository." },
        secrets: { type: ["object", "null"], additionalProperties: true, description: "Provider secret payload. Public MCP responses always return redacted credential metadata." },
        channelBindingId: { type: "string", description: "Channel binding id. Required for update_channel_binding and delete_channel_binding." },
        bindingId: { type: "string", description: "Alias for channelBindingId." },
        externalChannelId: { type: "string", description: "External provider channel id. Required for binding creation and optional for binding/delivery filters." },
        externalChannelName: { type: "string", description: "External provider channel label. Required for create_channel_binding and optional for update_channel_binding." },
        externalChannelMetadata: { type: ["object", "null"], additionalProperties: true, description: "Optional non-secret metadata about the external channel." },
        projectId: { type: "string", description: "Project id for binding creation or list filtering." },
        projectIds: { type: "array", items: { type: "string" }, description: "Optional project id filter set for list_channel_bindings." },
        agentPresetId: { type: ["string", "null"], description: "Optional project-manager agent preset id for a channel binding." },
        routingHints: { type: ["object", "null"], additionalProperties: true, description: "Optional non-secret routing hints for a channel binding." },
        inboundEnabled: { type: "boolean", description: "Optional binding inbound enablement flag." },
        outboundEnabled: { type: "boolean", description: "Optional binding outbound enablement flag." },
        suppressRichWidgets: { type: "boolean", description: "Optional binding display flag. Defaults to true when omitted." },
        deliveryStatus: { type: "string", enum: ["pending", "sending", "delivered", "processed", "failed", "duplicate", "cancelled"], description: "Optional outbound delivery status filter." },
        limit: { type: ["number", "string"], description: "Optional outbound delivery result limit. Defaults to 100 and is capped by the repository." },
        baseUrl: { type: "string", description: "Optional base URL used when generating ingress URL templates. Defaults to http://localhost:4444." },
        approval: {
          type: "object",
          properties: {
            confirmed: { type: "boolean" },
          },
        },
      },
      required: ["action"],
    },
  },
  {
    name: "manage_telemetry",
    runtimeRoles: ["project_manager"],
    category: "platform",
    description: "Manage Code UX telemetry. Used to get execution and stats snapshots, and list runs, dispatches, and invocations.",
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["get_project_execution_snapshot", "get_project_stats_snapshot", "list_sprint_runs", "list_task_dispatches", "list_execution_invocations", "list_execution_invocation_messages"], description: "The telemetry action to perform." },
        projectId: { type: "string", description: "Required for get_project_execution_snapshot, get_project_stats_snapshot, list_sprint_runs, list_task_dispatches, list_execution_invocations." },
        sprintId: { type: "string", description: "Required for list_sprint_runs, list_task_dispatches." },
        taskId: { type: "string", description: "Required for list_task_dispatches. Optional for list_execution_invocations." },
        invocationId: { type: "string", description: "Required for list_execution_invocation_messages." },
        type: { type: "string", description: "Optional for list_execution_invocations." },
      },
      required: ["action"],
    },
  },
  {
    name: "register_worker_endpoint",
    runtimeRoles: ["project_manager"],
    category: "platform",
    description: "Register or refresh an external Code UX worker endpoint and its eligible project scope.",
    inputSchema: {
      type: "object",
      properties: {
        connectionKey: { type: "string", description: "Stable worker connection key." },
        displayName: { type: "string", description: "Human-readable worker name." },
        transport: { type: "string", description: "Worker control-plane transport, usually streamable-http." },
        projectIds: { type: "array", items: { type: "string" }, description: "Full project eligibility set for this worker." },
        activeProjectIds: { type: "array", items: { type: "string" }, description: "Current polling/focus subset. Must be within projectIds when projectIds are provided." },
        capabilities: {
          type: "object",
          properties: {
            canSuperviseProjects: { type: "boolean" },
            canExecuteTasks: { type: "boolean" },
          },
          additionalProperties: false,
        },
        metadata: { type: "object", additionalProperties: true, description: "Bounded non-secret worker runtime metadata." },
      },
      required: ["connectionKey", "displayName", "transport"],
    },
  },
  {
    name: "pull_task_dispatch",
    runtimeRoles: ["project_manager"],
    category: "platform",
    description: "Claim the next eligible worker task dispatch for a registered external worker.",
    inputSchema: {
      type: "object",
      properties: {
        connectionKey: { type: "string", description: "Registered worker connection key." },
        projectId: { type: "string", description: "Optional project to poll. Must be enrolled for the worker." },
        sprintId: { type: "string", description: "Optional sprint filter." },
      },
      required: ["connectionKey"],
    },
  },
  {
    name: "update_task_dispatch",
    runtimeRoles: ["project_manager"],
    category: "platform",
    description: "Refresh worker dispatch heartbeat/state and return any control-plane action such as cancellation.",
    inputSchema: {
      type: "object",
      properties: {
        connectionKey: { type: "string", description: "Registered worker connection key." },
        dispatchId: { type: "string", description: "Claimed task dispatch id." },
        leaseToken: { type: "string", description: "Lease token returned by pull_task_dispatch." },
        state: { type: "string", enum: ["RUNNING", "COMPLETED", "FAILED", "BLOCKED", "QUOTA"], description: "Current worker task run state." },
        provider: { type: "string", description: "Optional provider id/name reported by the worker host." },
        sessionId: { type: "string", description: "Optional local worker-host session id." },
        sessionName: { type: "string", description: "Optional local worker-host session name." },
        workerBranch: { type: "string", description: "Optional branch used by the worker run." },
        prUrl: { type: "string", description: "Optional pull request URL produced by the worker run." },
        summaryMarkdown: { type: "string", description: "Optional completion or blocked summary." },
        errorMessage: { type: "string", description: "Optional error text for failed or blocked states." },
      },
      required: ["connectionKey", "dispatchId", "leaseToken", "state"],
    },
  },
] as const;

export type ToolName = (typeof TOOL_DEFINITIONS)[number]["name"];

export type ToolHandlerMap<TMap extends object> = {
  [K in keyof TMap]?: (args: TMap[K]) => Promise<unknown> | unknown;
};

export const dispatchTool = async <TMap extends object, K extends Extract<keyof TMap, string>>(
  name: string,
  args: unknown,
  handlers: ToolHandlerMap<TMap>
): Promise<unknown> => {
  const handler = handlers[name as keyof TMap];
  if (!handler) {
    throw new Error(`Tool not found: ${name}`);
  }
  return await handler(args as TMap[keyof TMap]);
};
