import type { DashboardSettings } from "../types.js";

export const DEFAULT_DASHBOARD_SETTINGS: DashboardSettings = {
  automationLevel: "SEMI_AUTO",
  aiProvider: {
    provider: "jules",
    strategy: "MANUAL",
    providers: {
      jules: {
        enabled: true,
        model: "default",
        weight: 60,
        thinkingMode: "MEDIUM",
        apiKey: "",
      },
      gemini: {
        enabled: true,
        model: "default",
        weight: 20,
        thinkingMode: "MEDIUM",
        apiKey: "",
      },
      codex: {
        enabled: true,
        model: "gpt-5.3-codex",
        weight: 20,
        thinkingMode: "HIGH",
        apiKey: "",
      },
    },
    julesApiKey: "",
  },
  git: {
    githubMode: "REMOTE",
    githubToken: "",
    defaultBranch: "main",
    autoCreatePr: true,
    featureBranchPrefix: "feature/",
    sprintBranchScheme: "feature/sprint{sprint}-implementation",
  },
  ciIntelligence: {
    enabled: true,
    waitForCiBeforeMainMerge: true,
    resolveAllCommentsBeforeMainMerge: true,
    waitForCiBeforeFeatureMerge: true,
    resolveAllCommentsBeforeFeatureMerge: true,
  },
  sprintLoopSteps: {
    branchPreflight: true,
    planningPreflight: true,
    loadSubtasks: true,
    sessionSync: true,
    statusDerivation: true,
    startReadyTasks: true,
    mergeProtocol: true,
    actionRequiredProtocol: true,
    statusTable: true,
    watchLoop: true,
  },
  cliWorkflow: {
    cleanupWorktreeOnSuccess: true,
    cleanupWorktreeOnFailure: false,
    retryOnReadFileNotFound: true,
    resumeFailedTaskInSameWorkspace: true,
    executionMode: "HOST",
    containerImage: "node:22-bookworm-slim",
    containerSetupScriptPath: "",
    containerMountCredentials: false,
    containerMountGitConfig: true,
    containerMountGithubAuth: true,
    containerMountGeminiAuth: true,
    containerMountCodexAuth: true,
    containerGithubAuthPath: "~/.config/gh",
    containerGeminiAuthPath: "~/.gemini",
    containerCodexAuthPath: "~/.codex",
  },
  skills: [
    { name: "orchestrator", enabled: true, isInternal: true },
    { name: "worker", enabled: true, isInternal: true },
    { name: "watch", enabled: true, isInternal: true },
    { name: "watch-skill", enabled: true, isInternal: true },
    { name: "sprint_agent_guide", enabled: true, isInternal: true },
    { name: "git_manager", enabled: true, isInternal: true },
    { name: "git_manager_remote", enabled: true, isInternal: true },
    { name: "git_manager_local", enabled: false, isInternal: true },
  ],
};

export const cloneDefaultSettings = (): DashboardSettings => ({
  automationLevel: DEFAULT_DASHBOARD_SETTINGS.automationLevel,
  aiProvider: {
    ...DEFAULT_DASHBOARD_SETTINGS.aiProvider,
    providers: {
      jules: { ...DEFAULT_DASHBOARD_SETTINGS.aiProvider.providers.jules },
      gemini: { ...DEFAULT_DASHBOARD_SETTINGS.aiProvider.providers.gemini },
      codex: { ...DEFAULT_DASHBOARD_SETTINGS.aiProvider.providers.codex },
    },
  },
  git: { ...DEFAULT_DASHBOARD_SETTINGS.git },
  ciIntelligence: { ...DEFAULT_DASHBOARD_SETTINGS.ciIntelligence },
  sprintLoopSteps: { ...DEFAULT_DASHBOARD_SETTINGS.sprintLoopSteps },
  cliWorkflow: { ...DEFAULT_DASHBOARD_SETTINGS.cliWorkflow },
  skills: DEFAULT_DASHBOARD_SETTINGS.skills.map((skill) => ({ ...skill })),
});
